<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="eng" xml:lang="eng"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Benjamin Thiry">
<meta name="description" content="Many international studies report a high prevalence of personality disorders among inmates on the basis of (semi) - structured diagnostic interviews. The present study proposes a self-reported evaluation of personality disorders using the NEO PI-R. The sample consists of 297 male and 26 female inmates (N = 323) who were psychologically assessed. The analysis of the five psychological domains shows that the French-speaking Belgian inmates are as stable, as extroverted, more closed, more agreeable and more conscientious than the normative sample. The NEO PI-R facets are also analysed. The mean Cohen’s d (.26) is small. Two personality disorders have medium effect sizes: obsessive compulsive personality disorder (high) and histrionic personality (low). Small effect sizes exist for antisocial personality (low), psychopathy (low), narcissistic personality (low), schizoid personality (high) and borderline personality (low). In our view, the context of the assessment can partially explain these results but not entirely. The results do not confirm previous studies and question the high rates of psychiatric prevalence in prison.">

<title>An Assessment of Personality Disorders with the Five-Factor Model among Belgian Inmates – Psychologie et délinquance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b53751a350365c71b6c909e95f209ed1.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-38d94b3cac77cd3e685c79e69241b0ba.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-86ef44f33eb6204f81838d6c66abc062.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="me" href="https://tchafia.be/@ouriagan">
<meta name="fediverse:creator" content="@ouriagan@tchafia.be">
<script>
  document.addEventListener("DOMContentLoaded", () => {
    const listing = document.querySelector(".quarto-listing-container");
    if (listing) {
      listing.classList.add("h-feed");
      const links = listing.querySelectorAll("a");
      links.forEach(link => {
        const article = document.createElement("article");
        article.classList.add("h-entry");
        link.classList.add("u-url");
        article.appendChild(link.cloneNode(true));
        link.replaceWith(article);
      });
    }
  });
</script>


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="An Assessment of Personality Disorders with the Five-Factor Model among Belgian Inmates – Psychologie et délinquance">
<meta property="og:description" content="Many international studies report a high prevalence of personality disorders among inmates on the basis of (semi) - structured diagnostic interviews. The present study proposes a self-reported evaluation of personality disorders using the NEO PI-R. The sample consists of 297 male and 26 female inmates (N = 323) who were psychologically assessed. The analysis of the five psychological domains shows that the French-speaking Belgian inmates are as stable, as extroverted, more closed, more agreeable and more conscientious than the normative sample. The NEO PI-R facets are also analysed. The mean Cohen’s d (.26) is small. Two personality disorders have medium effect sizes: obsessive compulsive personality disorder (high) and histrionic personality (low). Small effect sizes exist for antisocial personality (low), psychopathy (low), narcissistic personality (low), schizoid personality (high) and borderline personality (low). In our view, the context of the assessment can partially explain these results but not entirely. The results do not confirm previous studies and question the high rates of psychiatric prevalence in prison.">
<meta property="og:site_name" content="Psychologie et délinquance">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../benjaminthiry.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Psychologie et délinquance</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">Qui écrit ce blog ?</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://tchafia.be/@ouriagan"> <i class="bi bi-mastodon" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ouriagan/blog"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">An Assessment of Personality Disorders with the Five-Factor Model among Belgian Inmates</h1>
                  <div>
        <div class="description">
          Many international studies report a high prevalence of personality disorders among inmates on the basis of (semi) - structured diagnostic interviews. The present study proposes a self-reported evaluation of personality disorders using the NEO PI-R. The sample consists of 297 male and 26 female inmates (N = 323) who were psychologically assessed. The analysis of the five psychological domains shows that the French-speaking Belgian inmates are as stable, as extroverted, more closed, more agreeable and more conscientious than the normative sample. The NEO PI-R facets are also analysed. The mean Cohen’s d (.26) is small. Two personality disorders have medium effect sizes: obsessive compulsive personality disorder (high) and histrionic personality (low). Small effect sizes exist for antisocial personality (low), psychopathy (low), narcissistic personality (low), schizoid personality (high) and borderline personality (low). In our view, the context of the assessment can partially explain these results but not entirely. The results do not confirm previous studies and question the high rates of psychiatric prevalence in prison.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">analyses statistiques</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Benjamin Thiry </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">International Journal of Law and Psychiatry</div>
      <div class="quarto-title-meta-contents">
        <p class="date">1 juillet 2012</p>
      </div>
    </div>
    
      
      <div>
      <div class="quarto-title-meta-heading">Doi</div>
      <div class="quarto-title-meta-contents">
        <p class="doi">
          <a href="https://doi.org/https://doi.org/10.1016/j.ijlp.2012.04.010">https://doi.org/10.1016/j.ijlp.2012.04.010</a>
        </p>
      </div>
    </div>
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a>
  <ul class="collapse">
  <li><a href="#participants" id="toc-participants" class="nav-link" data-scroll-target="#participants">Participants</a></li>
  <li><a href="#procedure" id="toc-procedure" class="nav-link" data-scroll-target="#procedure">Procedure</a></li>
  <li><a href="#statistics" id="toc-statistics" class="nav-link" data-scroll-target="#statistics">Statistics</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Formally established in the 18th century as a mode of punishment, the prison sentence is the most serious penal sanction in democratic states that do not apply the death penalty. In some way, inmates still belong to the general population even if they are kept in security buildings. According to Walmsley (cited by Fazel &amp; Danesh, 2002), nine million people are imprisoned worldwide. Much research has been conducted in order to assess the frequency of psychiatric disorders in prisons. Motiuk and Porporino (1991) conducted a study on 2812 inmates in Canada and proposed a psychiatric diagnosis based on DSM-III (American Psychiatric Association, 1980) by using a structured interview. Prevalence rates were found to be: 74.9 % with antisocial personality disorder; 69.8 % alcohol abuse; 55.6 % with anxiety disorders; 52.9 % with disorders related to substances abuse; 29.5% with psychosexual disorders; 25.8 % with depressive disorders; 10.4 % with psychotic disorders and 4.3 % with organic disorders. Lafortune (2010) correlated correctional and medical records in order to assess 671 inmates entering prison. The ten most frequent psychiatric categories were anxiety disorders (40.2 %); drug dependence (25.2 %); depressive disorder (21.4 %); adjustment reactions (19.7 %); personality disorders (18 %), non-dependent abuse of drugs (14.5 %), alcohol dependence syndrome (11.6 %), drug psychoses (10.6 %) and general symptoms such as sleep problems or hallucinations (9.9 %). In total, 61 % of Quebec inmates had received at least one psychiatric diagnosis. Fazel and Danesh (2002) performed a meta-analysis of 62 studies involving 22 790 inmates. The most frequent diagnoses are personality disorders (65 % for men, 42 % for women), major depression (10 % for men, 12 % for women) and psychotic diseases (3.7 % for men, 4 % for women). They reported that inmates suffer from two to four times more psychosis or depression, and ten times more from antisocial personality disorder than the general population. They doubt that all these patients receive appropriate care to their pathology. Other researchers have emphasized the co-morbidity of psychiatric disorders with drug use and its disruptive effects (Piselli, Elisei,Murgia, Quartesan &amp; Abram, 2009). They underlined these impacts on employment, substance abuse, family and social functioning, and also the psychiatric symptomatology of inmates. Co-morbidity is much more important when considering forensic hospitals receiving offenders for whom a mental pathology was observed. According to Edens and Ruiz (2008), more than half of the inmates from forensic hospital receive more than one diagnosis. According to Pham and Saloppé (2010), 67.9 % of the patients of a Belgian forensic hospital have a co-morbidity, with on average 2.8 diagnoses by patient.</p>
<p>Most of the psychiatric studies in prison use (semi-) structured interviews to detect the presence or absence of mental pathology. However, this categorical approach has been criticised (Westen &amp; Arkiwotz-Westen, 1998 and Widiger &amp; Samuel, 2005) and has led to a dimensional conception of personality disorders (Costa &amp; Widiger, 2002). Lynam and Widiger (2001) defined prototypical profiles of each personality disorder based on the opinion of specialists. Therefore, the scores obtained by an individual to the NEO PI-R (Costa &amp; McCrae, 1998) allow the comparison with the typical profile of a personality disorder according to its description in the DSM-IV TR (American Psychiatric Association, 2000). The meta-analysis of Samuel and Widiger (2008) supports the hypothesis of a strong link between the variables of the Five-Factor Model (FFM) and personality disorders. This approach assesses personality disorders according to a dimensional logic, which is a more sensitive method. It is likely that the assessment of personality disorders in the DSM-V (planned for publication in 2013) will rely on the Five-Factor Model approach following a dimensional logic.</p>
<p>In Belgium, prisons have a <em>Psychosocial Service</em> with psychologists, social workers and psychiatrists. The prison permits adequate circumstances for psychological testing; e.g.&nbsp;each psychologist for example has of his own office. The main task of the Psychosocial Service consists of psychosocial assessment of the inmates concerning their request for conditional release. With the exception of inmates with sentences less then three years, all the inmates undergo a psychosocial assessment. The result of the assessment, which can take a few years, is given to the prison director and the judges of the court responsible for granting the conditional release. The psychologists meet the inmates several times and administer a battery of tests to help determine the diagnosis and the therapeutic indications.</p>
<p>One of the frequently used tests is the NEO PI-R because it assesses many personality variables. The Psychosocial Service disposes thus of a substantial number of protocols that can be used for a statistical analysis. Does the NEO PI-R reveal particular variables configurations? Does it highlight personality disorders in the prison population? What is the prevalence of co-morbid personality disorders? Are antisocial personality disorder and psychopathic disorder (Miller, Lynam, Widiger &amp; Leukefeld, 2001) prevalent in this population? Do forensic patients or female inmates show different profiles than regular inmates? We would also like to know if a self-reported inventory like the NEO PI-R provides relevant information to the psychological profile of inmates. This is the only study that deals with Personality Disorders using the NEO PI-R on a large prison sample.</p>
</section>
<section id="method" class="level1">
<h1>Method</h1>
<section id="participants" class="level2">
<h2 class="anchored" data-anchor-id="participants">Participants</h2>
<p>Our sample consists of 262 French-speaking inmates in Belgian prisons eligible for early release. Of these, 244 (93.1 %) are men and 18 (6.9 %) are women. Concerning the legal status, 248 (94.7 %) are sentenced and 14 (5.3 %) are forensic patients. The inmates are jailed in individual cells and are under the daily supervision of correctional officers. The forensic patients were recognized mentally irresponsible at the time of the offence and are jailed in special units of the prison, which provide psychiatric care. It was chosen to keep women and forensic patient in our sample as they are part of the prison population as well as the sentenced males. We wished our study to be representative of the actual prison population. This is a convenience sample obtained retrospectively. The average age is 35.5 years with a standard deviation equal to 11.1 and varies from 18 to 76 years.</p>
</section>
<section id="procedure" class="level2">
<h2 class="anchored" data-anchor-id="procedure">Procedure</h2>
<p>The NEO PI - R was obtained during a comprehensive psychological assessment. The psychologist in charge of the psychological assessment met the inmate in a quiet and private office. Preliminary psychological interviews assessed the cooperation of the inmate and his understanding of the French language, as self-reported personality questionnaires are not proposed to inmates who do not understand French, present a significant intellectual limitation or refuse psychological tests. In this study, we asked the French-speaking psychologists of the psychosocial service to provide NEO PI-R protocols they had previously administered. The protocols were gathered and anonymized by a membre of the Psychosocial Service and sent for data analysis. Some psychologists use this test very often while others never do because practicing psychologists prefer tests they know best in the task of psycho-diagnosis. This study aimed to receive as many completed tests as possible. This sample therefore has a weakness: the criterion for administration of the NEO PI-R was not strictly controlled. It is conceivable that psychologists have administered the NEO PI-R to the more conciliatory inmates. Some inmates also refuse to pass any psychological test. However, we find that the NEO PI-R is often well accepted by most inmates.</p>
<p>Personality assessment only takes place after a court decision (prison or internment) and so, inmates who are in custody are not tested by the Psychosocial Service. Therefore, participants in our sample have been held in detention for months or even years. This is important because it implies that our sample is not representative of inmates who face the shock due to recent incarceration. Indeed, the arrival in prison is a difficult time for most inmates, who discover a new, isolated and often violent world. Participants in our study know the prison rituals and probably exceeded the shock they experienced when they were arrested. Eligible for early release, they begin a project to leave the prison. Some inmates refuse psychosocial interviews or are considered as too dangerous to allow interviews. Therefore, these inmates have not been tested. These situations are rare and often transient. It may take several months before these meetings are possible. This study addressed this following prison population: French-speaking inmates who were currently undergoing the procedure for conditional release and who have completed the NEO PI-R.</p>
</section>
<section id="statistics" class="level2">
<h2 class="anchored" data-anchor-id="statistics">Statistics</h2>
<p>The 35 raw NEO PI-R scores were used and twelve personality disorders scores were collected from them (Miller, Lynam, Pham-Scottez, De Clercq, Rolland &amp; Fruyt, 2008 and Miller et al., 2001): paranoid, schizoid, schizotypal, antisocial, borderline, histrionic, narcissistic, avoidant, dependent, dependent revised, obsessive compulsive and psychopathy. These scores were compared with the French norms of the NEO PI-R (Costa &amp; McCrae, 1998) and those of the personality disorders (Miller, Lynam, Rolland, de Fruyt, Reynolds, Pham-Scottez, Baker, Bagby, 2008; Miller et al., 2001). Internal reliability of the NEO PI-R variable was assessed with the Cronbach’s alpha. The scores of male inmates were compared to those of female inmates. Sentenced inmates were also compared to the forensic patients.</p>
<p>To make these comparisons, the <em>t</em> test for independent samples was used. The value of <em>t</em> for each comparison and the associated <em>p</em> to assess the significance of the difference between the two means are described here. Beyond this significance, an assessment of the effect size of differences between means is also provided. Indeed, it is not only to affirm or not a difference between two means, but also to have some idea of the difference between them. Therefore, we also provide an index assessing the effect size, Cohen’s <em>d</em> (1992). The factor structure of personality variables is also provided. Indeed, this factor approach was chosen to evaluate the concept of comorbidity in a dimensional way. This allows the evaluation of the complex links between each personality disorder with all the others. It also helps to highlight the common factors that unite the personality disorders and thus understand their theoretical foundations better.</p>
<p>Given the context of obtaining data (through early releases), we used three validity scales developed by Schinka and Kremer (1997): Positive Presentation Management (PPM), Negative Presentation Management (NPM) and inconsistency (INC), which evaluate trends to present a positive self-image, a negative self-image, or incoherent responses to the questionnaire, respectively.</p>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>First, we calculated internal reliability indices of the five domains of the NEO PI-R using the six facets composing them. For N (Neuroticism), E (Extraversion), O (Openness), A (Agreeableness) and C (Conscientiousness), Cronbach’s alpha was respectively equal to .81, .70, .64, .69 and .81. These values are close to .70 and can be considered satisfactory.</p>
<p>Concerning the three validity scales of the NEO PI-R, the mean Negative Presentation Management (NPM) was equal to 9.99 (<em>SD</em> = 3.99), the mean Positive Presentation Management (PPM) was equal to 20.18 (<em>SD</em> = 4.08) and the mean response inconsistency variable (INC) was equal to 8.35 (<em>SD</em> = 3.22). Compared to Schinka and Kremer’s standards (1997), NPM is slightly higher (Cohen’s <em>d</em> = .26, <em>p</em> &lt;.001), PPM is in the standard (Cohen’s <em>d</em> = - .13, <em>p</em> = .06) and INC moderately higher (Cohen’s <em>d</em> = .63, <em>p</em> &lt;.001). These results suggest that inmates have not changed their answers in order to give positive impression. However, they would have answered the questions with more incoherence than the normative sample.</p>
<p>Table 1 shows descriptive statistics for each NEO PI-R variable, the effect size in comparison with the French normative sample, and the degree of significance.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Table 1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Descriptive Statistics of the 35 NEO PI-R variables for 262 Belgian French speaking inmates</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 39%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Mean</th>
<th style="text-align: left;"><em>SD</em></th>
<th style="text-align: left;"><em>t</em></th>
<th style="text-align: left;"><em>p</em></th>
<th style="text-align: left;">Cohen’s <em>d</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">N Neuroticism</td>
<td style="text-align: left;">91.32</td>
<td style="text-align: left;">19.98</td>
<td style="text-align: left;">-.76</td>
<td style="text-align: left;">.45</td>
<td style="text-align: left;">-0.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">E Extraversion</td>
<td style="text-align: left;">107.94</td>
<td style="text-align: left;">17.81</td>
<td style="text-align: left;">-1.90</td>
<td style="text-align: left;">.06</td>
<td style="text-align: left;">-0.12</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>O Openness</strong></td>
<td style="text-align: left;">105.85</td>
<td style="text-align: left;">14.41</td>
<td style="text-align: left;">-11.99</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">-0.64</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>A Agreeability</strong></td>
<td style="text-align: left;">127.00</td>
<td style="text-align: left;">15.93</td>
<td style="text-align: left;">5.89</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.36</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>C Conscientiousness</strong></td>
<td style="text-align: left;">122.42</td>
<td style="text-align: left;">17.84</td>
<td style="text-align: left;">5.93</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.34</td>
</tr>
<tr class="even">
<td style="text-align: left;">N1 Anxiety</td>
<td style="text-align: left;">17.15</td>
<td style="text-align: left;">4.62</td>
<td style="text-align: left;">-2.28</td>
<td style="text-align: left;">.02</td>
<td style="text-align: left;">-0.13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N2 Angry Hostility</td>
<td style="text-align: left;">13.97</td>
<td style="text-align: left;">4.50</td>
<td style="text-align: left;">-1.38</td>
<td style="text-align: left;">.17</td>
<td style="text-align: left;">-0.08</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>N3 Depression</strong></td>
<td style="text-align: left;">16.58</td>
<td style="text-align: left;">5.18</td>
<td style="text-align: left;">3.80</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N4 Self-Consciousness</td>
<td style="text-align: left;">16.26</td>
<td style="text-align: left;">4.24</td>
<td style="text-align: left;">1.20</td>
<td style="text-align: left;">.23</td>
<td style="text-align: left;">0.07</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>N5 Impulsiveness</strong></td>
<td style="text-align: left;">15.69</td>
<td style="text-align: left;">4.36</td>
<td style="text-align: left;">-4.45</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">-0.27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N6 Vulnerability</td>
<td style="text-align: left;">11.67</td>
<td style="text-align: left;">5.01</td>
<td style="text-align: left;">-.74</td>
<td style="text-align: left;">.46</td>
<td style="text-align: left;">-0.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">E1 Warmth</td>
<td style="text-align: left;">22.23</td>
<td style="text-align: left;">4.77</td>
<td style="text-align: left;">-.67</td>
<td style="text-align: left;">.50</td>
<td style="text-align: left;">-0.04</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E2 Gregariousness</td>
<td style="text-align: left;">17.44</td>
<td style="text-align: left;">5.21</td>
<td style="text-align: left;">.18</td>
<td style="text-align: left;">.86</td>
<td style="text-align: left;">0.01</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>E3 Assertiveness</strong></td>
<td style="text-align: left;">13.40</td>
<td style="text-align: left;">3.77</td>
<td style="text-align: left;">-4.17</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">-0.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E4 Activity</td>
<td style="text-align: left;">19.27</td>
<td style="text-align: left;">4.31</td>
<td style="text-align: left;">.85</td>
<td style="text-align: left;">.40</td>
<td style="text-align: left;">0.05</td>
</tr>
<tr class="even">
<td style="text-align: left;">E5 Excitement-Seeking</td>
<td style="text-align: left;">16.13</td>
<td style="text-align: left;">5.09</td>
<td style="text-align: left;">-1.50</td>
<td style="text-align: left;">.14</td>
<td style="text-align: left;">-0.10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E6 Positive Emotions</td>
<td style="text-align: left;">19.46</td>
<td style="text-align: left;">4.62</td>
<td style="text-align: left;">-2.27</td>
<td style="text-align: left;">.02</td>
<td style="text-align: left;">-0.14</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>O1 Fantasy</strong></td>
<td style="text-align: left;">14.82</td>
<td style="text-align: left;">4.23</td>
<td style="text-align: left;">-15.29</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">-0.85</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>O2 Aesthetics</strong></td>
<td style="text-align: left;">17.87</td>
<td style="text-align: left;">4.75</td>
<td style="text-align: left;">-3.03</td>
<td style="text-align: left;">.003</td>
<td style="text-align: left;">-0.17</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>O3 Feelings</strong></td>
<td style="text-align: left;">19.02</td>
<td style="text-align: left;">3.75</td>
<td style="text-align: left;">-8.81</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">-0.53</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>O4 Actions</strong></td>
<td style="text-align: left;">16.55</td>
<td style="text-align: left;">3.39</td>
<td style="text-align: left;">-3.88</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">-0.22</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>O5 Ideas</strong></td>
<td style="text-align: left;">18.70</td>
<td style="text-align: left;">4.33</td>
<td style="text-align: left;">-2.83</td>
<td style="text-align: left;">.005</td>
<td style="text-align: left;">-0.16</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>O6 Values</strong></td>
<td style="text-align: left;">18.89</td>
<td style="text-align: left;">3.39</td>
<td style="text-align: left;">-10.39</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">-0.61</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>A1 Trust</strong></td>
<td style="text-align: left;">16.63</td>
<td style="text-align: left;">4.86</td>
<td style="text-align: left;">-3.28</td>
<td style="text-align: left;">.001</td>
<td style="text-align: left;">-0.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>A2 Straightforwardness</strong></td>
<td style="text-align: left;">22.52</td>
<td style="text-align: left;">4.57</td>
<td style="text-align: left;">7.92</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.46</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>A3 Altruism</strong></td>
<td style="text-align: left;">24.87</td>
<td style="text-align: left;">3.77</td>
<td style="text-align: left;">7.83</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.49</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>A4 Compliance</strong></td>
<td style="text-align: left;">18.69</td>
<td style="text-align: left;">4.73</td>
<td style="text-align: left;">3.39</td>
<td style="text-align: left;">.001</td>
<td style="text-align: left;">0.21</td>
</tr>
<tr class="even">
<td style="text-align: left;">A5 Modesty</td>
<td style="text-align: left;">20.53</td>
<td style="text-align: left;">3.85</td>
<td style="text-align: left;">-.80</td>
<td style="text-align: left;">.43</td>
<td style="text-align: left;">-0.05</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>A6 Tender-Mindedness</strong></td>
<td style="text-align: left;">23.76</td>
<td style="text-align: left;">3.53</td>
<td style="text-align: left;">8.80</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.53</td>
</tr>
<tr class="even">
<td style="text-align: left;">C1 Competence</td>
<td style="text-align: left;">19.24</td>
<td style="text-align: left;">3.72</td>
<td style="text-align: left;">-.20</td>
<td style="text-align: left;">.84</td>
<td style="text-align: left;">-0.01</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>C2 Order</strong></td>
<td style="text-align: left;">20.44</td>
<td style="text-align: left;">4.39</td>
<td style="text-align: left;">7.90</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.46</td>
</tr>
<tr class="even">
<td style="text-align: left;">C3 Dutifulness</td>
<td style="text-align: left;">23.12</td>
<td style="text-align: left;">3.86</td>
<td style="text-align: left;">.93</td>
<td style="text-align: left;">.35</td>
<td style="text-align: left;">0.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>C4 Achievement Striving</strong></td>
<td style="text-align: left;">21.19</td>
<td style="text-align: left;">4.05</td>
<td style="text-align: left;">8.36</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.49</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>C5 Self-discipline</strong></td>
<td style="text-align: left;">21.79</td>
<td style="text-align: left;">4.09</td>
<td style="text-align: left;">9.53</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.53</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C6 Deliberation</td>
<td style="text-align: left;">16.63</td>
<td style="text-align: left;">4.76</td>
<td style="text-align: left;">-.97</td>
<td style="text-align: left;">.33</td>
<td style="text-align: left;">-0.05</td>
</tr>
</tbody>
</table>
<p>Significant scores are highlighted in bold text. Concerning the five domains, three are significantly different from the normative sample: the Openness is lower, Agreeableness and Conscientiousness are higher. This profile suggests that the French-speaking Belgian inmates are as stable, as extraverted, more frank, more agreeable and more conscientious than the normative population.</p>
<p>The study of the NEO PI-R facets gives more detailed results. Indeed, in descending effect sizes order, French-speaking Belgian inmates tend to be more prosaic, more conservative, colder, more altruistic, more disciplined, more ambitious, more frank, more orderly, more tolerant to frustration, less assertive, more discouraged, most submitted, more cynical, less aesthetic, less curious, less happy and less anxious than the normative population. Note that only one difference can be seen as large (Cohen’s <em>d</em> for O1 = -. 85) and others are lower. The mean of the absolute values of the 35 Cohen’s <em>d</em> is equal to .26. Differences, while statistically significant, remain low. Table 2 shows descriptive statistics for each NEO PI-R personality disorders variable.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Table 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Descriptive Statistics of the 12 NEO PI-R Personality Disorders variables for 262 French-speaking Belgian inmates</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Mean</th>
<th style="text-align: left;">SD</th>
<th style="text-align: left;"><em>t</em></th>
<th style="text-align: left;"><em>p</em></th>
<th style="text-align: left;">Cohen’s <em>d</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Paranoid</td>
<td style="text-align: left;">120.39</td>
<td style="text-align: left;">23.87</td>
<td style="text-align: left;">-2.18</td>
<td style="text-align: left;">.03</td>
<td style="text-align: left;">-0.13</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Schizoid</strong></td>
<td style="text-align: left;">112.50</td>
<td style="text-align: left;">20.37</td>
<td style="text-align: left;">3.89</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Schizotypal</td>
<td style="text-align: left;">100.54</td>
<td style="text-align: left;">16.63</td>
<td style="text-align: left;">-2.39</td>
<td style="text-align: left;">.02</td>
<td style="text-align: left;">-0.14</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Antisocial</strong></td>
<td style="text-align: left;">225.05</td>
<td style="text-align: left;">32.01</td>
<td style="text-align: left;">-5.84</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">-0.36</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Borderline</strong></td>
<td style="text-align: left;">139.29</td>
<td style="text-align: left;">23.21</td>
<td style="text-align: left;">-3.35</td>
<td style="text-align: left;">.001</td>
<td style="text-align: left;">-0.20</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Histrionic</strong></td>
<td style="text-align: left;">196.32</td>
<td style="text-align: left;">21.88</td>
<td style="text-align: left;">-9.08</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">-0.51</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Narcissist</strong></td>
<td style="text-align: left;">163.53</td>
<td style="text-align: left;">25.30</td>
<td style="text-align: left;">-4.20</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">-0.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">Avoidant</td>
<td style="text-align: left;">158.94</td>
<td style="text-align: left;">21.93</td>
<td style="text-align: left;">2.47</td>
<td style="text-align: left;">.01</td>
<td style="text-align: left;">0.14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dependent</td>
<td style="text-align: left;">119.53</td>
<td style="text-align: left;">15.67</td>
<td style="text-align: left;">.34</td>
<td style="text-align: left;">.74</td>
<td style="text-align: left;">0.02</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Dependent-Revised</strong></td>
<td style="text-align: left;">84.63</td>
<td style="text-align: left;">19.62</td>
<td style="text-align: left;">-3.19</td>
<td style="text-align: left;">.002</td>
<td style="text-align: left;">-0.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Obsessive-compulsive</strong></td>
<td style="text-align: left;">226.59</td>
<td style="text-align: left;">23.24</td>
<td style="text-align: left;">9.32</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">0.52</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Psychopathy</strong></td>
<td style="text-align: left;">269.56</td>
<td style="text-align: left;">29.99</td>
<td style="text-align: left;">-5.47</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">-0.33</td>
</tr>
</tbody>
</table>
<p>Two personality disorders have medium effect sizes: high obsessive compulsive personality disorder and low histrionic personality. Small effect sizes exist for antisocial personality (low score), psychopathy (low score), narcissistic personality (low score), schizoid personality (high score) and borderline personality (low score). The mean of the absolute values of the 12 Cohen’s <em>d</em> is also equal to. 26. Only 4 % of the participants have an antisocial personality score above 1.5 SD (the lowest cut-off chosen by Miller et al., 2001) and only 3% have a psychopathic score above 1.5 SD. Table 3 compares the scores of men with women.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Table 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Comparison of the 35 NEO PI-R variables for 244 male and 18 female Belgian inmates</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 34%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">Mean</th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Variable</td>
<td style="text-align: left;">Men</td>
<td>Women</td>
<td><em>t</em></td>
<td><em>p</em></td>
<td>Cohen’s <em>d</em></td>
</tr>
<tr class="even">
<td>N Neuroticism</td>
<td style="text-align: left;">90.60</td>
<td>101.06</td>
<td>-2.158*</td>
<td>.032</td>
<td>0.45</td>
</tr>
<tr class="odd">
<td>E Extraversion</td>
<td style="text-align: left;">108.09</td>
<td>105.89</td>
<td>.505</td>
<td>.614</td>
<td>-0.12</td>
</tr>
<tr class="even">
<td>O Openness</td>
<td style="text-align: left;">105.37</td>
<td>112.39</td>
<td>-2.004*</td>
<td>.046</td>
<td>0.37</td>
</tr>
<tr class="odd">
<td>A Agreeability</td>
<td style="text-align: left;">126.58</td>
<td>132.61</td>
<td>-1.553</td>
<td>.122</td>
<td>0.36</td>
</tr>
<tr class="even">
<td>C Conscientiousness</td>
<td style="text-align: left;">122.29</td>
<td>124.17</td>
<td>-.430</td>
<td>.668</td>
<td>0.09</td>
</tr>
<tr class="odd">
<td>N1 Anxiety</td>
<td style="text-align: left;">16.86</td>
<td>21.06</td>
<td>-3.811**</td>
<td>.000</td>
<td>0.77</td>
</tr>
<tr class="even">
<td>N2 Angry Hostility</td>
<td style="text-align: left;">14.06</td>
<td>12.72</td>
<td>1.215</td>
<td>.225</td>
<td>-0.26</td>
</tr>
<tr class="odd">
<td>N3 Depression</td>
<td style="text-align: left;">16.39</td>
<td>19.06</td>
<td>-2.120*</td>
<td>.035</td>
<td>0.48</td>
</tr>
<tr class="even">
<td>N4 Self-Consciousness</td>
<td style="text-align: left;">16.15</td>
<td>17.67</td>
<td>-1.457</td>
<td>.146</td>
<td>0.32</td>
</tr>
<tr class="odd">
<td>N5 Impulsiveness</td>
<td style="text-align: left;">15.68</td>
<td>15.83</td>
<td>-.143</td>
<td>.886</td>
<td>0.03</td>
</tr>
<tr class="even">
<td>N6 Vulnerability</td>
<td style="text-align: left;">11.45</td>
<td>14.72</td>
<td>-2.709**</td>
<td>.007</td>
<td>0.33</td>
</tr>
<tr class="odd">
<td>E1 Warmth</td>
<td style="text-align: left;">22.27</td>
<td>21.67</td>
<td>.521</td>
<td>.603</td>
<td>-0.14</td>
</tr>
<tr class="even">
<td>E2 Gregariousness</td>
<td style="text-align: left;">17.52</td>
<td>16.33</td>
<td>.934</td>
<td>.351</td>
<td>-0.22</td>
</tr>
<tr class="odd">
<td>E3 Assertiveness</td>
<td style="text-align: left;">13.45</td>
<td>12.72</td>
<td>.739</td>
<td>.460</td>
<td>-0.16</td>
</tr>
<tr class="even">
<td>E4 Activity</td>
<td style="text-align: left;">19.14</td>
<td>20.94</td>
<td>-1.716</td>
<td>.087</td>
<td>0.41</td>
</tr>
<tr class="odd">
<td>E5 Excitement-Seeking</td>
<td style="text-align: left;">16.20</td>
<td>15.11</td>
<td>.879</td>
<td>.380</td>
<td>-0.23</td>
</tr>
<tr class="even">
<td>E6 Positive Emotions</td>
<td style="text-align: left;">19.49</td>
<td>19.11</td>
<td>.333</td>
<td>.739</td>
<td>-0.08</td>
</tr>
<tr class="odd">
<td>O1 Fantasy</td>
<td style="text-align: left;">14.75</td>
<td>15.83</td>
<td>-1.049</td>
<td>.295</td>
<td>0.21</td>
</tr>
<tr class="even">
<td>O2 Aesthetics</td>
<td style="text-align: left;">17.72</td>
<td>19.89</td>
<td>-1.876</td>
<td>.062</td>
<td>0.38</td>
</tr>
<tr class="odd">
<td>O3 Feelings</td>
<td style="text-align: left;">18.88</td>
<td>20.94</td>
<td>-2.276</td>
<td>.024</td>
<td>0.52</td>
</tr>
<tr class="even">
<td>O4 Actions</td>
<td style="text-align: left;">16.55</td>
<td>16.56</td>
<td>-.013</td>
<td>.990</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td>O5 Ideas</td>
<td style="text-align: left;">18.62</td>
<td>19.83</td>
<td>-1.150</td>
<td>.251</td>
<td>0.23</td>
</tr>
<tr class="even">
<td>O6 Values</td>
<td style="text-align: left;">18.86</td>
<td>19.33</td>
<td>-.570</td>
<td>.569</td>
<td>0.13</td>
</tr>
<tr class="odd">
<td>A1 Trust</td>
<td style="text-align: left;">16.56</td>
<td>17.50</td>
<td>-.791</td>
<td>.430</td>
<td>0.18</td>
</tr>
<tr class="even">
<td>A2 Straightforwardness</td>
<td style="text-align: left;">22.48</td>
<td>23.00</td>
<td>-.466</td>
<td>.642</td>
<td>0.10</td>
</tr>
<tr class="odd">
<td>A3 Altruism</td>
<td style="text-align: left;">24.78</td>
<td>26.11</td>
<td>-1.445</td>
<td>.150</td>
<td>0.37</td>
</tr>
<tr class="even">
<td>A4 Compliance</td>
<td style="text-align: left;">18.64</td>
<td>19.39</td>
<td>-.648</td>
<td>.517</td>
<td>0.16</td>
</tr>
<tr class="odd">
<td>A5 Modesty</td>
<td style="text-align: left;">20.45</td>
<td>21.61</td>
<td>-1.236</td>
<td>.217</td>
<td>0.27</td>
</tr>
<tr class="even">
<td>A6 Tender-Mindedness</td>
<td style="text-align: left;">23.67</td>
<td>25.00</td>
<td>-1.548</td>
<td>.123</td>
<td>0.36</td>
</tr>
<tr class="odd">
<td>C1 Competence</td>
<td style="text-align: left;">19.28</td>
<td>18.72</td>
<td>.616</td>
<td>.538</td>
<td>-0.15</td>
</tr>
<tr class="even">
<td>C2 Order</td>
<td style="text-align: left;">20.36</td>
<td>21.50</td>
<td>-1.064</td>
<td>.288</td>
<td>0.23</td>
</tr>
<tr class="odd">
<td>C3 Dutifulness</td>
<td style="text-align: left;">23.04</td>
<td>24.28</td>
<td>-1.320</td>
<td>.188</td>
<td>0.31</td>
</tr>
<tr class="even">
<td>C4 Achievement Striving</td>
<td style="text-align: left;">21.22</td>
<td>20.83</td>
<td>.391</td>
<td>.696</td>
<td>-0.09</td>
</tr>
<tr class="odd">
<td>C5 Self-discipline</td>
<td style="text-align: left;">21.69</td>
<td>23.11</td>
<td>-1.427</td>
<td>.155</td>
<td>0.28</td>
</tr>
<tr class="even">
<td>C6 Deliberation</td>
<td style="text-align: left;">16.70</td>
<td>15.72</td>
<td>.841</td>
<td>.401</td>
<td>-0.13</td>
</tr>
</tbody>
</table>
<p>* <em>p</em> &lt; .05</p>
<p>** <em>p</em> &lt; .01</p>
<p>Five psychological variables are significantly different at the .05 level: women seem more anxious, more vulnerable to stress, have more negative affects, are more depressed and are more open than men. Table 4 also shows that three personality disorders are different for women than to men: they have more features of dependent, avoidant personality and less features of psychopathy.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Table 4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Comparison of the 12 NEO PI-R Personality Disorders variables for 244 male and 18 female Belgian inmates</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 17%">
<col style="width: 8%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">Mean</th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Variable</td>
<td style="text-align: left;">Men</td>
<td>Women</td>
<td><em>t</em></td>
<td><em>p</em></td>
<td>Cohen’s <em>d</em></td>
</tr>
<tr class="even">
<td>Paranoid</td>
<td style="text-align: left;">120.73</td>
<td>115.83</td>
<td>.839</td>
<td>.40</td>
<td>-0.19</td>
</tr>
<tr class="odd">
<td>Schizoid</td>
<td style="text-align: left;">112.49</td>
<td>112.61</td>
<td>-.024</td>
<td>.98</td>
<td>0.01</td>
</tr>
<tr class="even">
<td>Schizotypal</td>
<td style="text-align: left;">100.00</td>
<td>107.94</td>
<td>-1.968</td>
<td>.05</td>
<td>0.46</td>
</tr>
<tr class="odd">
<td>Antisocial</td>
<td style="text-align: left;">226.06</td>
<td>211.44</td>
<td>1.878</td>
<td>.06</td>
<td>-0.47</td>
</tr>
<tr class="even">
<td>Borderline</td>
<td style="text-align: left;">138.52</td>
<td>149.78</td>
<td>-1.997</td>
<td>.05</td>
<td>0.45</td>
</tr>
<tr class="odd">
<td>Histrionic</td>
<td style="text-align: left;">196.22</td>
<td>197.67</td>
<td>-.270</td>
<td>.79</td>
<td>0.06</td>
</tr>
<tr class="even">
<td>Narcissist</td>
<td style="text-align: left;">164.37</td>
<td>152.22</td>
<td>1.976</td>
<td>.05</td>
<td>-0.49</td>
</tr>
<tr class="odd">
<td>Avoidant</td>
<td style="text-align: left;">158.02</td>
<td>171.39</td>
<td>-2.521*</td>
<td>.01</td>
<td>0.53</td>
</tr>
<tr class="even">
<td>Dependent</td>
<td style="text-align: left;">118.66</td>
<td>131.22</td>
<td>-3.345**</td>
<td>.001</td>
<td>0.67</td>
</tr>
<tr class="odd">
<td>Dependent-Revised</td>
<td style="text-align: left;">83.89</td>
<td>94.67</td>
<td>-2.267*</td>
<td>.02</td>
<td>0.51</td>
</tr>
<tr class="even">
<td>Obsessive-compulsive</td>
<td style="text-align: left;">226.36</td>
<td>229.61</td>
<td>-.571</td>
<td>.57</td>
<td>0.12</td>
</tr>
<tr class="odd">
<td>Psychopathy</td>
<td style="text-align: left;">271.15</td>
<td>248.11</td>
<td>3.200**</td>
<td>.002</td>
<td>-0.74</td>
</tr>
</tbody>
</table>
<p>* <em>p</em> &lt; .05</p>
<p>** <em>p</em> &lt; .01</p>
<p>On the legal status, five psychological variables distinguish the sentenced inmates from the forensic patients. Forensic patients score higher in Neuroticism, <em>t</em>(260) = 2.62, <em>p</em> = .009, <em>d</em> = .62, self-consciousness, <em>t</em>(260) = 2.71, <em>p</em> = .007, <em>d</em> = .66, vulnerability, <em>t</em>(260) = 2.36, <em>p</em> =. 019, <em>d</em> =.32 and lower scores in Conscience, <em>t</em>(260) = - 2.41 <em>p</em> = .017, <em>d</em> = -.58, self-discipline, <em>t</em>(260) = - 3.14, <em>p</em> = .002, <em>d</em> = -.70. Four personality disorders are also different in the two groups. Forensic patients have higher scores in schizotypal personality, <em>t</em>(260) = -2.85, <em>p</em> =. 005, <em>d</em> = .74, borderline personality, <em>t</em>(260) = 2.16, <em>p</em> = .032, <em>d</em> = .55, revised dependent personality, <em>t</em>(260) = 2.89, <em>p</em> = .004, <em>d</em> = .73 and a lower score in obsessive compulsive personality disorder, <em>t</em>(260) = - 2.41, <em>p</em> = .017, <em>d</em> = -.54.</p>
<p>The age of inmates influenced the scores on eight of the twelve personality disorders: paranoid personality (<em>r</em> = -.14, <em>p</em> = .02), antisocial personality (<em>r</em> = -.21, <em>p</em> = .001), psychopathy (<em>r</em> = -.19, <em>p</em> = .002), borderline personality (<em>r</em> = -.22, <em>p</em> = .001), histrionic personality (<em>r</em> = -.19, <em>p</em> = .002), narcissistic personality (<em>r</em> = -.21, <em>p</em> =. 001), the revised dependent personality (<em>r</em> = -.19, <em>p</em> = .002) and obsessive compulsive personality disorder (<em>r</em> = .23, <em>p</em> &lt; .001).</p>
<p>Table 5 shows that the twelve variables of the NEO PI-R personality disorders can be resolved to just three factors that explain respectively 41 %, 33 % and 17 % (in total 92 %) of the variance.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Table 5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Exploratory factor analysis of the 12 NEO PI-R Personality Disorder variables for 262 Belgian inmates</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 41%">
<col style="width: 13%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">Factors (explained variance)</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Variable</td>
<td style="text-align: left;">1 (41%)</td>
<td>2 (33%)</td>
<td>3 (17%)</td>
</tr>
<tr class="even">
<td>Paranoid</td>
<td style="text-align: left;">.434</td>
<td><strong>.743</strong></td>
<td>.447</td>
</tr>
<tr class="odd">
<td>Schizoid</td>
<td style="text-align: left;">-.477</td>
<td><strong>.668</strong></td>
<td>.463</td>
</tr>
<tr class="even">
<td>Schizotypal</td>
<td style="text-align: left;">-.152</td>
<td><strong>.906</strong></td>
<td>.068</td>
</tr>
<tr class="odd">
<td>Antisocial</td>
<td style="text-align: left;"><strong>.951</strong></td>
<td>.271</td>
<td>.045</td>
</tr>
<tr class="even">
<td>Psychopathy</td>
<td style="text-align: left;"><strong>.898</strong></td>
<td>.086</td>
<td>.367</td>
</tr>
<tr class="odd">
<td>Borderline</td>
<td style="text-align: left;">.428</td>
<td><strong>.689</strong></td>
<td>-.476</td>
</tr>
<tr class="even">
<td>Histrionic</td>
<td style="text-align: left;"><strong>.684</strong></td>
<td>-.312</td>
<td><strong>-.619</strong></td>
</tr>
<tr class="odd">
<td>Narcissist</td>
<td style="text-align: left;"><strong>.832</strong></td>
<td>.378</td>
<td>.341</td>
</tr>
<tr class="even">
<td>Avoidant</td>
<td style="text-align: left;"><strong>-.682</strong></td>
<td><strong>.700</strong></td>
<td>.063</td>
</tr>
<tr class="odd">
<td>Dependent</td>
<td style="text-align: left;"><strong>-.685</strong></td>
<td>.407</td>
<td><strong>-.538</strong></td>
</tr>
<tr class="even">
<td>Dependent-Revised</td>
<td style="text-align: left;">-.029</td>
<td><strong>.815</strong></td>
<td><strong>-.522</strong></td>
</tr>
<tr class="odd">
<td>Obsessive-compulsive</td>
<td style="text-align: left;"><strong>-.673</strong></td>
<td>-.282</td>
<td>.490</td>
</tr>
</tbody>
</table>
<p>Loadings &gt; .5 are highlighted in the table. The first factor clearly shows that the variables of cluster B (dramatic, emotional, or erratic disorders) to which we added psychopathy and C (anxious and fearful disorders) are opposite. High scores on this first factor refer to the tendency to externalize conflicts, to be self-confident and assertive; on the other hand, low scores refer to the tendency to internalize conflicts, to be dependent on others and to be cautious. The second factor consists of variables in the cluster A (eccentric disorders) plus borderline, avoidant personality and the revised dependent personality. The two assessment methods of the dependent personality proposed by Miller et al.&nbsp;(2008) raise a problem because they do not appear to refer to the same psychological factor. Therefore, these two variables create a third factor in the analysis that could be seen as a bias in the assessment of the dependant personality. Therefore, we would be tempted to retain only the first two factors. The first factor of externalizing is correlated with age (<em>r</em> = -. 15, <em>p</em> = .02) and gender (<em>R</em> = .17, <em>p</em> = .0045 of the inmates. Men have higher scores than women for externalizing. Table 6 proposes a factor structure with varimax variation without the revised dependent personality variable.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Table 6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Factor analysis with varimax rotation of 11 NEO PI-R Personality Disorder variables for 262 Belgian inmates</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 40%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;">Factors (explained variance)</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Variable</td>
<td style="text-align: left;">1 (41%)</td>
<td>2 (31%)</td>
<td>3 (17%)</td>
</tr>
<tr class="even">
<td>Paranoid</td>
<td style="text-align: left;"><strong>.717</strong></td>
<td><strong>.604</strong></td>
<td>.244</td>
</tr>
<tr class="odd">
<td>Schizoid</td>
<td style="text-align: left;">-.005</td>
<td><strong>.917</strong></td>
<td>-.220</td>
</tr>
<tr class="even">
<td>Schizotypal</td>
<td style="text-align: left;">.044</td>
<td><strong>.862</strong></td>
<td>.347</td>
</tr>
<tr class="odd">
<td>Antisocial</td>
<td style="text-align: left;"><strong>.816</strong></td>
<td>-.140</td>
<td><strong>.543</strong></td>
</tr>
<tr class="even">
<td>Psychopathy</td>
<td style="text-align: left;"><strong>.937</strong></td>
<td>-.168</td>
<td>.199</td>
</tr>
<tr class="odd">
<td>Borderline</td>
<td style="text-align: left;">.154</td>
<td>.257</td>
<td><strong>.885</strong></td>
</tr>
<tr class="even">
<td>Histrionic</td>
<td style="text-align: left;">.120</td>
<td><strong>-.744</strong></td>
<td><strong>.620</strong></td>
</tr>
<tr class="odd">
<td>Narcissist</td>
<td style="text-align: left;"><strong>.918</strong></td>
<td>.087</td>
<td>.320</td>
</tr>
<tr class="even">
<td>Avoidant</td>
<td style="text-align: left;">-.401</td>
<td><strong>.896</strong></td>
<td>-.009</td>
</tr>
<tr class="odd">
<td>Dependent</td>
<td style="text-align: left;"><strong>-.803</strong></td>
<td>.448</td>
<td>.277</td>
</tr>
<tr class="even">
<td>Obsessive-compulsive</td>
<td style="text-align: left;">-.269</td>
<td>.190</td>
<td><strong>-.826</strong></td>
</tr>
</tbody>
</table>
<p>Three other factors emerge and also account for 92 % of the variance. The first factor refers to a psychopathic antisociality, tainted by suspicion. The second factor refers to alienation and feelings of strangeness. The third factor refers to an unstable, more emotional, more disorganized antisociality.</p>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>The results of this study show that some personality traits of inmates differ significantly from the normative sample. Concerning the five major domains of personality, the inmates are as emotionally stable and as extraverted as others. However, they seem less open, more agreeable and more conscientious. The study of the NEO PI-R facets refines these findings. Inmates are much more practical and conservative. They have strong values that they advocate, and do not wish to change them. They perceive themselves as altruistic and wish to help people in need. However, they give less importance to feelings, preferring to put them aside. They bring important ambitions that they want to realize in a disciplined and orderly manner. Some personality disorders are also significantly different: antisocial, psychopathic, histrionic, narcissistic score lower and obsessive, schizoid score higher than the normative population. It should be noted that the mean of these effect sizes is small (Cohen, 1992).</p>
<p>The weakness of these effect sizes had already been noticed by Samuels, Bienvenu, Cullen, Costa, Eaten and Nestadt (2004) whose results differ from ours. Indeed, by comparing the variables of the NEO PI-R of 79 persons who had been arrested earlier with 532 people who had never been arrested, they note that the first group had higher scores in Neuroticism, angry hostility, impulsiveness and excitement-seeking and lower scores in Agreeableness, trust, straightforwardness, compliance, modesty, dutifulness and deliberation. These results may even look opposite to ours. It is possible that our sample of Belgian inmates does not share the same psychological characteristics as the sample of people arrested at least once in their lives in the American city of Baltimore (Samuels et al., 2004).</p>
<p>The comparison between male and female inmates shows some differences: women seem more anxious and dependent. This result is interesting but clearly deserves confirmation with a more specific study. As the sample of women in this study is small (18) and raises issues of generalization, these findings should therefore be taken with caution. The same remark applies to the 14 forensic patients. Although significant differences were found with sentenced inmates, they should be confirmed by another more specific study.</p>
<p>The factor analysis that was conducted highlights two major factors. The first refers to the concepts of externalization and internalization that appear in several factor approaches of psychopathology (Sheets &amp; Craighead, 2007; Røysamb, Kendler, Tambs, Ørstavik, Neale &amp; Aggen, 2011; Kendler, Aggen, Knudsen, Røysamb, Neal, Reichborn-Kjennerud, 2011). That is, two opposite trends appear in the analysis: a) the self-confidence and the externalization of conflicts into the environment and b) scruples, dependence on others, and inner fears.</p>
<p>The age tends to exacerbate the trend towards internalization.</p>
<p>The second factor describing our data refers to certain thoughts and some strange, incoherent or unstable behaviour.</p>
<p>The second factor analysis with varimax variation is interesting from the criminological point of view because it reveals three distinct psychological types: (a) a resolute psychopathic tendency, (b) a tendency towards alienation and to strange experiences, and (c) a disorganized emotional antisocial tendency. Each of the three disorders of the cluster C (avoidant, dependent and obsessive-compulsive) seems to define a distinct psychological type. Indeed each one loads strongly each factor.</p>
<p>The prevalence of obsessive-compulsive features within this population can be surprising. Indeed, it has not appeared in previous studies evaluating personality disorders using hetero-reported and categorical assessment. For example, among the 80 inmates from a Parisian prison assessed by the Structured Clinical Interview for DSM Disorders (SCID-II) and the Mini-International Neuropsychiatric Interview (M.I.N.I.), 10 % meet the criteria of the obsessive-compulsive personality compared to 53.8 % for antisocial personality (Nioche, Pham, Ducro, Beaurepaire, Chudzik, Courtois &amp; Réveillère, 2010). The meta-analysis of Fazel and Danesh (2002) do not evoke the obsessive-compulsive personality disorder. Beyond this specific disorder, the high rates of prison personality disorders do not appear in our study. On the contrary, it shows much less pathological and therefore less worrisome results in strictly psychiatric terms that some studies have reported (Vandervelde, Soyez, Vander Beken, De Smet, Boer &amp; Broekart, 2011). How can we explain the results if the present study? First assumption: the Five-Factor Model variables do not assess the same realities that axis II of the DSM-IV TR personality disorders. However, the meta-analysis of Samuel and Widiger (2008) supports the idea that the Five-Factor Model actually does evaluate these personality disorders in a satisfactory manner. In addition, Bulten, Nijman and van der Staak (2009) argue that the NEO PI-R variables do predict the diagnosis of antisocial personality disorder.</p>
<p>Second assumption: inmates minimize dysfunctional personality characteristics in a self-reported context. In fact, Sung-Cheol (2007) has highlighted that the stake of the assessment (a professional recruitment) influences the scores to the NEO PI-R: Neuroticism (<em>d</em> = -1.2), Openness (<em>d</em> = -.49) Extraversion (<em>d</em> = .79), Agreeability (<em>d</em> = .63), Consciousness (<em>d</em> = 1.36) and lowered all personality disorders (mean of <em>d</em> = - .8), and increased obsessive-compulsive personality (<em>d</em> = .96). It is likely that the context of the assessment has had an impact on these scores. However, the differences to the norms we have found are well below those in a recruitment position. We also did not find differences for neuroticism and extraversion. Furthermore, this risk of bias made us include three validity scales proposed by Schinka and Kremer (1997). These scales did not reveal an effect of social desirability in the responses of inmates. However they showed a tendency to respond more inconsistently, which could be explained by the lesser degree of education of inmates. Indeed, being less familiar with the ability to read and writing, it is likely that some inmates have lesser understanding of the more complex items of the test. The context therefore does not fully explain our results.</p>
<p>Third assumption: our population suffers from a systematic bias, which would affect self representation (Petot &amp; Djuric Jocic, 2005). This assumption questions the validity of self-reported psychological assessments. Some argue that social desirability influences personality questionnaires so that the results would be invalid. Rolland and de Fruyt (2009) argue that social desirability is not so simple and does not invalidate the obtained psychological profile. Indeed, the trend to change some answers in a psychological test is itself related to the personality of the respondent. It is difficult (if not impossible) to distinguish conscious intentions of those that are not. Some may claim a psychological facet (e.g.&nbsp;altruism) based on a personal value that they endorse: “it is important to me to care for others”. This value could be seen as a stable and coherent cognitive pattern. One single act (e.g.&nbsp;an offense) does not imply a repetitive behaviour. Others organize drug dealing without paying attention to long-term negative consequences of their actions. Some are part of a criminal organization that gives them orders they follow by conformism or for social valorisation.</p>
<p>According to us, someone claiming a personality facet based on a personal conviction may be considered as expressing it.</p>
<p>The establishment of a trust relationship between the clinician and the participant allows the reduction of the social desirability effect. Let us recall that the protocols of NEO PI-R were obtained in a global clinical assessment for inmates incarcerated for several months and eligible for early release. This issue of social desirability (or manipulation) is often discussed during clinical interviews in one way or another. Therefore, the prison psychologist attempts as possible to ensure a minimum trust with the inmate before psychological testing. Concerning the present study, the average personality profile obtained contradicts a prototypical image of the inmate that could be characterised by impulsivity, egocentrism, violence, disrespect towards others, etc. These features could be seen as a caricature of the offender assumed dangerous. The psychological profile resulting from the present study is consistent with clinical interviews in prison. Most of the inmates report a major loyalty to their relatives (mainly their immediate family) and their values (e.g.&nbsp;religious values). They insist on the sacrifices they would be willing to do for the people they love. Often, an altruistic intent is hiding behind the criminal acts (for example, robbing a bank to ensure financial support to his family). The obsessive-compulsive dimension is not so surprising to the prison clinician: inmates must obey a series of specific rules in the prison and follow procedures to obtain a conditional release. They express their ambitions (e.g.&nbsp;to find a satisfactory job) and their intention to succeed. Finally, even if we believe that the Belgian inmates had manipulated their responses to the NEO PI-R, we should note that they would have done this whilst taking into account socially valued ideals, which means that they take them into consideration.</p>
<p>The common point of this study’s subjects is that they committed at least one offence and have therefore broken the law and morality. Is morality a personality trait? The Five-Factor Model seems to respond negatively to this question because morality does not appear explicitly in factor analyses. This study indirectly questions the relationship between crime and personality and therefore, between antisocial behaviour and personality. Although there are antisocial behaviours and ways of life, is there an antisocial personality? Studies using hetero-reported evaluations seem to confirm the prevalence of antisocial personality diagnosis in prisons. However, is this diagnosis not influenced by the situation of assessment? Don’t the psychiatrists or psychologists pay more attention to those diagnostic criteria, influenced by a halo effect?</p>
<p>The tautological definition of antisocial personality must be underlined: an antisocial person behaves in an antisocial manner. This definition is problematic because it is likely to induce non-conscious cognitive biases among the assessor and lead them to assign to personality what is in fact situational behaviour. Called the <em>fundamental attribution error</em> (Ross, 1977) this error is very common and insidious. We are not saying that this cognitive bias completely covers the antisocial personality diagnosis but assessors should be mindful of the role it plays.</p>
<p>Keeping the antisocial disorder in the different versions of the Diagnostic and Statistical Manual of Mental Disorders (DSM) induces the idea that this is a psychiatric problem (and hence a medical issue). Six of the seven diagnostic criteria for antisocial personality disorder in the DSM-IV TR directly refer to legal, safety and moral concepts. Deriving personality traits from <em>irresponsible</em> or immoral behaviours is not so obvious.</p>
<p>From a historical point of view, such a diagnosis evokes the homicidal monomania (by Georget in 1825) or the born criminal (by Lombroso in 1876), which showed little regard for sociological variables involved in understanding delinquency. Much sociological work has been made to highlight the weight of social factors influencing delinquency. For example, Becker (1963) insisted on the <em>labeling effect</em>, which sometimes leads people to commit crimes because there are seen as offenders by the others. Labels applied to individuals influence their behaviour. Psychiatric research about criminal behaviours often omits to consider social variables, reducing it to a medical issue.</p>
<p>According to us, the link between personality, self-representation and close social environment still deserves further research. Criminal behaviour is a particular relevant field for this matter.</p>
<p>The results of this study suggest that the personality of inmates is not fundamentally different from the rest of the population. This observation seems important because it reminds us that understanding delinquency involves other disciplines such as sociology and moral philosophy. Criminology is a complex discipline that requires a multidisciplinary approach. The reason why behaviour is considered legal or illegal is based on the law. Legal systems do not rely on the scientific paradigm. Some laws are also created in a specific emotional context (e.g.&nbsp;following a media event of for purely political reasons).</p>
<p>Delinquency implies, therefore, social elements over which individuals have no control. However, there are complex links between sociological variables and the personality of individuals who live in society. These links are studied by social psychology. We believe that the tests used for individual personality (such as personality inventories) do not lose their relevance; on the contrary, links between hetero- and self-reported assessments must still be clarified because the diagnostic process has an impact on the treatment and strategic interventions in the prison. Crime is a social problem that we would be tempted to medicalize. Though some inmates do have acute psychiatric problems, they are not representative of the prison population. Most of inmates committed offences in a complex situation influenced by personality, context and social variables. The results of the present study are not going in the direction of pathology. Although prisons have to deal with people showing mental disorders requiring care, this is not the case for the majority of the inmates.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>American Psychiatric Association (1980). <em>DSM-III: Diagnostic and statistical manual of mental disorders.</em> New York. Masson.</p>
<p>American Psychiatric Association (1994). <em>DSM-IV: Diagnostic and statistical manual of mental disorders.</em> New York. Masson.</p>
<p>Becker H.S. (1963). <em>Outsiders: Studies in the Sociology of Deviance</em>. New York: The Free Press.</p>
<p>Bulten E., Nijman H. &amp; van der Staak C. (2007). Measuring criminal thinking styles: the construct validity and utility of the PICTS in aDutch prison sample. <em>Legal and Criminological Psychology, 14</em>, 35-49.</p>
<p>Cohen J. (1992). A Power Primer. <em>Psychological Bulletin, 112 (1)</em>, 155-159.</p>
<p>Costa P. &amp; McCrae R. (1998). <em>NEO PI-R, Inventaire de Personnalité-Révisé</em>, french adaptation by J-P Rolland. Editions du Centre de Psychologie Appliquée. Paris.</p>
<p>Costa P.T. &amp; Widiger T.A. (2002). <em>Personality disorders and the five-factor model of personality.</em> Washington DC: APA.</p>
<p>Edens J.F. &amp; Ruiz M.A.&nbsp;(2008). Identification of mental disorders in an in-patient prison psychiatric unit: examining the criterion-related validity of the Personality Assessment Inventory. <em>Psychological Services, 5(2),</em> 108-1117.</p>
<p>Fazel S. &amp; Danesh J. (2002). Serious mental disorder in 23 000 prisoners: a systematic review of 62 surveys. <em>The Lancet, 359</em>, February, 16, 2002.</p>
<p>Georget E. (1825). Examen médical des procès criminels des nommés Léger, Feldtmann, Lecouffe, Jean-Pierre et Papavoine, dans lesquels l’aliénation mentale a été alléguée comme moyen de défense, suivi de quelques considérations médico-légales sur la liberté morale. [Medical examination of criminal trials of Léger, Feldtmann, Lecouffe, Jean-Pierre and Papavoine, in which insanity was alleged as a defence, followed by some considerations on forensic moral freedom]. Retrieved March 19, 2012, from http://gallica.bnf.fr/ark:/12148/bpt6k770154/f1</p>
<p>Kendler K.S, Aggen S.H., Knudsen G.P., Røysamb E., Neal M.C., Reichborn-Kjennerud T. (2011). The structure of genetic and environmental risk factors for syndromal and subsyndromal common DSM-IV axis I and all axis II disorders. <em>American Journal of Psychiatry, 168</em>, 29-39.</p>
<p>Lafortune D. (2010). Prevalence and screening of mental disorders in short-term correctional facilities. <em>International Journal of Law and Psychiatry, 33</em>, 94-100.</p>
<p>Lombroso C. (1876). <em>L’uomo delinquente.</em> Milan: Hoepli.</p>
<p>Lynam D.R. &amp; Widiger T.A. (2001). Using the five-factor model to represent the DSM-IV personality disorders: an expert consensus approach. <em>Journal of Abnormal Psychology, 110</em>, 401-412.</p>
<p>Miller J.D, Lynam D.R., Pham-Scottez A., De Clercq B., Roland J.P., De Fruyt F. (2008). Utilisation du modèle de personnalité à cinq facteurs (FFM) dans l’évaluation des troubles de la personnalité du DSM-IV. [Using the Five Factor Model in the assessment of DSM-IV personality disorders]. <em>Annales Médico-Psychologiques, 166 (6)</em>, 418-426.</p>
<p>Miller J.D., Lynam D.R., Rolland J.P., De Fruyt F., Reynolds S.K., Pham-Scottez A., Baker S. R., Bagby R.M. (2008). Scoring the DSM-IV Personality Disorders using the Five-Factor Model: Development and Validation of Normative Scores for North American, French and Dutch-Flemish Samples. <em>Journal of Personality Disorders, 22(5),</em> 433-450.</p>
<p>Miller J.D., Lynam D.R., Widiger T.A. &amp; Leukefeld C. (2001). Personality disorders as extreme variants of common personality dimensions: Can the five-factor model adequately represent psychopathy ? <em>Journal of Personality, 69 (2)</em>, 253-276.</p>
<p>Motiuk L.L. &amp; Porporino F.J. (1991). La prévalence, la nature et la gravité des problèmes de santé mentale chez les détenus de sexe masculin sous responsabilité fédérale dans les pénitenciers au Canada. [Prevalence, nature and severity of mental health problems among male inmates in federal penitentiaries in Canada].Retrieved February 15, 2012, from <a href="http://www.csc-scc.gc.ca/text/rsrch/reports/r24/r24e_f.pdf" class="uri">http://www.csc-scc.gc.ca/text/rsrch/reports/r24/r24e_f.pdf</a></p>
<p>Nioche A., Pham T., Ducro C., de Beaurepaire C., Chudzik, Courtois R. &amp; Réveillère C. (2010). Psychopathie et troubles de la personnalité associés&nbsp;: recherche d’un effet particulier au trouble borderline [Psychopathy and associated personality disorders: Searching for a particular effect of the borderline personality disorder]. <em>L’Encéphale, 36</em>, 253-259.</p>
<p>Petot J.M. &amp; Djuric Jocic D. (2005). Discrepancies between the Rorschach inkblot method and self-report measures of personality: methodological and theorical reflections. <em>Rorschachiana, 27</em>, 101-116.</p>
<p>Piselli M., Elisei S., Murgia N., Quartesan R. &amp; Abram K.M. (2009). Co-occuring psychiatric and substance use disorders among male detainees in Italy. <em>International Journal of Law and Psychiatry, 32</em>, 101-107.</p>
<p>Pham T. &amp; Saloppé T. (2010). PCL-R psychopathy and its relation to DSM axes I and II disorders in a sample of male forensic patients in a Belgian security hospital. <em>International Journal of Forensic Mental Health</em>.</p>
<p>Rolland J.P &amp; de Fruyt F. (2009). PfPI, inventaire de personnalité au travail. Manuel. [PfPI, personality inventory at work. Handbook]. ECPA. Éditions du Centre de psychologie appliquée.</p>
<p>Ross L. (1977). The intuitive psychologist and his shortcomings: Distortions in the attribution process. In L. Berkowitz (dir.), <em>Advances in experimental social psychology</em> (vol.&nbsp;10, 173–220), Academic Press, New York.</p>
<p>Røysamb E., Kendler K.S., Tambs K., Ørstavik R.E., Neale M.C. &amp; Aggen S.H. (2011). The joint structure of DSM-IV axis I and axis II disorders. <em>Journal of Abnormal Psychology, 120 (1)</em>, 198-209.</p>
<p>Samuels J., Bienvenu O., Cullen B., Costa P., Eaten W. &amp; Nestadt G. (2004). Personality dimensions and criminal arrest. <em>Comprehensive Psychiatry, 45 (4)</em>, 275-280.</p>
<p>Samuel D.B. &amp; Widiger T.A. (2008). A meta-analytic review of the relationships between the five-factor model and DSM-IV-TR personality disorders: a facet level analysis. <em>Clinical Psychology Review, 28,</em> 1326-1342.</p>
<p>Schinka J. &amp; Kremer T. (1997). Research validity scales for the NEO PI–R: Development and initial validation. <em>Journal of Personality Assessment, 68</em>, 127–138.</p>
<p>Sheets E. &amp; Craighead W.E. (2007). Towards an empirically based classification of personality pathology. <em>Clinical Psychology: Science and Practice, 14(2),</em> 77-93.</p>
<p>Sung-Cheol J. (2007). <em>La personnalité dans le processus d’évaluation : stabilité structurale de l’inventaire NEO-PI-R et prédiction des comportements au travail.</em> [Personality and assessment process: structural stability of the NEO PI-R and predicting behaviours at work]. Doctoral thesis. Université de Paris X Nanterre.</p>
<p>Vandervelde S., Soyez V., Vander Beken T., De Smet S., Boers A. &amp; Broekart E. (2011). Mentally ill offenders in prison: the Belgian case. <em>International Journal of Law and Psychiatry, 34</em>, 71-78.</p>
<p>Westen D. &amp; Arkowitz-Westen L. (1998). Limitations of axis II in diagnosing personality pathology in clinical practice. <em>American Journal of Psychiatry, 155</em>, 1767-71.</p>
<p>Widiger T.A. &amp; Samuel D.B. (2005). Diagnostic categories or dimensions ? A question for the Diagnostic and Statistical Manuel of Mental Disorders – 5th Edition. <em>Journal of Abnormal Psychology, 114</em>, 494-504.</p>


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" id="quarto-citation"><h2 class="anchored quarto-appendix-heading">Citation</h2><div><div class="quarto-appendix-secondary-label">BibTeX citation:</div><pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@online{thiry2012,
  author = {Thiry, Benjamin},
  title = {An Assessment of Personality Disorders with the Five-Factor
    Model among Belgian Inmates},
  date = {2012-07-01},
  url = {https://benjaminthiry.netlify.app/posts/2021-08-03-personality-inmates/},
  doi = {https://doi.org/10.1016/j.ijlp.2012.04.010},
  langid = {eng}
}
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre><div class="quarto-appendix-secondary-label">For attribution, please cite this work as:</div><div id="ref-thiry2012" class="csl-entry quarto-appendix-citeas" role="listitem">
Thiry, B. (2012, July 1). An Assessment of Personality Disorders with
the Five-Factor Model among Belgian Inmates. https://doi.org/<a href="https://doi.org/10.1016/j.ijlp.2012.04.010">https://doi.org/10.1016/j.ijlp.2012.04.010</a>
</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/benjaminthiry\.netlify\.app");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="ouriagan/blogcomments" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->




</body></html>