---
title: "Assessing the Therapeutic Alliance with the Five-Factor Model and the NEO PI: an Expert-Based Approach"
description: "In psychotherapy, therapeutic alliance is an integrative factor influencing the effectiveness of treatment. This alliance depends on the bond between therapist and patient. Objectives: this study investigates patient's psychological variables likely to facilitate or hamper a psychotherapeutic process. Methods: we asked 38 clinicians to assess the importance of each variable of the Five-Factor Model supposed to facilitate or hamper therapeutic alliance. Results: results indicate that high Openness, Agreeableness and Conscientiousness are perceived as favourable to therapeutic alliance. Beyond these results, we preferably focus on facets of the NEO PI to assess their relevance for the facilitation or hindrance of therapeutic alliance. According clinicians, four facets are supposed to affect positively therapeutic alliance: A2 (Straightforwardness), O3 (Feelings), C5 (Self-Discipline) and O5 (Ideas). Three facets were supposed to have a negative effect on therapeutic alliance: low scores for A5 (Modesty), A2 (Straightforwardness) and A1 (Trust). Conclusion: on this basis, we propose three experimental scores investigating the proneness to access therapy for the NEO PI. "
author:
  - name: Benjamin Thiry
    orcid_id: 0000-0001-5864-8369
    website: https://benjaminthiry.netlify.app/
date: "11-01-2020"
categories: [analyses statistiques]
published-title: "Annales Médico-psychologiques, revue psychiatrique"
doi: "https://doi.org/10.1016/j.amp.2020.01.007"
published-url: "https://www.sciencedirect.com/science/article/abs/pii/S000344872030007X"
lang: eng
---

# Introduction

In private psychotherapy, in psychiatric treatment, in pedagogic orientation, in personality assessment and even in somatic care, there is no suitable intervention without a well-established relationship between a patient and a professional. Consequently, this relationship is a major concern of scientific interest. Of course, this relationship depends on some psychological characteristics of the *patient* and the *professional*. However, it is more than the sum of both. For Wampold \[31\], "initial meeting of patient and therapist is essentially the meeting of two strangers, with the patient making a determination of whether the therapist is trustworthy, has the necessary expertise, and will take the time and effort to understand both the problem and the context in which the patient and the problem are situated". Many studies and meta-analyses have addressed this crucial issue. The aim of this paper is to recall the importance of this therapeutic alliance, focusing on psychological characteristics of patients that could influence this alliance and proposing new NEO PI indexes that could assess these characteristics. These indexes would help professionals to assess readiness of the patient to initiate a psychotherapy. For example, in forensic settings, some offenders are obliged to enter a psychotherapeutic process which often leads to prematurely terminate the therapy. Anticipating some psychological obstacles to therapy could help professionals to adapt a more suitable treatment.

# Therapeutic alliance as a key significant factor in therapy outcome

In the psychotherapeutic field, despite theoretical benchmarks, methods and ethical principles have changed, the bond between patient and therapist remains a main issue. It has many names but the most common ones are the *therapeutic alliance*, the *working* *alliance* or even the *transference* (from a psychoanalytic perspective following Freud \[9\]). For Rogers \[26\], quality of the therapeutic alliance is seen as an essential element in the person-centred therapy. It is a necessary condition for the humanist helping relationship. In psychotherapy, but also in any clinical relationship, many studies have focused on the characteristics of the therapeutic alliance. Indeed, beyond the theoretical frame, therapeutic alliance is considered to be a *common factor* to all psychotherapies. For Goldfried, Castonguay and Saffron \[10\], focus should primarily be targeted at processes that are more robust and more generic than specific techniques. According to Bordin \[3\], therapeutic alliance is composed of three components: (a) the bond between therapist and patient, (b) an agreement about the goals of therapy, and (c) an agreement about the tasks of therapy. Horvath and colleagues \[13, 14 \] used meta-analytic techniques to summarize quantitative research that links alliance and outcome. On the basis of 24 studies included in the review, they found an average effect size that linked quality of alliance to therapy of *r* = .26. A subsequent meta-analysis \[18\] reported an average correlation of .22 between alliance and outcome across 68 studies. Later studies confirmed this effect size as stated by Horvath, Del Re, Fluckiger and Symonds \[12\]: "The overall aggregate relation between the alliance and treatment outcome (adjusted for sample size and non-independence of outcome measures) was *r* = .275 (*k* = 190); the 95% confidence interval for this value was .25--.30. The statistical probability associated with the aggregated relation between alliance and outcome is *p* \< .0001." Fluckiger, Del Re, Wampold and Horvath \[8\] presented a meta-analysis of 295 independent studies and confirmed that the overall alliance--outcome association for face-to-face psychotherapy was *r* = .278. This kind of results led Laska, Gurman and Wampold \[17\] to suggest that evidence-based practices within psychotherapy should go beyond specific factors of each psychotherapeutic method and incorporate the scientific research relating to relationship variables considered as a *common factor*. All these studies suggest that therapeutic alliance, as an integrative factor, is a central issue in the effectiveness of psychotherapies \[2\].

# Therapeutic alliance and patient personality

Therapeutic alliance does not exist by itself. It depends, of course, on involved people. The personalities of patients and therapists influence the link between them.

> It appears that both intrapersonal and interpersonal client variables have similar and significant effects on the alliance. The average correlation coefficients (*r~s~*, weighted by sample size) between these variables and alliance were .30 and .32, respectively. Thus, clients who have difficulty maintaining social relationships \[22\] or have poor family relationships \[15\] are less likely to develop strong alliances \[13\].

Some client personality characteristics predict therapeutic alliance in general psychotherapy. Wallner-Samstag, Muran, Zindel, Segal and Schuman \[30\] found that patients who were more submissive, isolated and friendly were more likely to develop strong alliances than hostile, aggressive and dominant patients. Similarly, Puschner, Bauer, Horowitz and Kordy \[25\] found that overly hostile patients had poor initial alliances compared to more friendly patients \[27\]. Results of Diener and Monroe \[6 \] indicated that greater attachment security was associated with stronger therapeutic alliances, whereas greater attachment insecurity was associated with weaker therapeutic alliances, with an overall weighted effect size of *r* = .17. Relating to his own experience, Miller \[21\] suggested that Neuroticism (N) influences the intensity and duration of the patient's distress, Extraversion (E) influences the patient's enthusiasm for treatment, Openness (O) influences the patient's reactions to the therapist's interventions, Agreeableness (A) influences the patient's reaction to the person of the therapist, and Conscientiousness (C) influences the patient's willingness to do the work of psychotherapy. Ogrodniczuk, Piper, Joyce, McCallum and Rosie \[24\] assessed 107 psychiatric outpatients with the NEO-Five Factor Inventory \[5\] who completed a short-term group therapy and found higher extraversion, conscientiousness and openness and lower neuroticism were each associated with more favourable outcome. Samuel, Bucher and Suzuki (2018) assessed 52 patients with the Five-Factor Model Rating Form \[23\] who were treated by doctoral student clinicians in a cognitive-behavioral therapy. They found that therapist-rated conscientiousness at intake was positively related to client's early engagement in therapy and that openness to experience after the fourth session was predictive of long-term therapy outcomes. Bucher, Suzuki, and Samuel \[4 \] performed a meta-analytic review of 99 studies (*N* = 107 206) assessing the link between personality traits and therapeutic outcome. They stated that "generally, lower levels of neuroticism and higher levels of extraversion, agreeableness, conscientiousness, and openness were associated with more favorable outcomes. More specifically, agreeableness had positive associations with therapeutic alliance \[...\]". These last studies highlight the role of patient personality in the outcome of psychotherapy but only focused on the five broad personality domains without taking into account the more specific facets. Though these facets do share common variance between each other, they cannot be considered as identical. They do bring more accurate information about personality.

# Can we create a *psychotherapeutic alliance readiness index* based on FFM variables?

Since the 1990s, the Five Factor-Model of personality (FFM) \[5\] has become a reference model to assess personality in several contexts of evaluation \[27\]. A third English version of the NEO PI is available since 2010 (and since 2016 in French). A freely available alternative exists, such as questionnaires from the International Personality Item Pool \[11\] that approximates the same scores on the NEO PI-R. Table 1 represents the five domains and the thirty facets of the Five-Factor-Model.

| Table 1. Domains and facets of the Five-Factor Model (referring to Costa & McCrae, 1992) |   |
|:---------------------------------------|--------------------------------|
| NEO PI Domain | NEO PI Facet |
| N Neuroticism | (N1) Anxiety |
|  | (N2) Angry Hostility |
|  | (N3) Depression |
|  | (N4) Self-Consciousness |
|  | (N5) Impulsiveness |
|  | (N6) Vulnerability |
| E Extraversion | (E1) Warmth |
|  | (E2) Gregariousness |
|  | (E3) Assertiveness |
|  | (E4) Activity |
|  | (E5) Excitement-Seeking |
|  | (E6) Positive Emotions |
| O Openness to experience | (O1) Fantasy |
|  | (O2) Aesthetics |
|  | (O3) Feelings |
|  | (O4) Actions |
|  | (O5) Ideas |
|  | (O6) Values |
| A Agreeableness | (A1) Trust |
|  | (A2) Straightforwardness |
|  | (A3) Altruism |
|  | (A4) Compliance |
|  | (A5) Modesty |
|  | (A6) Tender-Mindedness |
| C Conscientiousness | (C1) Competence |
|  | (C2) Order |
|  | (C3) Dutifulness |
|  | (C4) Achievement Striving |
|  | (C5) Self-Discipline |
|  | (C6) Deliberation |

Some authors \[19-20\] have suggested to build *second order variables* from 35 variables of the NEO PI. Referring to personality disorders experts, these authors have suggested to calculate scores based on the facets of the NEO PI. These scores can be used to provide psychopathological assumptions from NEO PI responses although this is not the primary purpose of this test. Beyond the issue of personality disorders, the question of *readiness to start a psychotherapy* can be addressed. What aspects of personality could predict a good or a bad therapeutic alliance? Is it possible to create a score that could predict a good or a bad therapeutic alliance? If so, these scores would probably help to advise a more appropriate treatment before its beginning. Personality assessment might integrate this question prior to psychotherapy as suggested by Bucher, Suzuki, and Samuel \[4\]. The purpose of our study is to attempt to build such score(s) to assess patient's readiness to access some psychological treatment. For instance, personality assessment could include these scores in order to optimise future treatment.

# Method

## Participants

A request for participation in the study was sent by e-mail to clinicians we know or to psychologists and psychiatrists active on Facebook or Google+ forums. This request was made in French and concerned French-language clinicians having a current clinical practice. As we did not use a systematic recruitment of participants by appealing to professional associations, this is a convenience sample. Thirty-eight clinicians responded to our questionnaire including 27 women (71.1%) and 11 men (28.9%). Their mean age was equal to 38 years (SD = 11.05, minimum 25, maximum = 75). The mean duration of clinical practice was equal to 12.65 years (SD = 10.1, minimum = 1, maximum = 40). Twenty-nine participants (76.3%) followed psychology studies, 8 (21.1%) followed medical studies and 1 (2.6%) followed a type of studies not included in the list. Five participants (13.2%) were working in private practice, 18 (47.4%) in an institution and 15 (39.5%) in both. Fifteen participants (39.5%) were referring to psychoanalysis, 12 (31.6%) to a multireferential frame, 4 (10.5%) to the humanist frame, 3 (7.9%) to the systemic frame, 2 (5.3%) to the cognitive-behavioural frame, 2 (5.3%) to a not specified frame.

Our results are relatively close to those of the French Federation of Psychotherapy \[7\] that involves 1053 psychotherapists. They reported 73% women members, a mean age equal to 38 years, a mean of clinical practice equal to 13 years, 10% of reference to psychoanalysis, 72% humanistic and 18% multireferential.

## Procedure

Participants had to answer a googledocuments questionnaire. The instructions in the questionnaire were the following:

> In any clinical situation between a person and a professional clinician, the quality of the relationship between them plays a large role in the conduct of the intake as well as on its effect on the person. We often call "therapeutic alliance" the mutual collaboration between a patient and therapist in order to accomplish the objectives. Without sufficient therapeutic alliance, clinical interviews are likely to fail their goals. However this alliance may appear as a complex chemistry that is difficult to define precisely. Concerning the intake, it might be interesting to identify personality features that might facilitate or hinder a therapeutic alliance. As a professional clinician, could you rate each personality feature described below likely to facilitate therapeutic alliance on a five-level scale: Very negative effect (1), negative effect (2), not relevant (3), positive effect (4), very positive effect (5). Answer according to your own experience and your own clinical practice

The first questions of the questionnaire were related to: (a) sex, (b) age, (c) type of achieved studies, (d) number of experience years, (e) kind of practice, (f) theoretical main reference. The other questions regarded the 30 facets of the NEO PI but in their *two sides*: *high* and *low*. In fact, a low score to a facet has not always the opposite psychological interpretation than a high score to this facet \[5\].

For example, participants had to rate (1 to 5) these two items, which are opposite sides of the same NEO PI facet (N1 - Anxiety):

> N1^+^: "Feel apprehensive, fearful, worried, worried, preoccupied, nervous and tense."
>
> N1^-^: "Relaxed, serene, calm even in difficult and / or stressful situations"

## Data analysis

Our basic variables are the (30 x 2 =) 60 psychological facets rated by the experts theoretically ranging from 1 to 5. We also decided to calculate scores for (a) high Neuroticism, (b) high Extraversion, (c) high Openness, (d) high Agreeability and (e) high Consciousness by summing the scores obtained for six high facets that underlie them. Similarly, we have calculated scores for (f) low Neuroticism, (g) low Extraversion, (h) low Openness, (i) low Agreeability and (j) low Consciousness by summing the scores obtained for the six facets that underlie them.

For example: N^+^ = N1^+^ + N2^+^ + N3^+^ + N4^+^ + N5^+^ + N6^+^

Similarly, N^-^ = N1^-^ + N2^-^ + N3^-^ + N4^-^ + N5^-^ + N6^-^

The domain scores theoretically range from (1 x 6 =) **6** to (5 x 6 = ) **30**.

Consequently, we have (5 domains x 6 facets x 2 sides =) 60 facet scores and 10 domain scores. Thus, there are 70 personality variables in our study. We are essentially interested in the descriptive statistics of these 70 variables. A mean score equal to 3 means that experts do not think that this particular psychological variable has any impact on the therapeutic alliance. When mean scores are lower than 2 or higher then 4, it means that experts think that this particular psychological variable might have an impact on therapeutic alliance. In order to compare different kind of experts, we used non-parametric comparison tests: Mann-Whitney's *U* for two groups and Kruskal-Wallis *H* test for multiple groups. Taking into account how our global sample was composed, we decided to create two groups: (a) experts referring to psychoanalysis (*n* = 15) and (b) the others (*n* = 23). This may seem arbitrary but we created these two groups in order to have enough experts in both groups.

# Results

## Do experts rate FFM variables consistently?

We calculated an intra-class two-way random correlation coefficient (ICC2) to assess agreement between the 38 experts for all the facets of personality. We chose that model because we considered the 38 experts as being a mere sample of the "expert population" assessing systematically 60 personality variables. In this case, we were principally interested in the consistency of the ratings. A high degree of reliability was found between the measurements. The average measure ICC(2) was equal to .96 with a 95% confidence interval from .95 to .98 (*F* (59, 2183)= 29.49, *p* \< .001).

## Do experts rate FFM variables as having an impact on therapeutic alliance?

Table 2 contains descriptive statistics for the scores in each *domain* of the NEO PI (in their low and high polarity). It is noteworthy that no domain scores above 24 (when experts rate 4 for each 6 underlying facet) or below 12 (when experts rate 2 for each 6 underlying facet).

| Table 2 |   |   |   |   |   |   |
|:----------|-----------|-----------|-----------|-----------|-----------|-----------|
| *Descriptive statistics for 10 psychological domains supposed to predict therapeutic alliance according to 38 experts* |  |  |  |  |  |  |
| NEO PI Domain | Minimum | Maximum | Mean | Standard Deviation | *t* | *p* |
| O^+^ - Openness high | 18 | 29 | 22.97 | 2.64 | 11.62 | \<.001 |
| A^+^ - Agreeability high | 15 | 28 | 21.24 | 2.64 | 7.57 | \<.001 |
| C^+^ - Conscientiousness high | 16 | 25 | 21.00 | 2.30 | 8.04 | \<.001 |
| N^-^ - Neuroticism low | 13 | 25 | 19.21 | 2.58 | 2.89 | .006 |
| E^+^ - Extraversion high | 12 | 25 | 19.09 | 2.65 | 2.54 | .015 |
| N^+^ - Neuroticism high | 11 | 24 | 17.71 | 3.75 | -.64 | .637 |
| E^-^ - Extraversion low | 14 | 22 | 16.92 | 2.12 | -3.13 | .003 |
| C^-^ - Conscientiousness low | 9 | 23 | 15.26 | 3.38 | -4.99 | \<.001 |
| O^-^ - Openness low | 10 | 20 | 14.74 | 2.66 | -7.57 | \<.001 |
| A^-^ - Agreeability low | 6 | 19 | 12.13 | 3.36 | -10.76 | \<.001 |

Results show however that three domains are supposed to have positive effect on therapeutic alliance (O^+^, A^+^ and C^+^). Lower scores to these same domains (O^-^, A^-^ and C^-^) are also seen as potentially hampering therapeutic alliance. Do these three domain scores bring a common information? Correlation matrix (*r~s~*) highlights no significant correlation between them. We suppose that each bring a different kind of information on the question experts were asked. Nevertheless, facet level must be assessed.

Table 3 contains descriptive statistics for every *facet* of the NEO PI scores (in their low and high polarity). For facets supposed to affect *positively* therapeutic alliance, we have kept those whose mean was higher than 4 \[19\]. We have therefore kept the following variables: A2^+^, O3^+^, C5^+^, O5^+^.

|   |   | Table 3 |   |   |   |   |   |   |   |
|--------|--------|:-------|--------|--------|--------|--------|--------|--------|--------|
|  |  | . |  |  |  |  |  |  |  |
| NEO PI facet |  |  | Min | Max | Mean | Standard deviation | *t* | *p* |  |
| A2^+^ - Straightforwardness high |  |  | 2 | 5 | **4.26** | .64 | 12.08 | \<.001 |  |
| O3^+^ - Feelings high |  |  | 3 | 5 | **4.22** | .55 | 9.45 | \<.001 |  |
| C5^+^ - Self-discipline high |  |  | 2 | 5 | **4.08** | .78 | 8.48 | \<.001 |  |
| O5^+^ - Ideas high |  |  | 3 | 5 | **4.05** | .52 | 12.54 | \<.001 |  |
| O6^+^ - Values high |  |  | 1 | 5 | 3.92 | .88 | 6.44 | \<.001 |  |
| O2^+^ - Aesthetics high |  |  | 2 | 5 | 3.89 | .79 | 6.91 | \<.001 |  |
| O1^+^ - Fantasy high |  |  | 2 | 5 | 3.84 | .75 | 6.88 | \<.001 |  |
| C1^+^ - Competence high |  |  | 2 | 5 | 3.84 | .75 | 6.88 | \<.001 |  |
| E2^+^ - Gregariousness high |  |  | 2 | 5 | 3.82 | .65 | 7.72 | \<.001 |  |
| E1^+^ - Warmth high |  |  | 2 | 5 | 3.76 | .79 | 5.98 | \<.001 |  |
| A6^+^ - Tender-Mindedness high |  |  | 2 | 5 | 3.74 | .69 | 6.63 | \<.001 |  |
| N5^-^ - Impulsiveness low |  |  | 2 | 5 | 3.71 | .69 | 6.31 | \<.001 |  |
| A3^+^ - Altruism high |  |  | 2 | 5 | 3.66 | .85 | 4.79 | \<.001 |  |
| C4^+^ - Achievement Striving high |  |  | 2 | 5 | 3.66 | .67 | 6.06 | \<.001 |  |
| E4^-^ - Activity low |  |  | 3 | 5 | 3.63 | .59 | 6.61 | \<.001 |  |
| N1^-^ - Anxiety low |  |  | 2 | 5 | 3.63 | .75 | 5.19 | \<.001 |  |
| C6^+^ - Deliberation high |  |  | 3 | 5 | 3.58 | .59 | 5.96 | \<.001 |  |
| E6^+^ - Positive Emotions high |  |  | 2 | 5 | 3.50 | .83 | 3.71 | .001 |  |
| N2^-^ - Angry Hostility low |  |  | 2 | 5 | 3.39 | .72 | 3.39 | .002 |  |
| O4^+^ - Actions high |  |  | 2 | 5 | 3.26 | .79 | 2.04 | .05 |  |
| A1^+^ - Trust high |  |  | 2 | 5 | 3.26 | .83 | 1.96 | .06 |  |
| N4^+^ - Self-Consciousness high |  |  | 2 | 5 | 3.26 | .89 | 1.82 | .08 |  |
| N6^-^ - Vulnerability low |  |  | 1 | 5 | 3.24 | .88 | 1.65 | .11 |  |
| N1^+^ - Anxiety high |  |  | 1 | 5 | 3.18 | .93 | 1.23 | .23 |  |
| A4^+^ - Compliance high |  |  | 1 | 5 | 3.18 | .89 | 1.27 | .21 |  |
| C1^-^ - Competence low |  |  | 1 | 5 | 3.16 | 1.00 | .97 | .34 |  |
| A5^+^ - Modesty high |  |  | 2 | 5 | 3.13 | .93 | .87 | .39 |  |
| N3^+^ - Depression high |  |  | 1 | 5 | 3.13 | 1.12 | .73 | .47 |  |
| C2^+^ - Order high |  |  | 2 | 5 | 3.08 | .71 | .68 | .50 |  |
| N6^+^ - Vulnerability high |  |  | 1 | 5 | 2.97 | 1.13 | -.14 | .87 |  |
| N4^-^ - Self-Consciousness low |  |  | 2 | 4 | 2.97 | .72 | -.23 | .82 |  |
| E5^-^ - Excitement-Seeking low |  |  | 2 | 4 | 2.97 | .68 | -.24 | .81 |  |
| E3^-^ - Assertiveness low |  |  | 2 | 4 | 2.92 | .75 | -.65 | .52 |  |
| E4^+^ - Activity high |  |  | 1 | 5 | 2.87 | .88 | -.93 | .21 |  |
| E6^-^ - Positive Emotions low |  |  | 2 | 4 | 2.79 | .70 | -1.84 | .07 |  |
| C3^+^ - Dutifulness high |  |  | 1 | 4 | 2.76 | .88 | -1.65 | .11 |  |
| N2^+^ - Angry Hostility high |  |  | 1 | 5 | 2.74 | .92 | -1.76 | .09 |  |
| C6^-^ - Deliberation low |  |  | 1 | 5 | 2.68 | .90 | -2.15 | .04 |  |
| O4^-^ - Actions low |  |  | 1 | 4 | 2.63 | .79 | -2.89 | .006 |  |
| C5^-^ - Self-discipline low |  |  | 1 | 5 | 2.58 | .86 | -3.03 | .005 |  |
| C2^-^ - Order low |  |  | 1 | 4 | 2.58 | .83 | -3.14 | .003 |  |
| O6^-^ - Values low |  |  | 1 | 4 | 2.58 | .76 | -3.42 | .002 |  |
| O1^-^ - Fantasy low |  |  | 1 | 4 | 2.53 | .76 | -3.83 | \<.001 |  |
| E2^-^ - Gregariousness low |  |  | 1 | 4 | 2.53 | .76 | -3.83 | \<.001 |  |
| O2^-^ - Aesthetics low |  |  | 1 | 3 | 2.47 | .69 | -4.72 | \<.001 |  |
| N5^+^ - Impulsiveness high |  |  | 1 | 4 | 2.42 | .92 | -3.88 | \<.001 |  |
| E5^+^ - Excitement-Seeking high |  |  | 1 | 4 | 2.42 | .72 | -4.95 | \<.001 |  |
| A3^-^ - Altruism low |  |  | 1 | 4 | 2.37 | .82 | -4.75 | \<.001 |  |
| O5^-^ - Ideas low |  |  | 1 | 3 | 2.34 | .58 | -6.96 | \<.001 |  |
| A6^-^ - Tender-Mindedness low |  |  | 1 | 3 | 2.32 | .66 | -6.37 | \<.001 |  |
| N3^-^ - Depression low |  |  | 1 | 4 | 2.26 | .72 | -6,28 | \<.001 |  |
| C4^-^ - Achievement Striving low |  |  | 1 | 4 | 2.24 | .82 | -5,74 | \<.001 |  |
| O3^-^ - Feelings low |  |  | 1 | 4 | 2.18 | .73 | -6,89 | \<.001 |  |
| A4^-^ - Compliance low |  |  | 1 | 4 | 2.11 | .92 | -5,97 | \<.001 |  |
| E1^-^ - Warmth low |  |  | 1 | 4 | 2.08 | .75 | -7,58 | \<.001 |  |
| E3^+^ - Assertiveness high |  |  | 1 | 4 | 2.06 | .73 | -5,52 | \<.001 |  |
| C3^-^ - Dutifulness low |  |  | 1 | 3 | 2.03 | .64 | -9,44 | \<.001 |  |
| A1^-^ - Trust low |  |  | 1 | 4 | **1.87** | .88 | -7,97 | \<.001 |  |
| A2^-^ - Straightforwardness low |  |  | 1 | 4 | **1.76** | 1.03 | -7,44 | \<.001 |  |
| A5^-^ - Modesty low |  |  | 1 | 4 | **1.71** | .73 | -10,86 | \<.001 |  |

For facets supposed to have a *negative* effect on therapeutic alliance, we have kept those whose mean was lower than 2 \[19\]. We have therefore kept the following variables: A5^-^, A2^-^, A1^-^.

## Proposed scores for assessing readiness to therapeutic alliance

We propose two evaluation methods for assessing readiness to therapeutic alliance calculated with the *raw scores* for the NEO PI. At the NEO PI *domain* level, the score could be obtained as follows:

Score 1 = O + A + C

If we compare the 15 psychotherapists of psychoanalytic reference to the 23 others, O, A and C are estimated as important referring to the Mann-Whitney's *U* (*p* \> 0.05). There is no significant difference. At the NEO PI *facet* level, we propose two scores. The first score relies in the facets supposed to *facilitate therapeutic alliance*:

Score 2 = A2 + O3 + C5 + O5

If we compare the 15 psychotherapists of psychoanalytic reference to the 23 others, A2^+^, O3^+^, C5^+^ and O5^+^ variables are estimated as important referring to the Mann-Whitney's *U* (*p* \> 0.006 taking into account the Bonferroni correction). There is no significant difference. Kruskal-Wallis *H* test does not highlight significant differences for practitioners in private practice, in an institution or both. Nor the age nor the number of experience years are significantly correlated with these variables.

The second score relies on the facets that are seen as *hampering* therapeutic alliance:

Score 3 = (32 - A5) + (32 - A2) + (32 - A1).

If we compare the 15 psychotherapists of psychoanalytic reference to the 23 others, A5^-^, A1^-^ and A2^-^ are estimated as important referring to the Mann-Whitney's *U* (*p* \> 0.006). No significant correlation were found. Kruskal-Wallis *H* test does not highlight significant differences for practitioners in private practice, in an institution or both. Nor the age nor the number of years of experience are significantly correlated with these variables.

# Discussion

The results suggest a high degree of agreement between the 38 clinical experts. We didn't identify a significant influence of the theoretical model, age nor type of practice on the ratings. This is an interesting result because it suggests that, in the context of a therapeutic alliance, there is a consensus that goes beyond any theoretical and ideological divisions that any particular therapeutic model could create. Similarly, Laska, Gurman and Wampold \[17\] insist that therapeutic alliance has an equivalent effect for several kind of psychotherapeutic frames. According to our experts, Openness, Agreeability and Conscientiousness of their patients are likely to facilitate therapeutic alliance. We proposed a score based on these three NEO PI domains that could be used when the clinician only have access to the domain scores. Yet, it seems that these domain scores are less accurate than facets when assessing this matter. Not all facets underlying a specific domain has been considered as relevant by experts. We encourage therefore to assess the facet level with the two other scores that we propose. More specifically, the "ideal" patient shows the following personality features (in descending order of importance): frank and sincere, experiencing many deep emotions, a strong ability to motivate himself in the pursuit of long-term goals and commitments despite boredom, difficulties or obstacles, prone to debates, discussions or controversies. In contrast, the "bad" patient would have the following personality features (in descending order of importance): feels like a superior person, pretentious and arrogant, manipulates others by flattery, trickery or deception, tends to be cynical and sceptical, thinks that others are fundamentally dishonest and malicious. What can we conclude about these two profiles?

The first profile highlights the willingness of the patient to meet the therapist, to engage, to question, including emotional authenticity but also respect the commitment in the therapeutic framework proposed by therapist. An half of these facets relate to the open character. The second profile highlights self-sufficiency of patient and his/her lack of trust or competitive attitude. All of these facets relate to the agreeable domain. This is an interesting result. Indeed, it suggests that factors supposed to *hamper* therapeutic alliance would primarily be *relational* (mistrust for the therapist, for example) while elements that *facilitate* therapy would be more *"intellectual"* (taste for discussion and questioning of beliefs for example). This is consistent with the idea that the aim of therapy is often to make a patient change his/her point of view on the world and on himself/herself. This idea of personal change is compatible with an open mind. An underlying idea seems to be that psychotherapy is an opportunity for patient to understand his life (and possibly his suffering) differently. If we refer to the styles included in the manual of the NEO PI 3, one that is considered here is called "attitude style", which depends on O and A. We hypothesise that O^+^A^+^ style would be indicative of a better therapeutic alliance than O-A- style. Conversely, O-A- style would indicate a less favourable therapeutic alliance. We agree with Miller \[21\] who considers that openness influences the reactions of patient to therapist's interventions that agreeableness colours the relationship with the therapist and that conscientiousness influences compliance with the therapeutic setting. On the other hand, and this is surprising, aspects of neuroticism and extraversion are seldom mentioned as being relevant by our experts. Neuroticism is directly linked to experiences of suffering and dissatisfaction, namely negative feelings. Often, it is precisely because a person suffers psychologically that he/she decides to meet a psychotherapist. However, it seems that this suffering is neither a good nor a bad predictor of the quality of the therapeutic alliance, at least in the eyes of our therapists. On this matter, note that Samuel, Bucher and Suzuki \[29\] did not identify a significant correlation between neuroticism and psychotherapy outcomes in a clinical sample. These two domains are therefore not included decisively in the calculation of our scores of therapeutic alliance.

We must once again recall that domains and facets highlighted in this study rely on perception of therapists. To answer the questionnaire, they had to build an image of the "good" and "bad" patient. It is possible that their representations are skewed in a way or another. For example, a therapist may believe that his/her patient want to obtain a new perspective on their own lives while the patient would only wish his/her suffering to decrease. This highlights the complexity of therapeutic alliance. Indeed, expectations of the two actors may be different, but they must also find points of convergence. Otherwise, therapy could lose its point and become meaningless. Both, patient and therapist need to adjust during the sessions. Another limitation of this study is that the included sample of experts might not be representative of all psychotherapists. Indeed, there are cultural influences in the perception of psychotherapy, often for historical reasons. Would other experts identify other facets of personality in relation to therapeutic alliance? Only an international replication of this study can answer this question.

Are the scores that we propose here reliable predictors of a good therapeutic success? It is certainly too early to answer this question. For now, we cannot yet provide standards for these three scores. However, it would be possible to calculate these for different groups and make comparisons. Once these comparisons have been made, a method could be considered to assess the relevance of these scores to predict effectiveness of therapeutic alliance from a clinical point of view. When addressing the best fit between a specific patient and the most appropriate treatment, Beutler, Someah, Kimpara and Miller \[1\] see patient factors as mediating or moderating variables. This means that personality variables might have an influence on psychotherapy outcome but would not be the most predictive variables when considering other aspects of psychotherapy. As a matter of fact, the link between personality and treatment outcome might not be straightforward. Indeed, many other variables are involved. For example, we did not address psychopathology severity that might influence global treatment, including therapeutic alliance.

This study suggests a new way to evaluate therapeutic possibilities with a patient based on a general personality questionnaire such as the NEO PI. It must be seen as an experimental attempt to link psychotherapy and personality assessment researches as proposed by Koole and Tschacher \[16\] when claiming that "alliance research would do well to nurture a more multidisciplinary orientation". So far, no definite conclusions should be drawn from these scores.

# References

1.  Beutler LE, Someah K, Kimpara S, Miller K. Selecting the most appropriate treatment for each patient. International Journal of Clinical and Health Psychology. 2016;16(1):99--108.

2.  Bioy A, Bachelart M. L'alliance thérapeutique: historique, recherches et perspectives cliniques. Perspectives psy. 2010;49(4):317--326.

3.  Bordin ES. The generalizability of the psychoanalytic concept of the working alliance. Psychotherapy: Theory, research & practice. 1979;16(3):252.

4.  Bucher MA, Suzuki T, Samuel DB. A meta-analytic review of personality traits and their associations with mental health treatment outcomes. Clinical psychology review. 2019;

5.  Costa PT, McCrae RR. The revised neo personality inventory (NEO-PI-R). The SAGE handbook of personality theory and assessment. 2008;2(2):179--198.

6.  Diener MJ, Monroe JM. The relationship between adult attachment style and therapeutic alliance in individual psychotherapy: A meta-analytic review. Psychotherapy. 2011;48(3):237.

7.  Fédération Française de Psychothérapie. Pourquoi la psychothérapie»? Fondements, méthodes, applications. Dunod; 2005.

8.  Fluckiger C, Del Re A, Wampold B, Horvath A. The alliance in adult psychotherapy: A meta-analytic synthesis. Psychotherapy. Advance online publication. 2018.

9.  Freud S. Advice to the doctor in the analytic treatment. In: Oeuvres complètes-Psychanalyse. Presses Universitaires de France; 1912. p. 43--154.

10. Goldfried M.R., Castonguay L.G., Safran J.D. Questions fondamentales et perspectives d'avenir de l'int├®gration en psychoth├®rapie. In Norcross J.C. & Goldfried M.R. Psychothérapie intégrative. Desclée de Brouwer. 1998:321-343.

11. Goldberg LR, Johnson JA, Eber HW, Hogan R, Ashton MC, Cloninger CR, et al. The international personality item pool and the future of public-domain personality measures. Journal of Research in personality. 2006;40(1):84--96.

12. Horvath AO, Del Re A, Fluckiger C, Symonds D. Alliance in individual psychotherapy. Psychotherapy. 2011;48(1):9.

13. Horvath AO, Luborsky L. The role of the therapeutic alliance in psychotherapy. Journal of consulting and clinical psychology. 1993;61(4):561.

14. Horvath AO, Symonds BD. Relation between working alliance and outcome in psychotherapy: A meta-analysis. Journal of counseling psychology. 1991;38(2):139.

15. Kokotovic AM, Tracey TJ. Working alliance in the early phase of counseling. Journal of counseling psychology. 1990;37(1):16.

16. Koole SL, Tschacher W. Synchrony in psychotherapy: A review and an integrative framework for the therapeutic alliance. Frontiers in psychology. 2016;7:862.

17. Laska KM, Gurman AS, Wampold BE. Expanding the lens of evidence-based practice in psychotherapy: a common factors perspective. Psychotherapy. 2014;51(4):467.

18. Martin DJ, Garske JP, Davis MK. Relation of the therapeutic alliance with outcome and other variables: a meta-analytic review. Journal of consulting and clinical psychology. 2000;68(3):438.

19. Miller JD, Hyatt CS, Maples-Keller JL, Carter NT, Lynam DR. Psychopathy and Machiavellianism: A distinction without a difference? Journal of personality. 2017;85(4):439--453.

20. Miller JD, Lynam DR, Rolland J-P, De Fruyt F, Reynolds SK, Pham-Scottez A, et al. Scoring the DSM-IV personality disorders using the five-factor model: Development and validation of normative scores for North American, French, and Dutch-Flemish samples. Journal of Personality Disorders. 2008;22(5):433--450.

21. Miller TR. The psychotherapeutic utility of the five-factor model of personality: A clinician's experience. Journal of Personality Assessment. 1991;57(3):415--433.

22. Moras K, Strupp HH. Pretherapy interpersonal relations, patients' alliance, and outcome in brief therapy. Archives of General Psychiatry. 1982;39(4):405--409.

23. Mullins-Sweatt SN, Jamerson JE, Samuel DB, Olson DR, Widiger TA. Psychometric properties of an abbreviated instrument of the five-factor model. Assessment. 2006;13(2):119--137.

24. Ogrodniczuk JS, Piper WE, Joyce AS, McCallum M, Rosie JS. NEO-five factor personality traits as predictors of response to two forms of group psychotherapy. International Journal of Group Psychotherapy. 2003;53(4):417--442.

25. Puschner B, Bauer S, Horowitz LM, Kordy H. The relationship between interpersonal problems and the helping alliance. Journal of Clinical Psychology. 2005;61(4):415--429.

26. Rogers CR. Client-centered therapy: Its current practice, implications, and theory. Houghton Mifflin Boston; 1959.

27. Rolland J-P. L'évaluation de la personnalité: Le modèle en cinq facteurs. Mardaga; 2013.

28. Ross EC, Polaschek DL, Ward T. The therapeutic alliance: A theoretical revision for offender rehabilitation. Aggression and violent behavior. 2008;13(6):462--480.

29. Samuel DB, Bucher MA, Suzuki T. A Preliminary Probe of Personality Predicting Psychotherapy Outcomes: Perspectives from Therapists and Their Clients. Psychopathology. 2018;51(2):122--129.

30. Wallner-Samstag, L., Muran, C., Zindel, V., Segal, Z., & Schuman, C. Patient pretreatment interpersonal problems and therapeutic alliance in short-term cognitive therapy. Paper presented at the Annual meeting of the Society for Psychotherapy Research, Berkeley, CA. 1992.

31. Wampold B. How important are the common factors in psychotherapy? An update. World Psychiatry. 2015;14(3):270--277.
