<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Benjamin Thiry">
<meta name="author" content="Stéphanie Ponchaux">
<meta name="description" content="Notre étude propose d’approfondir le lien entre certains comportements problématiques ou délinquants et la personnalité de leur auteur. 112 adolescents de 15 ou 16 ans ont répondu au NEO PI-R, qui est un questionnaire de personnalité, ainsi qu’à un questionnaire de délinquance auto-révélé. Les comportements problématiques présentent des corrélations significatives avec les variables A, A2, A4, C, C2, C6, antisocialité et psychopathie du NEO PI-R. Les comportements délinquants présentent des corrélations significatives avec les variables E2, A, A2, A3, A4, A5, C, C1, C2, C3, C5, C6, antisocialité et psychopathie du NEO PI-R. Un modèle économique propose de prédire les comportements délinquants à partir de l’équation de régression suivante : E3 – C3 – A2 – E3xA2 (R = .43, p < .001). Ces résultats permettent de soutenir l’idée qu’il existe donc au moins trois sphères psychologiques en lien avec la tendance antisociale (morale, relationnelle et comportementale) et qu’il s’agit d’un concept complexe. Nous discutons ces résultats en regard de certaines théories criminologiques classiques.">

<title>Comparaison de variables de délinquance auto-révélée avec des variables de personnalité selon le modèle en cinq facteurs auprès d’adolescents – Psychologie et délinquance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b53751a350365c71b6c909e95f209ed1.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-38d94b3cac77cd3e685c79e69241b0ba.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-86ef44f33eb6204f81838d6c66abc062.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../benjaminthiry.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Psychologie et délinquance</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Recherche"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Basculer la navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">Qui écrit ce blog ?</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://tchafia.be/@ouriagan"> <i class="bi bi-mastodon" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ouriagan/blog"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Basculer le mode sombre"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Comparaison de variables de délinquance auto-révélée avec des variables de personnalité selon le modèle en cinq facteurs auprès d’adolescents</h1>
                  <div>
        <div class="description">
          Notre étude propose d’approfondir le lien entre certains comportements problématiques ou délinquants et la personnalité de leur auteur. 112 adolescents de 15 ou 16 ans ont répondu au NEO PI-R, qui est un questionnaire de personnalité, ainsi qu’à un questionnaire de délinquance auto-révélé. Les comportements problématiques présentent des corrélations significatives avec les variables A, A2, A4, C, C2, C6, antisocialité et psychopathie du NEO PI-R. Les comportements délinquants présentent des corrélations significatives avec les variables E2, A, A2, A3, A4, A5, C, C1, C2, C3, C5, C6, antisocialité et psychopathie du NEO PI-R. Un modèle économique propose de prédire les comportements délinquants à partir de l’équation de régression suivante : E3 – C3 – A2 – E3xA2 (R = .43, p &lt; .001). Ces résultats permettent de soutenir l’idée qu’il existe donc au moins trois sphères psychologiques en lien avec la tendance antisociale (morale, relationnelle et comportementale) et qu’il s’agit d’un concept complexe. Nous discutons ces résultats en regard de certaines théories criminologiques classiques.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">analyses statistiques</div>
                <div class="quarto-category">psychologie</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Auteur·rice·s</div>
      <div class="quarto-title-meta-contents">
               <p>Benjamin Thiry </p>
               <p>Stéphanie Ponchaux </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Date de publication</div>
      <div class="quarto-title-meta-contents">
        <p class="date">23 février 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Sur cette page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#méthode" id="toc-méthode" class="nav-link" data-scroll-target="#méthode">Méthode</a>
  <ul class="collapse">
  <li><a href="#participants" id="toc-participants" class="nav-link" data-scroll-target="#participants">Participants</a></li>
  <li><a href="#procédure" id="toc-procédure" class="nav-link" data-scroll-target="#procédure">Procédure</a>
  <ul class="collapse">
  <li><a href="#questionnaire-de-délinquance-auto-révélée" id="toc-questionnaire-de-délinquance-auto-révélée" class="nav-link" data-scroll-target="#questionnaire-de-délinquance-auto-révélée">Questionnaire de délinquance auto-révélée</a></li>
  </ul></li>
  <li><a href="#traitement-statistique" id="toc-traitement-statistique" class="nav-link" data-scroll-target="#traitement-statistique">Traitement statistique</a></li>
  </ul></li>
  <li><a href="#résultats" id="toc-résultats" class="nav-link" data-scroll-target="#résultats">Résultats</a>
  <ul class="collapse">
  <li><a href="#fiabilité-des-variables" id="toc-fiabilité-des-variables" class="nav-link" data-scroll-target="#fiabilité-des-variables">Fiabilité des variables</a></li>
  <li><a href="#statistiques-descriptives" id="toc-statistiques-descriptives" class="nav-link" data-scroll-target="#statistiques-descriptives">Statistiques descriptives</a></li>
  <li><a href="#liens-entre-les-variables-psychologiques-et-criminologiques" id="toc-liens-entre-les-variables-psychologiques-et-criminologiques" class="nav-link" data-scroll-target="#liens-entre-les-variables-psychologiques-et-criminologiques">Liens entre les variables psychologiques et criminologiques</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p><img src="schooldarksky.png" class="img-fluid"></p>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>L’intérêt pour le lien entre la <em>personnalité</em> d’un individu et sa propension à commettre des <em>actes transgressifs</em> est ancien et a donné naissance à une discipline nouvelle au 19<sup>ème</sup> siècle : la <em>criminologie</em>. En effet, c’est avec <span class="citation" data-cites="lombroso1876homme">Lombroso (<a href="#ref-lombroso1876homme" role="doc-biblioref">1876</a>)</span>, <span class="citation" data-cites="garofalo1888criminologie">Garofalo (<a href="#ref-garofalo1888criminologie" role="doc-biblioref">1888</a>)</span> et <span class="citation" data-cites="ferri1893sociologie">Ferri (<a href="#ref-ferri1893sociologie" role="doc-biblioref">1893</a>)</span> qu’une première théorie supposait l’existence d’une <em>personnalité criminelle</em> à l’origine des passages à l’acte délictueux. Ces thèses furent vivement critiquées par la suite notamment par des criminologues se référant au paradigme sociologique. Pour ceux-ci, la tendance à la délinquance est majoritairement déterminée par des variables sociales et situationnelles indépendantes de la personnalité du délinquant. En psychiatrie et en psychologie clinique, la personnalité dite criminelle a toutefois survécu en changeant plusieurs fois de formes et de noms. Aujourd’hui, le DSM-5 <span class="citation" data-cites="american2013dsm">(<a href="#ref-american2013dsm" role="doc-biblioref">APA, 2013</a>)</span> évoque la <em>personnalité antisociale</em> parmi les troubles de la personnalité. En parallèle, la <em>psychopathie</em> est un domaine de recherche très fécond et vivant. C’est bien souvent au travers d’entretiens cliniques (structurés ou non) et d’études du parcours de vie (notamment pénal) que ces diagnostics sont posés selon une logique catégorielle : ce patient correspond-il aux critères de l’antisocialité / de la psychopathie ou pas ? Cette approche catégorielle des troubles de la personnalité a toutefois fait l’objet de critiques <span class="citation" data-cites="westen1998limitations widiger2005diagnostic">(<a href="#ref-westen1998limitations" role="doc-biblioref">Westen &amp; Arkowitz-Westen, 1998</a>; <a href="#ref-widiger2005diagnostic" role="doc-biblioref">Widiger &amp; Samuel, 2005</a>)</span> qui ont mené à une conception <em>dimensionnelle</em> de ces troubles <span class="citation" data-cites="widiger2002personality">(<a href="#ref-widiger2002personality" role="doc-biblioref">Costa &amp; Widiger, 2002</a>)</span>. <span class="citation" data-cites="lynam2001using">Lynam &amp; Widiger (<a href="#ref-lynam2001using" role="doc-biblioref">2001</a>)</span> établirent ainsi des profils prototypiques pour chaque trouble de la personnalité sur base de l’avis de spécialistes de ces troubles. Les scores obtenus par un individu à un questionnaire de personnalité auto-rapporté tel que le NEO PI-R <span class="citation" data-cites="costa1998neo">(<a href="#ref-costa1998neo" role="doc-biblioref">Costa, McCrae, &amp; Rolland, 1998</a>)</span> permettent dès lors d’évaluer leur ressemblance avec le profil typique de tel ou tel trouble de la personnalité selon sa description dans le DSM-IV <span class="citation" data-cites="american1994dsm">(<a href="#ref-american1994dsm" role="doc-biblioref">APA, 1994</a>)</span>. La méta-analyse de <span class="citation" data-cites="samuel2008meta">Samuel &amp; Widiger (<a href="#ref-samuel2008meta" role="doc-biblioref">2008</a>)</span> et la revue de la littérature de <span class="citation" data-cites="miller2012five">Miller (<a href="#ref-miller2012five" role="doc-biblioref">2012</a>)</span> permettent de soutenir l’hypothèse d’un lien robuste entre les variables du modèle en cinq facteurs et les troubles de la personnalité. Cette approche permet d’aborder les troubles de la personnalité selon une logique dimensionnelle, donc continue, et plus nuancée que l’approche catégorielle. <span class="citation" data-cites="miller2012five">Miller (<a href="#ref-miller2012five" role="doc-biblioref">2012</a>)</span> encourage l’exploitation de ce modèle dans les futures taxonomies psychiatriques. Concernant la personnalité antisociale, <span class="citation" data-cites="gudonis2008conceptualizing">Gudonis, Miller, Miller, &amp; Lynam (<a href="#ref-gudonis2008conceptualizing" role="doc-biblioref">2008</a>)</span> ont comparé les scores d’antisocialité générés sur base du prototype du modèle en cinq facteurs et les résultats d’un entretien diagnostic semi-structuré en relation avec des variables telles que l’agression, la délinquance, l’usage de drogues, la psychopathie, le comportement sexuel à risque, le niveau d’étude, la carrière professionnelle et le quotient intellectuel. Ils trouvèrent que les deux types de scores présentaient des corrélations très similaires (ICC = .85). <span class="citation" data-cites="jones2011personality">Jones, Miller, &amp; Lynam (<a href="#ref-jones2011personality" role="doc-biblioref">2011</a>)</span> se sont intéressés aux facettes qui sous-tendent les cinq grands domaines du NEO PI-R et constatent que celles qui présentent les tailles d’effet les plus élevés avec le comportement antisocial sont la droiture (A2), la compliance (A4), la délibération (C6), le sens du devoir (C3) et l’altruisme (A3). Selon <span class="citation" data-cites="miller2012five">Miller (<a href="#ref-miller2012five" role="doc-biblioref">2012</a>)</span>, le score d’antisocialité calculé sur base du NEO PI-R présente une validité convergence dont la taille d’effet pondérée est égale à .40 (sur base de 13 études, <em>N</em> = 3087). Ces scores méritent toutefois d’autres travaux de validation.</p>
<p>La présente étude poursuit plusieurs objectifs. Le premier est d’évaluer le lien entre les scores d’antisocialité et de psychopathie extraits du NEO PI-R et des variables criminologiques extraites d’un questionnaire de délinquance auto-révélée (qui évalue également des variables de victimisation). Le deuxième est de s’intéresser au lien entre les domaines mais aussi les facettes du NEO PI-R et ces variables criminologiques. Le troisième est de réfléchir aux liens complexes susceptibles d’exister entre des variables de personnalité et des comportements délinquants.</p>
</section>
<section id="méthode" class="level1">
<h1>Méthode</h1>
<section id="participants" class="level2">
<h2 class="anchored" data-anchor-id="participants">Participants</h2>
<p>Nous avons envoyé un courrier expliquant le but de la recherche à quatorze établissements scolaires de la région de Tournai (en Belgique). Cette région a été choisie car elle nous permettait d’accéder aisément aux établissements grâce à la proximité géographique de la réalisation de l’étude. Parmi les quatorze établissements, deux ont répondu favorablement : l’un de type général et l’autre de type général et technique. Tous deux ont signé un formulaire de consentement à l’étude.</p>
<p>Notre échantillon initialement composé de 133 sujets est constitué d’étudiants âgés de quinze à seize ans effectuant leurs études dans une école secondaire belge. Cette tranche d’âges est considérée d’un point de vue criminologique comme étant l’âge d’entrée le plus fréquent dans les parcours délictueux <span class="citation" data-cites="born2017psychologie">(<a href="#ref-born2017psychologie" role="doc-biblioref">Born &amp; Glowacz, 2017</a>)</span>. En Belgique, dès seize ans, certains étudiants sont susceptibles de suivre une formation pratique et fréquentent dès lors plus rarement l’établissement scolaire. Nous pensons que nos étudiants sont représentatifs des établissements scolaires qu’ils fréquentent.<br>
Lors du dépouillement des protocoles et de leur analyse, il est ressorti que 21 des protocoles sur les 133 distribués à notre échantillon étaient invalides et ceci pour diverses raisons telles que : non remplis par choix, remplis de façon volontairement biaisée, non achevés soit par manque de temps, soit par lassitude, etc. L’échantillon final constituant cette étude est composé de 112 participants ayant complètement rempli le protocole qui leur a été remis. Parmi ces 112, la variable de <em>problème de délinquance</em> présentait une valeur potentiellement problématique car un des participant a rapporté beaucoup plus de problèmes de délinquance que les autres (66). Par prudence, nous avons exclu cette valeur des traitement statistiques.</p>
</section>
<section id="procédure" class="level2">
<h2 class="anchored" data-anchor-id="procédure">Procédure</h2>
<p>Deux échelles d’évaluations ont été soumises à notre population d’adolescents dans le local de cours. Suite aux exigences des établissements, la passation des protocoles a été effectuée en 1h30. Avant de démarrer la passation du protocole anonymisé par l’attribution d’un numéro, une brève présentation de l’étude fut exposée aux participants. Le protocole de passation établi se composait d’une échelle d’évaluation de la personnalité élaborée sur base du modèle en cinq facteurs qu’est le NEO PI-R <span class="citation" data-cites="costa1998neo">(<a href="#ref-costa1998neo" role="doc-biblioref">Costa et al., 1998</a>)</span> ainsi que d’une échelle d’évaluation auto-révélée de la délinquance élaborée pour ce travail et inspirée de <span class="citation" data-cites="born2007isrd">Born &amp; Glowacz (<a href="#ref-born2007isrd" role="doc-biblioref">2007</a>)</span> qui ont participé au projet de l’International Study on Self-Related Delinquency (ISRD) en collaboration avec <span class="citation" data-cites="junger2012introduction">Junger-Tas &amp; Marshall (<a href="#ref-junger2012introduction" role="doc-biblioref">2012</a>)</span>. Des dictionnaires furent mis à la disposition des participants pour les aider à répondre aux questionnaires.</p>
<section id="questionnaire-de-délinquance-auto-révélée" class="level3">
<h3 class="anchored" data-anchor-id="questionnaire-de-délinquance-auto-révélée">Questionnaire de délinquance auto-révélée</h3>
<p>Le questionnaire auto-révélée de la délinquance se composait notamment de trois questions principales :</p>
<ol type="1">
<li>Avez-vous déjà eu l’un des problèmes suivants ?</li>
</ol>
<ul>
<li>Brouille ou dispute</li>
<li>Bagarre</li>
<li>Accident ou blessure</li>
<li>Perte d’argent ou d’autres objets de valeur</li>
<li>Objets ou vêtements abîmés</li>
<li>Problèmes avec vos parents</li>
<li>Problèmes avec vos amis</li>
<li>Problèmes avec vos professeurs</li>
<li>Mauvais résultats à l’école ou au travail</li>
<li>Victime d’un vol</li>
<li>Problèmes avec la police</li>
<li>Hospitalisé ou admis aux urgences</li>
<li>Rapport sexuel que vous regrettez le lendemain Rapport sexuel non protégé</li>
</ul>
<ol start="2" type="1">
<li>Au cours des 12 derniers mois, selon quelle fréquence avez-vous…</li>
</ol>
<ul>
<li>Frappé un de vos professeurs</li>
<li>Été impliqué(e) à une bagarre à l’école ou au travail</li>
<li>Pris part à une bagarre où un groupe de vos amis était confronté à un autre groupe</li>
<li>Blessé quelqu’un suffisamment pour qu’il ait besoin de bandages ou d’un docteur</li>
<li>Utilisé une arme de quelque sorte pour obtenir quelque chose de quelqu’un</li>
<li>Pris quelque chose dans une boutique sans le payer</li>
<li>Mis exprès le feu aux affaires de quelqu’un d’autre</li>
<li>Abîmé exprès du matériel de l’école</li>
<li>Eu des problèmes avec la police à cause de quelque chose que vous aviez fait</li>
<li>Fait partie d’un groupe persécutant un individu</li>
<li>Fait partie d’un groupe blessant physiquement un individu</li>
<li>Fait partie d’un groupe commençant une bagarre avec un autre groupe</li>
<li>Provoqué une bagarre avec un autre individu</li>
<li>Volé quelque chose d’une valeur de 15€ ou plus</li>
<li>Entré par effraction quelque part pour voler</li>
<li>Abîmé exprès des biens publics ou privés</li>
<li>Vendu des objets volés</li>
</ul>
<ol start="3" type="1">
<li>Au cours des 12 derniers mois, selon quelle fréquence avez-vous…</li>
</ol>
<ul>
<li>Été personnellement persécuté(e) par tout un groupe</li>
<li>Été blessé(e) physiquement par tout un groupe</li>
<li>Fait partie d’un groupe qui a été attaqué par un autre groupe</li>
<li>Été impliqué(e) dans une bagarre par quelqu’un</li>
<li>Été victime de vol pour une valeur de 15€ ou plus</li>
<li>Quelqu’un est entré par effraction chez vous pour voler quelque chose</li>
<li>Quelque chose vous appartenant a été abîmé exprès</li>
<li>Acheté des objets volés</li>
</ul>
<p>Au terme de la passation, un feed-back fut proposé aux élèves qui le souhaitaient. Nous leur laissions pour ce faire nos coordonnées électroniques et téléphoniques tout en leur précisant de garder précieusement leur numéro de protocole, celui-ci permettant de faire le lien avec les résultats pour un éventuel feed-back.</p>
</section>
</section>
<section id="traitement-statistique" class="level2">
<h2 class="anchored" data-anchor-id="traitement-statistique">Traitement statistique</h2>
<p>Les domaines et les facettes du NEO PI-R ont été calculés conformément au manuel français du test <span class="citation" data-cites="costa1998neo">(<a href="#ref-costa1998neo" role="doc-biblioref">Costa et al., 1998</a>)</span>. La variable de la personnalité antisociale a été calculée selon cette formule<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> :</p>
<p><span class="math display">\[
antisocialité = N1r + N2 + N4r + N5 + E3 + E4 + E5 + O4 + A1r + A2r + A3r + A4r\\ + A5r + A6r + C3r + C5r + C6r
\]</span></p>
<p>La variable de psychopathie a été calculée selon cette formule<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> :</p>
<p><span class="math display">\[
psychopathie = N1r + N3r + N4r + N5 + N6r + E1r + E3 + E5 + O3r + O4 + A1r + A2r\\ + A3r + A4r + A5r + A6r + C1 + C3r + C5r + C6r
\]</span> Selon <span class="citation" data-cites="decuyper2009validation">Decuyper, De Clercq, De Bolle, &amp; De Fruyt (<a href="#ref-decuyper2009validation" role="doc-biblioref">2009</a>)</span>, ces deux variables sont utilisables auprès d’une population d’adolescents et présentent une validité convergente forte avec la personnalité antisociale. Les variables de validité ont été calculées selon la méthode de <span class="citation" data-cites="schinka1997research">Schinka, Kinder, &amp; Kremer (<a href="#ref-schinka1997research" role="doc-biblioref">1997</a>)</span> et <span class="citation" data-cites="schinka2011scoring">Schinka (<a href="#ref-schinka2011scoring" role="doc-biblioref">2011</a>)</span>. Elles sont au nombre de trois : (a) NPM renvoie à la tendance à présenter une image négative de soi, (b) PPM renvoie à la tendance à présenter une image positive de soi et (c) INC renvoie à la tendance à répondre de manière incohérente.</p>
<p>Nous disposons de trois variables criminologiques :</p>
<ul>
<li>La variable <em>problèmes</em> est la somme des 14 items du questionnaires cotés 0 (“jamais”) ou 1 (oui). La somme varie dès lors théoriquement de 0 à 14.</li>
<li>La variable <em>faits de délinquance</em> est la somme des 17 items du questionnaire coté de 0 (“jamais”), 1, 2, 3 ou 4 (“cinq fois ou plus”). La somme varie dès lors théoriquement de 0 à 68</li>
<li>La variable <em>faits de victimisation</em> est la somme des 8 items du questionnaire coté 0 (“jamais), 1, 2, 3 ou 4 (“cinq fois ou plus”). La somme varie dès lors théoriquement de 0 à 32.</li>
</ul>
<p>Les corrélations que nous avons effectuées sont des corrélations non paramétriques (Rho de Spearman). Pour effectuer les équations de régression, nous avons centré les variables et omis un participant dont le score de faits de délinquance était extrême (66).</p>
</section>
</section>
<section id="résultats" class="level1">
<h1>Résultats</h1>
<section id="fiabilité-des-variables" class="level2">
<h2 class="anchored" data-anchor-id="fiabilité-des-variables">Fiabilité des variables</h2>
<p>Concernant les cinq grands domaines (comptant chacun six facettes) du NEO PI-R, l’alpha de Cronbach est égal à .84 pour N, .74 pour E, .71 pour O, .76 pour A et à .82 pour C.</p>
<p>L’alpha de Cronbach des trois échelles criminologiques est égal à .79 pour <em>problèmes</em>, .94 pour <em>faits de délinquance</em> et à .36 pour <em>faits de victimisation</em>. Pour évaluer l’unidimensionalité de ces trois variables, nous avons procédé à trois analyses factorielles. Concernant problèmes, le premier facteur explique 28% de la variance. Seul l’item <em>rapport sexuel non protégé</em> ne sature pas ce facteur. Concernant faits de délinquance, un facteur explique 62% de la variance totale. Concernant faits de victimisation, deux facteurs semblent pouvoir être distingués : (a) un premier qui se rapporte au fait d’avoir été victime d’actes violents (5 items, 25% de la variance) et (b) un deuxième qui se rapporte au fait d’avoir été victime de vols (2 items, 16% de la variance).</p>
</section>
<section id="statistiques-descriptives" class="level2">
<h2 class="anchored" data-anchor-id="statistiques-descriptives">Statistiques descriptives</h2>
<p>Le <a href="#tbl-statdesc" class="quarto-xref">Table&nbsp;1</a> présente la moyenne, l’écart type, le score minimal, le score maximal, la moyenne normative <span class="citation" data-cites="costa1998neo">(<a href="#ref-costa1998neo" role="doc-biblioref">Costa et al., 1998</a>)</span>, l’écart type normatif et le Delta de <span class="citation" data-cites="cohen1992quantitative">Cohen (<a href="#ref-cohen1992quantitative" role="doc-biblioref">1992</a>)</span> auquel nous avons associé un test <em>t</em> (le seuil de significativité du test <em>t</em> est de .001 qui est le seuil .05 corrigé par la formule de Bonferroni pour 40 tests) pour chacune de nos variables. La lettre O indique que la différence est significative et la lettre N indique qu’elle ne l’est pas.</p>
<div class="cell">
<div id="tbl-statdesc" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-statdesc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Statistiques descriptives des variables du NEO PI-R et du questionnaire de délinquance auto-révélée pour 112 adolescents
</figcaption>
<div aria-describedby="tbl-statdesc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Score brut moyen</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Ecart-type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Min.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Max.</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Norme m</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Norme ET</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Delta</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p &lt; .001</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">NEVROSISME</td>
<td style="text-align: right;">96.56</td>
<td style="text-align: right;">22.07</td>
<td style="text-align: right;">51</td>
<td style="text-align: right;">144</td>
<td style="text-align: right;">92.25</td>
<td style="text-align: right;">23.19</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="even">
<td style="text-align: left;">N1&nbsp;: Anxiété</td>
<td style="text-align: right;">16.90</td>
<td style="text-align: right;">5.43</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">17.80</td>
<td style="text-align: right;">5.44</td>
<td style="text-align: right;">-0.17</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N2&nbsp;: Colère-Hostilité</td>
<td style="text-align: right;">15.46</td>
<td style="text-align: right;">4.79</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">14.35</td>
<td style="text-align: right;">5.22</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="even">
<td style="text-align: left;">N3&nbsp;: Dépression</td>
<td style="text-align: right;">16.46</td>
<td style="text-align: right;">5.71</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">15.36</td>
<td style="text-align: right;">5.59</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N4&nbsp;: Timidité sociale</td>
<td style="text-align: right;">16.60</td>
<td style="text-align: right;">4.52</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">15.95</td>
<td style="text-align: right;">4.73</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="even">
<td style="text-align: left;">N5&nbsp;: Impulsivité</td>
<td style="text-align: right;">17.70</td>
<td style="text-align: right;">3.99</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">16.89</td>
<td style="text-align: right;">4.50</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N6&nbsp;: Vulnérabilité</td>
<td style="text-align: right;">13.45</td>
<td style="text-align: right;">5.04</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">11.90</td>
<td style="text-align: right;">4.92</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="even">
<td style="text-align: left;">EXTRAVERSION</td>
<td style="text-align: right;">115.12</td>
<td style="text-align: right;">18.08</td>
<td style="text-align: right;">67</td>
<td style="text-align: right;">156</td>
<td style="text-align: right;">110.02</td>
<td style="text-align: right;">18.33</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E1&nbsp;: Chaleur</td>
<td style="text-align: right;">22.71</td>
<td style="text-align: right;">4.21</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">22.43</td>
<td style="text-align: right;">4.41</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="even">
<td style="text-align: left;">E2&nbsp;: Grégarité</td>
<td style="text-align: right;">18.95</td>
<td style="text-align: right;">5.59</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">17.38</td>
<td style="text-align: right;">5.42</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E3&nbsp;: Assertivité</td>
<td style="text-align: right;">14.46</td>
<td style="text-align: right;">4.40</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">14.45</td>
<td style="text-align: right;">4.63</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="even">
<td style="text-align: left;">E4&nbsp;: Activité</td>
<td style="text-align: right;">17.76</td>
<td style="text-align: right;">4.19</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">19.04</td>
<td style="text-align: right;">4.43</td>
<td style="text-align: right;">-0.30</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E5&nbsp;: Recherche de sensation</td>
<td style="text-align: right;">20.13</td>
<td style="text-align: right;">4.57</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">16.60</td>
<td style="text-align: right;">4.74</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">E6&nbsp;: Émotions positives</td>
<td style="text-align: right;">21.12</td>
<td style="text-align: right;">4.48</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">20.11</td>
<td style="text-align: right;">4.81</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OUVERTURE</td>
<td style="text-align: right;">108.38</td>
<td style="text-align: right;">17.61</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">152</td>
<td style="text-align: right;">116.53</td>
<td style="text-align: right;">19.07</td>
<td style="text-align: right;">-0.43</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">O1&nbsp;: Rêveries</td>
<td style="text-align: right;">19.49</td>
<td style="text-align: right;">5.10</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">18.82</td>
<td style="text-align: right;">5.16</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O2&nbsp;: Esthétique</td>
<td style="text-align: right;">17.71</td>
<td style="text-align: right;">6.80</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">18.76</td>
<td style="text-align: right;">5.69</td>
<td style="text-align: right;">-0.17</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="even">
<td style="text-align: left;">O3&nbsp;: Sentiments</td>
<td style="text-align: right;">20.01</td>
<td style="text-align: right;">3.64</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">21.06</td>
<td style="text-align: right;">3.97</td>
<td style="text-align: right;">-0.28</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O4&nbsp;: Actions</td>
<td style="text-align: right;">15.55</td>
<td style="text-align: right;">3.90</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">17.36</td>
<td style="text-align: right;">3.86</td>
<td style="text-align: right;">-0.47</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">O5&nbsp;: Idées</td>
<td style="text-align: right;">16.95</td>
<td style="text-align: right;">5.39</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">19.46</td>
<td style="text-align: right;">5.22</td>
<td style="text-align: right;">-0.47</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O6&nbsp;: Valeurs</td>
<td style="text-align: right;">19.01</td>
<td style="text-align: right;">2.95</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">21.07</td>
<td style="text-align: right;">3.75</td>
<td style="text-align: right;">-0.62</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">AGREABILITE</td>
<td style="text-align: right;">113.80</td>
<td style="text-align: right;">20.07</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">167</td>
<td style="text-align: right;">121.19</td>
<td style="text-align: right;">16.77</td>
<td style="text-align: right;">-0.40</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A1&nbsp;: confiance</td>
<td style="text-align: right;">16.62</td>
<td style="text-align: right;">4.31</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">17.61</td>
<td style="text-align: right;">5.36</td>
<td style="text-align: right;">-0.21</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="even">
<td style="text-align: left;">A2&nbsp;: Droiture</td>
<td style="text-align: right;">18.88</td>
<td style="text-align: right;">5.76</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">20.28</td>
<td style="text-align: right;">5.06</td>
<td style="text-align: right;">-0.26</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A3&nbsp;: Altruisme</td>
<td style="text-align: right;">22.80</td>
<td style="text-align: right;">4.30</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">23.05</td>
<td style="text-align: right;">3.64</td>
<td style="text-align: right;">-0.06</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="even">
<td style="text-align: left;">A4&nbsp;: Compliance</td>
<td style="text-align: right;">16.01</td>
<td style="text-align: right;">6.08</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">52</td>
<td style="text-align: right;">17.70</td>
<td style="text-align: right;">4.64</td>
<td style="text-align: right;">-0.32</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A5&nbsp;: Modestie</td>
<td style="text-align: right;">18.86</td>
<td style="text-align: right;">5.20</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">20.72</td>
<td style="text-align: right;">4.27</td>
<td style="text-align: right;">-0.39</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">A6&nbsp;: Sensibilité</td>
<td style="text-align: right;">20.63</td>
<td style="text-align: right;">3.59</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">21.84</td>
<td style="text-align: right;">3.70</td>
<td style="text-align: right;">-0.33</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CONSCIENCE</td>
<td style="text-align: right;">101.64</td>
<td style="text-align: right;">19.29</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">159</td>
<td style="text-align: right;">115.89</td>
<td style="text-align: right;">20.34</td>
<td style="text-align: right;">-0.72</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">C1&nbsp;: Compétence</td>
<td style="text-align: right;">17.51</td>
<td style="text-align: right;">4.02</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">19.29</td>
<td style="text-align: right;">3.84</td>
<td style="text-align: right;">-0.45</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C2&nbsp;: Ordre</td>
<td style="text-align: right;">16.14</td>
<td style="text-align: right;">4.65</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">18.30</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">-0.45</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">C3&nbsp;: Sens du devoir</td>
<td style="text-align: right;">19.21</td>
<td style="text-align: right;">4.09</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">22.90</td>
<td style="text-align: right;">4.05</td>
<td style="text-align: right;">-0.91</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C4&nbsp;: Recherche de réussite</td>
<td style="text-align: right;">18.20</td>
<td style="text-align: right;">4.19</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">19.10</td>
<td style="text-align: right;">4.42</td>
<td style="text-align: right;">-0.21</td>
<td style="text-align: left;">N</td>
</tr>
<tr class="even">
<td style="text-align: left;">C5&nbsp;: Autodiscipline</td>
<td style="text-align: right;">16.82</td>
<td style="text-align: right;">5.18</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">19.38</td>
<td style="text-align: right;">4.99</td>
<td style="text-align: right;">-0.50</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C6&nbsp;: Délibération</td>
<td style="text-align: right;">13.76</td>
<td style="text-align: right;">4.26</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">16.92</td>
<td style="text-align: right;">4.79</td>
<td style="text-align: right;">-0.52</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">NPM</td>
<td style="text-align: right;">12.69</td>
<td style="text-align: right;">3.84</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">8.93</td>
<td style="text-align: right;">4.18</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PPM</td>
<td style="text-align: right;">17.63</td>
<td style="text-align: right;">3.57</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">20.72</td>
<td style="text-align: right;">4.01</td>
<td style="text-align: right;">-0.82</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">INC</td>
<td style="text-align: right;">8.70</td>
<td style="text-align: right;">3.42</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">6.35</td>
<td style="text-align: right;">2.89</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Antisocialité</td>
<td style="text-align: right;">255.96</td>
<td style="text-align: right;">35.78</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">339</td>
<td style="text-align: right;">236.60</td>
<td style="text-align: right;">31.32</td>
<td style="text-align: right;">0.58</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">Psychopathie</td>
<td style="text-align: right;">295.63</td>
<td style="text-align: right;">37.19</td>
<td style="text-align: right;">214</td>
<td style="text-align: right;">384</td>
<td style="text-align: right;">279.70</td>
<td style="text-align: right;">31.33</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: left;">O</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Pour les 35 variables du NEO PI-R, les normes sont celles du manuel français officiel <span class="citation" data-cites="costa1998neo">(<a href="#ref-costa1998neo" role="doc-biblioref">Costa et al., 1998</a>)</span>. Pour les scores d’antisocialité et de psychopathie, les normes sont celles de <span class="citation" data-cites="miller2008utilisation">Miller et al. (<a href="#ref-miller2008utilisation" role="doc-biblioref">2008</a>)</span> et <span class="citation" data-cites="miller2001structural">Miller &amp; Lynam (<a href="#ref-miller2001structural" role="doc-biblioref">2001</a>)</span>. Pour les échelles de validité NPM, PPM et INC, les normes sont celles de Schinka &amp; Kremer (1997) et Schinka (2011). Notons d’emblée que ces normes ont été établies sur des populations adultes, parfois américaines alors que notre groupe est composé d’adolescents francophones.</p>
<p>Pour les 35 variables du NEO PI-R, 14 sont significativement différentes des normes. D’une manière générale, les adolescents de notre groupe apparaissent comme étant moins consciencieux, moins ouverts et moins agréables que les adultes. Pour les variables d’antisocialité (<em>m</em> = 255.96) et de psychopathie (<em>m</em> = 295.63), elles sont significativement supérieures à la norme. Les trois échelles de validité sont également significativement différentes des normes : la présentation négative (NPM) est supérieure, la présentation positive est inférieure, la tendance à l’incohérence (INC) est supérieure.</p>
<p>La <a href="#fig-crimino" class="quarto-xref">Figure&nbsp;1</a> présente les distributions des trois échelles criminologiques que nous avons créées.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-crimino" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-crimino-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-crimino-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-crimino-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Distributions des trois échelles criminologiques
</figcaption>
</figure>
</div>
</div>
</div>
<p>Les trois échelles criminologiques présentent des distributions quelque peu différentes. Certains participants n’ont rapporté aucun problème de type criminologique : 9.8% pour <em>problèmes</em>, 43.8% pour <em>faits de délinquance</em> et 61.6% pour <em>faits de victimisation</em>. Les deux dernières variables présentent donc une asymétrie gauche.</p>
<p>Existe-t-il des différences entre les garçons et les filles pour les trois variables criminologiques ? La réponse est non pour <em>problèmes</em> (<em>U</em> de Mann-Whitney = 1484, <em>p</em> = .80), non pour <em>faits de délinquance</em> (<em>U</em> = 1203, <em>p</em> = .06) et non pour <em>faits de victimisation</em> (<em>U</em> = 1518, <em>p</em> = .95). Concernant faits de délinquance, nous constatons que toutes les filles ont un score égal à 0. Nous avons décidé d’effectuer les traitements statistiques sur le groupe entier, sans différencier les garçons des filles. Concernant les deux variables d’antisocialité et de psychopathie du NEO PI-R, les filles obtiennent des scores moyens significativement inférieurs à ceux des garçons (<em>t</em> = 3.05, <em>p</em> = .003 pour <em>antisocialité</em> et <em>t</em> = 3.95, <em>p</em> &lt; .001 pour <em>psychopathie</em>). Leurs scores moyens aux échelles de validité de Schinka sont quant à eux similaires.</p>
<div class="cell">
<div id="tbl-problemes" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-problemes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Fréquences des problèmes auto-révélés par les 112 adolescents
</figcaption>
<div aria-describedby="tbl-problemes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Problème</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Problèmes avec vos parents</td>
<td style="text-align: right;">71</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brouille ou dispute</td>
<td style="text-align: right;">66</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mauvais résultats école</td>
<td style="text-align: right;">65</td>
</tr>
<tr class="even">
<td style="text-align: left;">Problèmes avec vos amis</td>
<td style="text-align: right;">60</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Accident ou blessure</td>
<td style="text-align: right;">51</td>
</tr>
<tr class="even">
<td style="text-align: left;">Perte d’argent ou d’autres objets de valeur</td>
<td style="text-align: right;">48</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Objets ou vêtements abîmés</td>
<td style="text-align: right;">47</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hospitalisé ou admis aux urgences</td>
<td style="text-align: right;">46</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Problèmes avec vos professeurs</td>
<td style="text-align: right;">26</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bagarre</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Victime d’un vol</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rapport sexuel non protégé</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rapport sexuel que vous regrettez le lendemain</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Problèmes avec la police</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Le <a href="#tbl-problemes" class="quarto-xref">Table&nbsp;2</a> reprend les fréquences des problèmes rencontrés par les adolescents de notre échantillon. Les trois problèmes les plus fréquents sont : avec les parents (71% des adolescents), des brouilles ou des disputes (66%) et des mauvais résultats à l’école (65%).</p>
<div class="cell">
<div id="tbl-delinq" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-delinq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Fréquences des faits de délinquance auto-révélés (au moins 1 fois) par les 111 adolescents
</figcaption>
<div aria-describedby="tbl-delinq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Fait de délinquance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Pris quelque chose dans une boutique sans le payer</td>
<td style="text-align: right;">27</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abîmé exprès du matériel de l’école</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Abîmé exprès des biens publics ou privés</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pris part à une bagarre où un groupe de vos amis était confronté à un autre groupe</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Été impliqué(e) à une bagarre à l’école ou au travail</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Blessé quelqu’un suffisamment pour qu’il ait besoin de bandages ou d’un docteur</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fait partie d’un groupe persécutant un individu</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Provoqué une bagarre avec un autre individu</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fait partie d’un groupe commençant une bagarre avec un autre groupe</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mis exprès le feu aux affaires de quelqu’un d’autre</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fait partie d’un groupe blessant physiquement un individu</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Volé quelque chose d’une valeur de 15€ ou plus</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Vendu des objets volés</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Eu des problèmes avec la police à cause de quelque chose que vous aviez fait</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Frappé un de vos professeurs</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Entré par effraction quelque part pour voler</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Utilisé une arme de quelque sorte pour obtenir quelque chose de quelqu’un</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Le <a href="#tbl-delinq" class="quarto-xref">Table&nbsp;3</a><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> reprend les fréquences des faits de délinquance prétendument commis par les adolescents de notre échantillon. Les trois faits de délinquance les plus fréquents sont : le vol (27%), le vandalisme scolaire (14%) et le vandalisme public (14%).</p>
<div class="cell">
<div id="tbl-victimo" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-victimo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Fréquences des faits de victimisation auto-révélés (au moins 1 fois) par les 112 adolescents
</figcaption>
<div aria-describedby="tbl-victimo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Fait de victimisation</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Quelque chose vous appartenant a été abîmé exprès</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="even">
<td style="text-align: left;">Quelqu’un est entré par effraction chez vous pour voler quelque chose</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Été victime de vol pour une valeur de 15€ ou plus</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fait partie d’un groupe qui a été attaqué par un autre groupe</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Été impliqué(e) dans une bagarre par quelqu’un</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Été personnellement persécuté(e) par tout un groupe</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Été blessé(e) physiquement par tout un groupe</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Acheté des objets volés</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Le <a href="#tbl-victimo" class="quarto-xref">Table&nbsp;4</a> reprend les fréquences des faits de victimisation prétendument subis par les adolescents de notre échantillon. Les trois faits de victimisation les plus fréquents sont : les objets personnels abîmés (15%), les vols avec effraction (11%) et un vol de plus de 15 Euros (10%).</p>
</section>
<section id="liens-entre-les-variables-psychologiques-et-criminologiques" class="level2">
<h2 class="anchored" data-anchor-id="liens-entre-les-variables-psychologiques-et-criminologiques">Liens entre les variables psychologiques et criminologiques</h2>
<p>La variable <em>problèmes</em> est significativement corrélée avec deux des cinq grands domaines du NEO PI-R : avec le caractère Agréable (<em>r</em> = -.23, <em>p</em> = .01) et avec le caractère Consciencieux (<em>r</em> = -.19, <em>p</em> = .04). Elle est également corrélée avec les variables d’antisocialité (<em>r</em> = .28, <em>p</em> = .003) et de psychopathie (<em>r</em> = .21, <em>p</em> = .03). Elle est également corrélée avec quatre facettes du NEO PI-R : avec A2 (<em>r</em> = -.32, <em>p</em> = .001), A4 (<em>r</em> = -.28, p = .002), C2 (<em>r</em> = -.22, <em>p</em> = .02) et C6 (<em>r</em> = -.19, <em>p</em> = .04). La <a href="#fig-scatterplot1" class="quarto-xref">Figure&nbsp;2</a> représente le lien entre le score d’antisocialité du NEO PI-R et le nombre de problèmes rapportés par les participants.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scatterplot1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scatterplot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-scatterplot1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scatterplot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Lien entre le score d’antisocialité du NEO PI-R et le score auto-rapporté de problèmes
</figcaption>
</figure>
</div>
</div>
</div>
<p>La droite de régression (en trait plein) indique une lien positif entre les deux variables, confirmant la corrélation significative pointée précédemment. La courbe loess permet quant à elle de constater que des scores inférieurs à la moyenne ne semble pas avoir d’impact sur le nombre de problèmes alors que les scores supérieurs à la moyenne induisent une augmentation croissante et régulière de problèmes.</p>
<p>La variable <em>faits de délinquance</em> est significativement corrélée avec deux des cinq grands domaines du NEO PI-R : avec le caractère Agréable (<em>r</em> = -.24, <em>p</em> = .01) et avec le caractère Consciencieux (<em>r</em> = -.30, <em>p</em> = .001). Elle est également corrélée avec les variables d’antisocialité (<em>r</em> = .36, <em>p</em> &lt; .001) et de psychopathie (<em>r</em> = .31, <em>p</em> &lt; .001). Elle est également corrélée avec dix facettes du NEO PI-R : E3 (<em>r</em> = .27, <em>p</em> = .006), A2 (<em>r</em> = -.26, <em>p</em> = .006), A3 (<em>r</em> = -.19, <em>p</em> = .05), A4 (<em>r</em> = -.21, <em>p</em> = .03), A5 (<em>r</em> = -.19, <em>p</em> = .05), C1 (<em>r</em> = -27, <em>p</em> = .005), C2 (<em>r</em> = -.20, <em>p</em> = .04), C3 (<em>r</em> = -.36, <em>p</em> &lt; .001), C5 (<em>r</em> = -.24, <em>p</em> = .012) et C6 (<em>r</em> = -.28, <em>p</em> = .003).</p>
<p>La <a href="#fig-scatterplot2" class="quarto-xref">Figure&nbsp;3</a> représente graphiquement le lien entre la variable d’antisocialité au NEO PI-R et le nombre de problèmes de délinquance.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scatterplot2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scatterplot2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-scatterplot2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scatterplot2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Lien entre le score d’antisocialité du NEO PI-R et le score auto-rapporté de délinquance
</figcaption>
</figure>
</div>
</div>
</div>
<p>Puisque <em>faits de délinquance</em> est la variable qui nous intéresse le plus dans cette étude, nous avons testé plusieurs modèles de régression linéaire qui permettent de la prédire à partir des facettes du NEO PI-R selon. Pour chaque modèle de régression, nous avons introduit chaque prédicteur dans l’ordre de leur taille de corrélation (en l’occurence C3 en premier et A3 en dernier). Lorsque le nouveau prédicteur n’était pas significatif, nous avons introduit le suivant jusqu’à ce qu’aucun prédicteur ne soit significatif. Nous avons ensuite introduit les interactions entre chaque prédicteur retenu, ne conservant que les interactions elles-mêmes significatives. Selon cette méthode, le modèle qui explique le mieux sa variance est le modèle présenté dans le <a href="#tbl-lm01" class="quarto-xref">Table&nbsp;5</a>.</p>
<div class="cell">
<div id="tbl-lm01" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-lm01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Table de régression prédisant les problèmes de délinquance
</figcaption>
<div aria-describedby="tbl-lm01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">conf.int</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: left;">1.77</td>
<td style="text-align: left;">[1.22, 2.31]</td>
<td style="text-align: left;">6.40</td>
<td style="text-align: left;">106</td>
<td style="text-align: left;">&lt; .001</td>
</tr>
<tr class="even">
<td style="text-align: left;">C3</td>
<td style="text-align: left;">-0.14</td>
<td style="text-align: left;">[-0.28, 0.00]</td>
<td style="text-align: left;">-2.00</td>
<td style="text-align: left;">106</td>
<td style="text-align: left;">.048</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E3</td>
<td style="text-align: left;">0.17</td>
<td style="text-align: left;">[0.04, 0.30]</td>
<td style="text-align: left;">2.56</td>
<td style="text-align: left;">106</td>
<td style="text-align: left;">.012</td>
</tr>
<tr class="even">
<td style="text-align: left;">A2</td>
<td style="text-align: left;">-0.10</td>
<td style="text-align: left;">[-0.20, 0.01]</td>
<td style="text-align: left;">-1.85</td>
<td style="text-align: left;">106</td>
<td style="text-align: left;">.067</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E3xA2</td>
<td style="text-align: left;">-0.02</td>
<td style="text-align: left;">[-0.05, 0.00]</td>
<td style="text-align: left;">-2.04</td>
<td style="text-align: left;">106</td>
<td style="text-align: left;">.044</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Ce modèle est prédit de manière significative la variable de problèmes de délinquance : <span class="math inline">\(R^2 = .19\)</span>, <span class="math inline">\(F(4, 106) = 6.03\)</span>, <span class="math inline">\(p &lt; .001\)</span>.</p>
<p>Pour ce modèle qui tient compte de l’interaction entre E3 et A2, <em>R</em> = .43 (<em>p</em> &lt; .001). Il explique donc 19% de la variance, ce qui est légèrement supérieur à la prédictibilité des variables d’antisocialité et de psychopathie. Ce modèle propose de concevoir les tendances à l’assertivité, au manque de responsabilité et au manque de droiture comme susceptibles d’aller de pair avec des passages à l’acte transgressif. L’interaction incluse dans le modèle amène une précision : la tendance à l’assertivité n’est vraiment prédictrice de transgression que lorsque la droiture est basse. A2 semble donc constituer le “terreau moral” susceptible d’induire des comportements antisociaux.</p>
<p>La variable <em>faits de victimisation</em> n’est pas significativement corrélée avec les cinq grands domaines du NEO PI-R ni avec les variables d’antisocialité ni de psychopathie. Elle est toutefois corrélée avec une facette du NEO PI-R : E3 (<em>r</em> = .21, <em>p</em> = .02).</p>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>Nos premiers résultats permettent de constater que l’échantillon que nous avons récolté diffère sensiblement des échantillons normatifs. En effet, les adolescents de notre échantillon seraient moins consciencieux, moins ouverts et moins agréables que les adultes. En outre, leurs scores aux échelles d’antisocialité et de psychopathie du NEO PI-R sont également significativement supérieurs à ceux des adultes. Selon <span class="citation" data-cites="rolland2004evaluation">Rolland (<a href="#ref-rolland2004evaluation" role="doc-biblioref">2004, p. 79</a>)</span>, c’est entre 18 et 30 ans que les scores A et C augmentent sensiblement. Remarquons au passage que ces deux variables correspondent justement au pattern [A- C-] que <span class="citation" data-cites="miller2001structural">Miller &amp; Lynam (<a href="#ref-miller2001structural" role="doc-biblioref">2001</a>)</span> ont associé à un ensemble de conduites inadaptatives, notamment à la délinquance. Concernant les variables d’antisocialité et de psychopathie, nous n’avons pas trouvé d’informations concernant l’effet de l’âge sur elles. Il est dès lors difficile d’expliquer ce résultat. Concernant les échelles de validité de <span class="citation" data-cites="schinka1997research">Schinka et al. (<a href="#ref-schinka1997research" role="doc-biblioref">1997</a>)</span>, elles semblent indiquer que les adolescents de notre échantillon ont eu tendance à présenter une image plus négative et moins positive mais également à répondre de manière plus incohérente que l’échantillon normatif. Les deux premiers indices de validité laissent penser que les adolescents n’ont pas altéré leurs réponses dans le sens de la désirabilité sociale. L’indice d’incohérence invite à la prudence. En effet, il est possible que certains adolescents aient eu des difficultés à comprendre certaines questions du NEO PI-R. Nous ne pouvons malheureusement pas corriger ce biais de compréhension qui ne concerne probablement que certaines questions plus difficiles que les autres. Selon nous, ces résultats n’invalident pas les résultats pris dans leur ensemble.</p>
<p>Nos variables criminologiques apportent une information sur la fréquence des comportements transgressifs révélés par les adolescents de notre échantillon. Neuf adolescents sur dix rapportent au moins un problème (même mineur) avec les règles. Ce constat n’est pas récent. Selon <span class="citation" data-cites="junger1994delinquency">Junger-Tas (<a href="#ref-junger1994delinquency" role="doc-biblioref">1994</a>)</span>, plus de 20% des jeunes belges interrogés, 27% des jeunes américains et 21% des jeunes espagnols mentionnaient avoir commis au moins un acte de délinquance durant l’année précédente. Sur une population similaire à la nôtre, <span class="citation" data-cites="gavray2007delinquance">Gavray &amp; Vettenburg (<a href="#ref-gavray2007delinquance" role="doc-biblioref">2007</a>)</span> ont obtenu les fréquences de comportements déviants pour 4829 élèves dans 95 écoles secondaires. Les trois plus fréquents étaient le resquillage (25.5%), le vol (23.4%) et le vandalisme (20.7%). Ces délits concernent des objets, soit volés soit abîmés sciemment. Le fait délictueux le plus fréquemment commis sur des personnes est celui d’une bagarre en groupe (20%).</p>
<p>La formule de régression linéaire que nous avons mise en évidence est la suivante :</p>
<p><span class="math display">\[
Délinquance = E3 - C3 - A2 - E3xA2
\]</span> Elle présente une taille d’effet relativement élevée pour prédire les actes de délinquance auto-révélés à partir de variables psychologiques. Il s’agit du modèle le plus économique que nous ayons trouvé, c’est-à-dire qu’il n’inclut pas d’autre facettes de personnalité qui partagent une partie de leur variance avec E3, C3 ou A2. Que nous apprend cette équation ? Que trois des cinq domaines de la personnalité semblent devoir être pris en considération pour évaluer d’éventuels comportements antisociaux. Il existe d’abord une facette que l’on pourrait qualifier de morale car A2 renseigne sur la droiture et la tendance à manipuler autrui à ses propres fins. Cette prédisposition morale ne semble trouver d’expression visible que lorsque l’individu fait preuve de capacités de meneur et fait montre d’<em>assertivité</em> (E3). La tendance à mener les groupes sans s’embarrasser de considérations morales semblent ouvrir la porte à des agissements transgressifs. Enfin, le <em>laxisme</em> vis-à-vis des tâches imposées (C3) renvoient également à une fragilité morale mais également à une tendance à abandonner rapidement lorsque l’individu est confronté à des obligations. Il existe donc au moins trois sphères psychologiques en lien avec la tendance antisociale : (a) une sphère <em>morale</em>, (b) une sphère <em>relationnelle</em> et (c) une sphère <em>comportementale</em>. La tendance antisociale est donc un concept complexe. D’un point de vue clinique, ce profil semble correspondre à des adolescents masculins peu persévérants dans l’accomplissement des tâches qui leur sont demandées, capables de prendre l’ascendance dans certains groupes et qui entretiennent des relations plutôt cyniques avec les autres, des relations qui reposent sur l’idée de manipulation. Il est probable que ces jeunes refusent (plus ou moins explicitement) les contraintes extérieures (par exemple de leurs parents ou des professeurs) et exploitent la crédulité supposée des autres pour exercer un certain pouvoir sur eux. Peut-être tentent-ils de quitter la position passive imposée par la famille ou l’école afin d’occuper une <em>position active</em> vis-à-vis de leurs camarades. Rappelons ici que notre échantillon n’est pas un échantillon pathologique : à notre connaissance, aucun adolescent du groupe n’a fait l’objet d’un diagnostic de personnalité antisociale ou de psychopathie. Nous évoquons donc ici des tendances psychologiques susceptibles de sous-tendre des comportements transgressifs divers (selon nous, il n’y avait aucun meurtrier ou violeur dans notre échantillon). Nous souhaitons défendre une approche dimensionnelle et nuancée tant pour la personnalité (les traits de personnalité varient sur un continuum) que pour la tendance antisociale (il existe des comportements transgressifs de faible gravité et d’autres bien plus graves dans une société donnée). L’équation de régression que nous proposons s’applique à une population d’adolescents sans troubles psychiques connus et en situation scolaire.</p>
<p><span class="citation" data-cites="gavray2007delinquance">Gavray &amp; Vettenburg (<a href="#ref-gavray2007delinquance" role="doc-biblioref">2007, p. 56</a>)</span> ont également administré un questionnaire de délinquance auto-révélée à des adolescents belges à l’école mais avec d’autres variables les décrivant. Elles proposent également une analyse de régression multiple permettant de mettre en évidence les variables qui prédisent le mieux le niveau de délinquance du jeune. Par ordre de priorité, il s’agit (a) d’une relation médiocre du jeune avec les enseignants, (b) du manque d’attention de la famille à l’égard du jeune, (c) du sexe masculin, (d) de l’enseignement technique ou professionnel, (e) de l’implication du jeune à l’école et (f) de sa satisfaction à l’école. Ces six variables expliquent 30% de la variance du niveau de délinquance, ce qui est relativement élevé. Notre équation de régression n’est pas identique à celle de <span class="citation" data-cites="gavray2007delinquance">Gavray &amp; Vettenburg (<a href="#ref-gavray2007delinquance" role="doc-biblioref">2007</a>)</span>. Nous pouvons toutefois supposer qu’elles partagent des liens complexes. En effet, il est possible que le manque d’autodiscipline aille de pair avec un manque d’implication et de satisfaction de l’adolescent dans les tâches scolaires. Cela peut induire une réaction négative de certains enseignants perçue par l’adolescent qui entretient dès lors une moins bonne relation avec ces enseignants. Cette mauvaise relation est susceptible d’induire une tonalité cynique aux autres relations. L’adolescent pourrait alors avoir tendance à trouver une satisfaction dans d’autres domaines (par exemple le vol) en prenant l’ascendant sur d’autres personnes. Il existe toujours une relation complexe et réciproque entre les événements auxquels un adolescent est confronté (par exemple un échec scolaire) et le vécu émotionnel (par exemple, la tristesse ou la colère).</p>
<p>En criminologie, le lien entre la personnalité et la délinquance a déjà été abordé à plusieurs reprises. Par exemple, <span class="citation" data-cites="gottfredson1990general">Gottfredson &amp; Hirschi (<a href="#ref-gottfredson1990general" role="doc-biblioref">1990</a>)</span> ont élaboré une théorie générale du crime selon laquelle les individus qui disposent d’un autocontrôle élevé se conforment à la loi (car ils y voient un intérêt ultérieur) alors que les individus qui disposent d’un autocontrôle bas commettent des délits (qui leur procurent une satisfaction immédiate). Nos résultats confirment un lien significatif entre le sens du devoir (C3) et l’autodiscipline (C5) conscientes, si on peut les qualifier ainsi, et les actes de délinquance auto-révélée (<em>r</em> = - .26, <em>p</em> = .007) mais pas avec les variables d’auto-contrôle sur leur versant affectif (<em>r</em> = .04 pour l’impulsivité N5 et <em>r</em> = -. 01 pour la vulnérabilité N6, toutes deux non significatives). Un autre criminologue, <span class="citation" data-cites="agnew2020contribution">Agnew (<a href="#ref-agnew2020contribution" role="doc-biblioref">2020</a>)</span>, postule l’existence d’une tension psychologique entre les réalisations d’un individu et ses aspirations. Cette tension ou des facteurs de stress externes augmentent la probabilité d’apparition d’émotions négatives comme la colère et la frustration. Ces émotions sont alors susceptibles de créer une pression psychologique qui serait évacuée par le biais de comportements déviants, notamment la criminalité <span class="citation" data-cites="chamayou2012actualites">(<a href="#ref-chamayou2012actualites" role="doc-biblioref">Chamayou, 2012, p. 293</a>)</span>. La contribution majeure d’Agnew est d’insister sur l’affect de colère. Celui-ci résulterait d’une frustration sociale importante ou récurrente et mènerait à la commission d’acte de violence et à des ruptures sociales. Les résultats de notre étude ne confirment pas l’importance de l’affect de colère sur les actes de délinquance auto-révélée (<em>r</em> = .07, <em>p</em> = .46). Ils invitent à approfondir le lien complexe qui unit la tendance à répondre adéquatement aux tâches imposées par les autres, le cynisme envers les pairs et la tendance à prendre l’ascendant sur ceux-ci. Les limites de notre étude découlent principalement de notre échantillon relativement petit et composé d’adolescents suivant une scolarité classique. Les actes de délinquance graves (meurtres, viols, terrorisme, séquestrations, etc.) n’ont pas été abordés. Il serait dès lors hasardeux de généraliser les résultats à une population adulte délinquante. Avec <span class="citation" data-cites="moffitt1993adolescence">Moffitt (<a href="#ref-moffitt1993adolescence" role="doc-biblioref">1993</a>)</span>, <span class="citation" data-cites="farrington2007childhood">Farrington (<a href="#ref-farrington2007childhood" role="doc-biblioref">2007</a>)</span> et <span class="citation" data-cites="born2017psychologie">Born &amp; Glowacz (<a href="#ref-born2017psychologie" role="doc-biblioref">2017</a>)</span>, nous soutenons toutefois l’idée que la délinquance est un processus progressif qui débute par la commission d’actes de faible gravité et qui est susceptible de mener à d’autres actes plus graves. S’intéresser aux facteurs psychologiques accompagnant l’entrée dans la délinquance nous paraît dès lors garder sa pertinence.</p>



</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">Les références</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-agnew2020contribution" class="csl-entry" role="listitem">
Agnew, R. (2020). The contribution of social-psychological strain theory to the explanation of crime and delinquency. In <em>The legacy of anomie theory</em> (p. 113‑137). Routledge.
</div>
<div id="ref-american1994dsm" class="csl-entry" role="listitem">
APA. (1994). <em>DSM-IV: Diagnostic and statistical manual of mental disorders</em>.
</div>
<div id="ref-american2013dsm" class="csl-entry" role="listitem">
APA. (2013). <em>DSM-5: Diagnostic and Statistical Manual of Mental Disorders</em>.
</div>
<div id="ref-born2007isrd" class="csl-entry" role="listitem">
Born, M., &amp; Glowacz, F. (2007). <em>ISRD technical report. Wallonie Belgium</em>.
</div>
<div id="ref-born2017psychologie" class="csl-entry" role="listitem">
Born, M., &amp; Glowacz, F. (2017). <em>Psychologie de la d<span>é</span>linquance</em>. De Boeck Sup<span>é</span>rieur.
</div>
<div id="ref-chamayou2012actualites" class="csl-entry" role="listitem">
Chamayou, J.-L. (2012). Actualit<span>é</span>s sur la th<span>é</span>orie des tensions psychiques et des ph<span>é</span>nom<span>è</span>nes violents en prison. <em>Psychologie fran<span>ç</span>aise</em>, <em>57</em>(4), 291‑303.
</div>
<div id="ref-cohen1992quantitative" class="csl-entry" role="listitem">
Cohen, J. (1992). Quantitative methods in psychology: A power primer. <em>Psychological Bulletin</em>, <em>112</em>, 155‑159.
</div>
<div id="ref-costa1998neo" class="csl-entry" role="listitem">
Costa, P. T., McCrae, R., &amp; Rolland, J.-P. (1998). NEO-PI-R. Inventaire de Personnalit<span>é</span> r<span>é</span>vis<span>é</span>. Adaptation Fran<span>ç</span>aise. <em>Editions du Centre de Psychologie Appliqu<span>é</span>e, Paris</em>.
</div>
<div id="ref-widiger2002personality" class="csl-entry" role="listitem">
Costa, P. T., &amp; Widiger, T. A. (2002). <em>Personality disorders and the five-factor model of personality</em>. APA.
</div>
<div id="ref-decuyper2009validation" class="csl-entry" role="listitem">
Decuyper, M., De Clercq, B., De Bolle, M., &amp; De Fruyt, F. (2009). Validation of FFM PD counts for screening personality pathology and psychopathy in adolescence. <em>Journal of Personality Disorders</em>, <em>23</em>(6), 587‑605.
</div>
<div id="ref-farrington2007childhood" class="csl-entry" role="listitem">
Farrington, D. P. (2007). Childhood risk factors and risk-focused prevention. In <em>The Oxford handbook of criminology</em> (p. 602‑640). Oxford University Press.
</div>
<div id="ref-ferri1893sociologie" class="csl-entry" role="listitem">
Ferri, E. (1893). <em>La sociologie criminelle</em>. Éditeur A. Rousseau.
</div>
<div id="ref-garofalo1888criminologie" class="csl-entry" role="listitem">
Garofalo, R. (1888). <em>La criminologie: <span>é</span>tude sur la nature du crime et la th<span>é</span>orie de la p<span>é</span>nalit<span>é</span></em>. F. Alcan.
</div>
<div id="ref-gavray2007delinquance" class="csl-entry" role="listitem">
Gavray, C., &amp; Vettenburg, N. (2007). La d<span>é</span>linquance juv<span>é</span>nile autor<span>é</span>v<span>é</span>l<span>é</span>e: le cas de la Belgique. <em>Carrefours de l’Education</em>, (2), 53‑72. Consulté à l'adresse <a href="https://www.cairn.info/revue-carrefours-de-l-education-2007-2-page-53.htm">https://www.cairn.info/revue-carrefours-de-l-education-2007-2-page-53.htm</a>
</div>
<div id="ref-gottfredson1990general" class="csl-entry" role="listitem">
Gottfredson, M. R., &amp; Hirschi, T. (1990). <em>A general theory of crime</em>. Stanford University Press.
</div>
<div id="ref-gudonis2008conceptualizing" class="csl-entry" role="listitem">
Gudonis, L. C., Miller, D. J., Miller, J. D., &amp; Lynam, D. R. (2008). Conceptualizing personality disorders from a general model of personality functioning: antisocial personality disorder and the five-factor model. <em>Personality and Mental Health</em>, <em>2</em>(4), 249‑264.
</div>
<div id="ref-jones2011personality" class="csl-entry" role="listitem">
Jones, S. E., Miller, J. D., &amp; Lynam, D. R. (2011). Personality, antisocial behavior, and aggression: A meta-analytic review. <em>Journal of Criminal Justice</em>, <em>39</em>(4), 329‑337.
</div>
<div id="ref-junger1994delinquency" class="csl-entry" role="listitem">
Junger-Tas, J. (1994). Delinquency in thirteen western countries: Some preliminary conclusions. <em>Delinquent behavior among young people in the western world: First results of the international self-report delinquency study</em>, 370‑380.
</div>
<div id="ref-junger2012introduction" class="csl-entry" role="listitem">
Junger-Tas, J., &amp; Marshall. (2012). Introduction to the international self-report study of delinquency (ISRD-2). In <em>The many faces of youth crime: Contrasting theoretical perspectives on juvenile delinquency across countries and cultures</em> (p. 3‑20). Springer.
</div>
<div id="ref-lombroso1876homme" class="csl-entry" role="listitem">
Lombroso, C. (1876). <em>L’homme criminel</em>. Alcan. Paris.
</div>
<div id="ref-lynam2001using" class="csl-entry" role="listitem">
Lynam, D. R., &amp; Widiger, T. A. (2001). Using the five-factor model to represent the DSM-IV personality disorders: an expert consensus approach. <em>Journal of abnormal psychology</em>, <em>110</em>(3), 401.
</div>
<div id="ref-miller2012five" class="csl-entry" role="listitem">
Miller, J. D. (2012). Five-factor model personality disorder prototypes: A review of their development, validity, and comparison to alternative approaches. <em>Journal of Personality</em>, <em>80</em>(6), 1565‑1591.
</div>
<div id="ref-miller2001structural" class="csl-entry" role="listitem">
Miller, J. D., &amp; Lynam, D. (2001). Structural models of personality and their relation to antisocial behavior: A meta-analytic review. <em>Criminology</em>, <em>39</em>(4), 765‑798.
</div>
<div id="ref-miller2008utilisation" class="csl-entry" role="listitem">
Miller, J. D., Lynam, D. R., Pham-Scottez, A., De Clercq, B., Rolland, J.-P., &amp; De Fruyt, F. (2008). Utilisation du mod<span>è</span>le de personnalit<span>é</span> <span>à</span> cinq facteurs (FFM) dans l’<span>é</span>valuation des troubles de la personnalit<span>é</span> du DSM-IV. <em>Annales M<span>é</span>dico-psychologiques, revue psychiatrique</em>, <em>166</em>, 418‑426. Elsevier.
</div>
<div id="ref-moffitt1993adolescence" class="csl-entry" role="listitem">
Moffitt, T. E. (1993). Adolescence-limited and life-course-persistent antisocial behavior: A developmental taxonomy. <em>Psychological Review</em>, <em>100</em>(4), 674‑701.
</div>
<div id="ref-rolland2004evaluation" class="csl-entry" role="listitem">
Rolland, J.-P. (2004). <em>L’<span>é</span>valuation de la personnalit<span>é</span>: Le mod<span>è</span>le en cinq facteurs</em>. Mardaga.
</div>
<div id="ref-samuel2008meta" class="csl-entry" role="listitem">
Samuel, D. B., &amp; Widiger, T. A. (2008). A meta-analytic review of the relationships between the five-factor model and DSM-IV-TR personality disorders: A facet level analysis. <em>Clinical psychology review</em>, <em>28</em>(8), 1326‑1342.
</div>
<div id="ref-schinka2011scoring" class="csl-entry" role="listitem">
Schinka, J. A. (2011). <em>Scoring directions and norms for the research validity scales for the NEO PI-R</em>.
</div>
<div id="ref-schinka1997research" class="csl-entry" role="listitem">
Schinka, J. A., Kinder, B. N., &amp; Kremer, T. (1997). Research validity scales for the NEO–PI–R: Development and initial validation. <em>Journal of Personality Assessment</em>, <em>68</em>(1), 127‑138.
</div>
<div id="ref-westen1998limitations" class="csl-entry" role="listitem">
Westen, D., &amp; Arkowitz-Westen, L. (1998). Limitations of Axis II in diagnosing personality pathology in clinical practice. <em>American journal of Psychiatry</em>, <em>155</em>(12), 1767‑1771.
</div>
<div id="ref-widiger2005diagnostic" class="csl-entry" role="listitem">
Widiger, T. A., &amp; Samuel, D. B. (2005). Diagnostic categories or dimensions? A question for the Diagnostic and statistical manual of mental disorders–. <em>Journal of abnormal psychology</em>, <em>114</em>(4), 494.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Notes de bas de page</h2>

<ol>
<li id="fn1"><p>r signifie que la variable a été renversée (32 - x)<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>r signifie que la variable a été renversée (32 - x)<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>nous avons exclu le participant 20 car il avait indiqué les fréquences maximales pour toutes les questions relatives à la délinquance, ce que nous avons considéré suspect<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section><section class="quarto-appendix-contents" id="quarto-citation"><h2 class="anchored quarto-appendix-heading">Citation</h2><div><div class="quarto-appendix-secondary-label">BibTeX</div><pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@online{thiry2023,
  author = {Thiry, Benjamin and Ponchaux, Stéphanie},
  title = {Comparaison de variables de délinquance auto-révélée avec des
    variables de personnalité selon le modèle en cinq facteurs auprès
    d’adolescents},
  date = {2023-02-23},
  url = {https://benjaminthiry.netlify.app/posts/2023-02-26-delinquancefivefactormodel/},
  langid = {fr}
}
</code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre><div class="quarto-appendix-secondary-label">Veuillez citer ce travail comme suit&nbsp;:</div><div id="ref-thiry2023" class="csl-entry quarto-appendix-citeas" role="listitem">
Thiry, B., &amp; Ponchaux, S. (2023, February 23). Comparaison de
variables de délinquance auto-révélée avec des variables de personnalité
selon le modèle en cinq facteurs auprès d’adolescents. Retrieved from <a href="https://benjaminthiry.netlify.app/posts/2023-02-26-delinquancefivefactormodel/">https://benjaminthiry.netlify.app/posts/2023-02-26-delinquancefivefactormodel/</a>
</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copié");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copié");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/benjaminthiry\.netlify\.app\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>