<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Benjamin Thiry">
<meta name="author" content="Maëva Piolti">
<meta name="description" content="L’International Personality Item Pool (IPIP) propose un questionnaire de personnalité basé sur le modèle en cinq facteurs appelé IPIP NEO 300. La version originale a été créée en langue anglaise et il existe une traduction en français canadien. Notre étude propose une adaptation en français européen pour ce questionnaire. Parmi les 300 items, 26 items ont été considérés comme potentiellement problématiques et ont été soumis à des étudiants de langue maternelle française en dernière année de master en traduction (N = 20). Nous avons retenu les traductions les plus majoritaires afin de proposer une version française adaptée à la population francophone européenne.">

<title>IPIP NEO 300, adapation française européenne – Psychologie et délinquance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b53751a350365c71b6c909e95f209ed1.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-38d94b3cac77cd3e685c79e69241b0ba.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-86ef44f33eb6204f81838d6c66abc062.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>
<link rel="me" href="https://tchafia.be/@ouriagan">
<meta name="fediverse:creator" content="@ouriagan@tchafia.be">
<script>
  document.addEventListener("DOMContentLoaded", () => {
    const listing = document.querySelector(".quarto-listing-container");
    if (listing) {
      listing.classList.add("h-feed");
      const links = listing.querySelectorAll("a");
      links.forEach(link => {
        const article = document.createElement("article");
        article.classList.add("h-entry");
        link.classList.add("u-url");
        article.appendChild(link.cloneNode(true));
        link.replaceWith(article);
      });
    }
  });
</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../benjaminthiry.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Psychologie et délinquance</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Recherche"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Basculer la navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">Qui écrit ce blog ?</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://tchafia.be/@ouriagan"> <i class="bi bi-mastodon" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ouriagan/blog"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Basculer le mode sombre"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">IPIP NEO 300, adapation française européenne</h1>
                  <div>
        <div class="description">
          L’International Personality Item Pool (IPIP) propose un questionnaire de personnalité basé sur le modèle en cinq facteurs appelé IPIP NEO 300. La version originale a été créée en langue anglaise et il existe une traduction en français canadien. Notre étude propose une adaptation en français européen pour ce questionnaire. Parmi les 300 items, 26 items ont été considérés comme potentiellement problématiques et ont été soumis à des étudiants de langue maternelle française en dernière année de master en traduction (N = 20). Nous avons retenu les traductions les plus majoritaires afin de proposer une version française adaptée à la population francophone européenne.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">analyses statistiques</div>
                <div class="quarto-category">psychologie</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Auteur·rice·s</div>
      <div class="quarto-title-meta-contents">
               <p>Benjamin Thiry </p>
               <p>Maëva Piolti </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Date de publication</div>
      <div class="quarto-title-meta-contents">
        <p class="date">12 février 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Sur cette page</h2>
   
  <ul>
  <li><a href="#linternational-personality-item-pool-ipip" id="toc-linternational-personality-item-pool-ipip" class="nav-link active" data-scroll-target="#linternational-personality-item-pool-ipip">L’International Personality Item Pool (IPIP)</a></li>
  <li><a href="#lipip-neo" id="toc-lipip-neo" class="nav-link" data-scroll-target="#lipip-neo">L’IPIP NEO</a>
  <ul class="collapse">
  <li><a href="#validité-de-lipip-neo" id="toc-validité-de-lipip-neo" class="nav-link" data-scroll-target="#validité-de-lipip-neo">Validité de l’IPIP NEO</a></li>
  <li><a href="#problème-de-validation-en-français" id="toc-problème-de-validation-en-français" class="nav-link" data-scroll-target="#problème-de-validation-en-français">Problème de validation en français</a></li>
  </ul></li>
  <li><a href="#objectif-de-notre-étude" id="toc-objectif-de-notre-étude" class="nav-link" data-scroll-target="#objectif-de-notre-étude">Objectif de notre étude</a></li>
  <li><a href="#adaptation-française-de-lipip-neo-300" id="toc-adaptation-française-de-lipip-neo-300" class="nav-link" data-scroll-target="#adaptation-française-de-lipip-neo-300">Adaptation française de l’IPIP NEO 300</a></li>
  <li><a href="#méthode" id="toc-méthode" class="nav-link" data-scroll-target="#méthode">Méthode</a>
  <ul class="collapse">
  <li><a href="#participants" id="toc-participants" class="nav-link" data-scroll-target="#participants">Participants</a></li>
  <li><a href="#matériel" id="toc-matériel" class="nav-link" data-scroll-target="#matériel">Matériel</a></li>
  <li><a href="#procédure" id="toc-procédure" class="nav-link" data-scroll-target="#procédure">Procédure</a>
  <ul class="collapse">
  <li><a href="#etape-1-première-évaluation-par-les-deux-auteurs-de-la-traducion-québecquoise" id="toc-etape-1-première-évaluation-par-les-deux-auteurs-de-la-traducion-québecquoise" class="nav-link" data-scroll-target="#etape-1-première-évaluation-par-les-deux-auteurs-de-la-traducion-québecquoise">Etape 1 : première évaluation par les deux auteurs de la traducion québecquoise</a></li>
  <li><a href="#etape-2-traductions-de-langlais-au-français-par-les-étudiants-en-traduction" id="toc-etape-2-traductions-de-langlais-au-français-par-les-étudiants-en-traduction" class="nav-link" data-scroll-target="#etape-2-traductions-de-langlais-au-français-par-les-étudiants-en-traduction">Etape 2 : traductions de l’anglais au français par les étudiants en traduction</a></li>
  <li><a href="#etape-3-analyse-des-fréquences-de-chaque-proposition-de-traduction" id="toc-etape-3-analyse-des-fréquences-de-chaque-proposition-de-traduction" class="nav-link" data-scroll-target="#etape-3-analyse-des-fréquences-de-chaque-proposition-de-traduction">Etape 3 : analyse des fréquences de chaque proposition de traduction</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#résultats" id="toc-résultats" class="nav-link" data-scroll-target="#résultats">Résultats</a>
  <ul class="collapse">
  <li><a href="#exemple-de-litem-50-work-hard" id="toc-exemple-de-litem-50-work-hard" class="nav-link" data-scroll-target="#exemple-de-litem-50-work-hard">Exemple de l’item 50 : “Work hard”</a></li>
  <li><a href="#items-réévalués" id="toc-items-réévalués" class="nav-link" data-scroll-target="#items-réévalués">Items réévalués</a></li>
  <li><a href="#traduction-française-européenne" id="toc-traduction-française-européenne" class="nav-link" data-scroll-target="#traduction-française-européenne">Traduction française européenne</a></li>
  </ul></li>
  <li><a href="#ipip-neo-300---version-française" id="toc-ipip-neo-300---version-française" class="nav-link" data-scroll-target="#ipip-neo-300---version-française">IPIP NEO 300 - Version française</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ipipneo300.png" class="img-fluid figure-img"></p>
<figcaption>IPIP NEO 300</figcaption>
</figure>
</div>
<section id="linternational-personality-item-pool-ipip" class="level1">
<h1>L’International Personality Item Pool (IPIP)</h1>
<p>Dans le domaine de l’investigation psychométrique de la personnalité, <span class="citation" data-cites="goldberg_broad-bandwidth_1999">Goldberg (<a href="#ref-goldberg_broad-bandwidth_1999" role="doc-biblioref">1999</a>)</span> souligne que la plupart des instruments évaluant la personnalité appartiennent à un auteur ou à un éditeur et que les items sont protégés par le copyright, ce qui empêche les scientifiques de les utiliser gratuitement ou de les modifier. Cela réduit par exemple les possibilités de comparer deux instruments entre eux pour mesurer leur validité et leur performance. De plus, il souligne que les recherches scientifiques sont alors soumises aux intérêts commerciaux. Il a donc entrepris de développer et de continuellement affiner un large choix d’inventaires de personnalité en proposant le projet de l’<a href="https://ipip.ori.org/">International Personality Item Pool</a>. L’IPIP présente de nombreux avantages selon <span class="citation" data-cites="goldberg_broad-bandwidth_1999">Goldberg (<a href="#ref-goldberg_broad-bandwidth_1999" role="doc-biblioref">1999</a>)</span>. En effet, l’accès et l’utilisation sont gratuits et rapides grâce à son site internet. Il permet une certaine flexibilité car les utilisateurs peuvent administrer les items dans l’ordre qui leur convient et appliquer les modifications qu’ils désirent. De plus, il regroupe également un très grand nombre d’items qui permettent de développer des versions plus ou moins longues de différents tests <span class="citation" data-cites="goldberg_international_2006">(<a href="#ref-goldberg_international_2006" role="doc-biblioref">Goldberg et al., 2006</a>)</span>. L’IPIP rassemble ainsi plus de 250 inventaires évaluant la personnalité dont l’IPIP NEO qui s’inspire du NEO-PI R <span class="citation" data-cites="costa_jr_manuel_1998">(<a href="#ref-costa_jr_manuel_1998" role="doc-biblioref">Costa, McCrae, &amp; Rolland, 1998</a>)</span>.</p>
</section>
<section id="lipip-neo" class="level1">
<h1>L’IPIP NEO</h1>
<p>L’IPIP NEO est donc une adaptation du NEO PI, dans le sens où il vise à mesurer les mêmes domaines et les mêmes facettes. Ainsi, à partir de 300 items, soit dix items par facette, l’IPIP NEO évalue les cinq domaines du Big Five :</p>
<ul>
<li>Ouverture (O) ;</li>
<li>Caractère Consciencieux (C) ;</li>
<li>Extraversion (E) ;</li>
<li>Agréabilité (A) ;</li>
<li>Névrosisme (N).</li>
</ul>
<p>Comme pour le NEO-PI R, il se base également sur six facettes par domaine, qui, pour certaines, n’ont pas exactement le même intitulé, quand bien même les définitions s’avèrent similaires. Une proposition de traduction pour les domaines et facettes en français est proposée ici.</p>
<p>L’IPIP NEO fait l’objet de <a href="https://ipip.ori.org/newItemTranslations.htm">traductions dans plus de dix langues</a>, notamment en slovène <span class="citation" data-cites="musek_j_slovene_nodate">(<a href="#ref-musek_j_slovene_nodate" role="doc-biblioref">Musek, s.&nbsp;d.</a>)</span> en japonais <span class="citation" data-cites="karlin_300_nodate">(<a href="#ref-karlin_300_nodate" role="doc-biblioref">Karlin, s.&nbsp;d.</a>)</span> ou encore en <a href="https://ipip.ori.org/FrenchCanadian300-Item-IPIP-NEO.htm">français québécois</a> <span class="citation" data-cites="gravel_french_nodate">(<a href="#ref-gravel_french_nodate" role="doc-biblioref">Gravel, s.&nbsp;d.</a>)</span>. Le site de l’IPIP NEO permet à n’importe qui de passer le test gratuitement et d’obtenir, à la fin, un résultat détaillé et des informations sur sa personnalité. Ainsi, plus de 500 000 personnes ont déjà passé ce test depuis qu’il a été diffusé sur internet. Comme pour le NEO-PI, il existe des versions courtes de l’IPIP NEO avec seulement 120 items par exemple. Cela permet de répondre plus rapidement (10-20 minutes versus 30-40 minutes) mais donne des résultats moins précis que la version 300 items. Ainsi, sur la page internet <a href="www.personal.psu.edu/~j5j/IPIP/ipipneo300.htm">The IPIP NEO (International Personality Item Pool Representation of the NEO-PI-R)</a>, n’importe qui peut remplir le questionnaire pour avoir un feedback concernant sa personnalité, dans sa version anglaise.</p>
<section id="validité-de-lipip-neo" class="level2">
<h2 class="anchored" data-anchor-id="validité-de-lipip-neo">Validité de l’IPIP NEO</h2>
<p>La validité de l’IPIP NEO a été mesurée dans la première étude de <span class="citation" data-cites="goldberg_broad-bandwidth_1999">Goldberg (<a href="#ref-goldberg_broad-bandwidth_1999" role="doc-biblioref">1999</a>)</span> qui indique que celui-ci présentait un alpha moyen de .80, ce qui est plus élevé que l’alpha du NEO-PI R qui s’élève à .75. L’échelle a une corrélation moyenne de .94 avec le NEO PI R. L’IPIP NEO a déjà fait l’objet d’études confirmant sa validité interne <span class="citation" data-cites="lim_assessing_2006">(<a href="#ref-lim_assessing_2006" role="doc-biblioref">Lim &amp; Ployhart, 2006</a>)</span>. De nombreuses études utilisant l’IPIP NEO ont montré son efficacité sur des sujets très différents : il a été utilisé pour des études traitant de l’anxiété et de la dépression <span class="citation" data-cites="lewis_relationship_2010">(<a href="#ref-lewis_relationship_2010" role="doc-biblioref">Lewis et al., 2010</a>)</span>, des comportements de santé <span class="citation" data-cites="hagger-johnson_conscientiousness_2007">(<a href="#ref-hagger-johnson_conscientiousness_2007" role="doc-biblioref">Hagger-Johnson &amp; Whiteman, 2007</a>)</span> ou encore l’utilisation du téléphone <span class="citation" data-cites="siddiqui_personality_2011">(<a href="#ref-siddiqui_personality_2011" role="doc-biblioref">Siddiqui, 2011</a>)</span> par exemple. De nombreuses études se sont appliquées à évaluer la validité de l’IPIP NEO et elles ont toutes conclu à sa robustesse et sa validité <span class="citation" data-cites="goldberg_broad-bandwidth_1999 maples_test_2014 rehman2020structural">(<a href="#ref-goldberg_broad-bandwidth_1999" role="doc-biblioref">Goldberg, 1999</a>; <a href="#ref-maples_test_2014" role="doc-biblioref">Maples, Guan, Carter, &amp; Miller, 2014</a>; <a href="#ref-rehman2020structural" role="doc-biblioref">Rehman, Muellenbach, &amp; Johnson, 2020</a>)</span>. Plus que la validation de l’IPIP NEO 300 items, sa version plus courte, comprenant 120 items, fait l’objet d’un très grand nombre d’études de validation. Ainsi, <span class="citation" data-cites="kajonius_assessing_2019">Kajonius &amp; Johnson (<a href="#ref-kajonius_assessing_2019" role="doc-biblioref">2019</a>)</span>, ont conclu à la robustesse de la structure factorielle de l’IPIP NEO 120 pour les utilisations futures.</p>
</section>
<section id="problème-de-validation-en-français" class="level2">
<h2 class="anchored" data-anchor-id="problème-de-validation-en-français">Problème de validation en français</h2>
<p>L’IPIP NEO est donc très intéressant mais s’il a été traduit dans de nombreuses langues, il n’a cependant qu’une seule traduction française, réalisée au Québec <span class="citation" data-cites="gravel_french_nodate">(<a href="#ref-gravel_french_nodate" role="doc-biblioref">Gravel, s.&nbsp;d.</a>)</span>. Néanmoins, le français québécois est sensiblement différent du français européen et une mauvaise compréhension des énoncés pourrait poser problème dans l’interprétation et dans la structure même du questionnaire <span class="citation" data-cites="longley_taxometric_2017">(<a href="#ref-longley_taxometric_2017" role="doc-biblioref">Longley et al., 2017</a>)</span>. En effet, d’après <span class="citation" data-cites="verreault_francais_nodate">Verreault (<a href="#ref-verreault_francais_nodate" role="doc-biblioref">s.&nbsp;d.</a>)</span>, si le français québécois fait partie du tout qu’est le français, celui-ci est constitué de nombreuses variétés sociales et régionales. Ainsi, le français peut déjà être divisé en deux ; séparant le français européen du français américain. Le français européen étant constitué du français de France, de Belgique et de Suisse et le français américain étant constitué du français du Canada. D’autres divisions peuvent encore être effectuées au sein même de celles-ci, jusqu’à aller au patois d’un petit village breton, par exemple. C’est pourquoi, dans un souci de rigueur pour entreprendre l’utilisation de cette traduction en Europe, il a été décidé de fournir une adaptation en français européen, afin de diminuer les erreurs de compréhension et finalement de valider l’IPIP NEO français européen. L’objectif de notre étude est de nous baser sur la traduction déjà existante de <span class="citation" data-cites="gravel_french_nodate">Gravel (<a href="#ref-gravel_french_nodate" role="doc-biblioref">s.&nbsp;d.</a>)</span> disponible sur le site de l’IPIP NEO. Cette traduction a suivi les trois première étapes de la méthode de <span class="citation" data-cites="vallerand_vers_1989">Vallerand (<a href="#ref-vallerand_vers_1989" role="doc-biblioref">1989</a>)</span>. Cette procédure incluait une première traduction en français, suivie d’une back-translation en anglais, qui devait correspondre avec la version originale. De ce fait, certains items ont été modifié jusqu’à trois fois pour correspondre au mieux et le pronom “Je” a dû être ajouté dans la version française. Notons que ce questionnaire a fait l’objet d’une traduction, mais jamais d’une validation à proprement parler.</p>
</section>
</section>
<section id="objectif-de-notre-étude" class="level1">
<h1>Objectif de notre étude</h1>
<p>Nous souhaitons proposer une adaptation française européenne de l’IPIP NEO.</p>
<p>En effet, nous constatons :</p>
<ol type="1">
<li>l’absence d’une version française validée de l’IPIP NEO ;</li>
<li>ses avantages quant à sa qualité d’instrument « open-source » ;</li>
<li>la potentielle facilitation du travail des chercheurs / étudiants par l’usage de ce test.</li>
</ol>
<p>L’objectif de notre travail est de tenter de proposer une adaptation adéquate de la version française québécoise <span class="citation" data-cites="gravel_french_nodate">(<a href="#ref-gravel_french_nodate" role="doc-biblioref">Gravel, s.&nbsp;d.</a>)</span> déjà existante. Cette étape constitue un préalable nécessaire à une tentative de validation de cette nouvelle version du questionnaire en se questionnant sur la fidélité (consistance interne) et la structure factorielle de cette nouvelle version.</p>
</section>
<section id="adaptation-française-de-lipip-neo-300" class="level1">
<h1>Adaptation française de l’IPIP NEO 300</h1>
<p>Avant d’aller plus loin, il est important d’apporter la précision suivante : <span class="citation" data-cites="gravel_french_nodate">Gravel (<a href="#ref-gravel_french_nodate" role="doc-biblioref">s.&nbsp;d.</a>)</span> n’a a priori pas réalisé le travail de traduction des domaines et des facettes du questionnaire. Ainsi, nous proposons les traductions suivantes dans le <a href="#tbl-labels" class="quarto-xref">Table&nbsp;1</a>.</p>
<div class="cell">
<div id="tbl-labels" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-labels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Proposition de traduction française des domaines et facettes de l’IPIP NEO 300 items
</figcaption>
<div aria-describedby="tbl-labels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Intitulé anglais</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Proposition en français</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">N</td>
<td style="text-align: left;">Neuroticism</td>
<td style="text-align: left;">Névrosisme</td>
</tr>
<tr class="even">
<td style="text-align: left;">N1</td>
<td style="text-align: left;">Anxiety</td>
<td style="text-align: left;">Anxiété</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N2</td>
<td style="text-align: left;">Anger</td>
<td style="text-align: left;">Colère</td>
</tr>
<tr class="even">
<td style="text-align: left;">N3</td>
<td style="text-align: left;">Depression</td>
<td style="text-align: left;">Dépression</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N4</td>
<td style="text-align: left;">Self-consciousness</td>
<td style="text-align: left;">Timidité</td>
</tr>
<tr class="even">
<td style="text-align: left;">N5</td>
<td style="text-align: left;">Immoderation</td>
<td style="text-align: left;">Impatience</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N6</td>
<td style="text-align: left;">Vulnerability</td>
<td style="text-align: left;">Vulnérabilité</td>
</tr>
<tr class="even">
<td style="text-align: left;">E</td>
<td style="text-align: left;">Extraversion</td>
<td style="text-align: left;">Extraversion</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E1</td>
<td style="text-align: left;">Friendliness</td>
<td style="text-align: left;">Sympathie</td>
</tr>
<tr class="even">
<td style="text-align: left;">E2</td>
<td style="text-align: left;">Gregariousness</td>
<td style="text-align: left;">Sociabilité</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E3</td>
<td style="text-align: left;">Assertiveness</td>
<td style="text-align: left;">Assertivité</td>
</tr>
<tr class="even">
<td style="text-align: left;">E4</td>
<td style="text-align: left;">Activity Level</td>
<td style="text-align: left;">Activité</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E5</td>
<td style="text-align: left;">Excitement-Seeking</td>
<td style="text-align: left;">Recherche de sensations</td>
</tr>
<tr class="even">
<td style="text-align: left;">E6</td>
<td style="text-align: left;">Cheerfulness</td>
<td style="text-align: left;">Enthousiasme</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: left;">Conscientiousness</td>
<td style="text-align: left;">Caractère Consciencieux</td>
</tr>
<tr class="even">
<td style="text-align: left;">C1</td>
<td style="text-align: left;">Self-efficacity</td>
<td style="text-align: left;">Auto-efficacité</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C2</td>
<td style="text-align: left;">Orderliness</td>
<td style="text-align: left;">Ordre</td>
</tr>
<tr class="even">
<td style="text-align: left;">C3</td>
<td style="text-align: left;">Dutifulness</td>
<td style="text-align: left;">Sens du devoir</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C4</td>
<td style="text-align: left;">Achievement-Striving</td>
<td style="text-align: left;">Recherche de succès</td>
</tr>
<tr class="even">
<td style="text-align: left;">C5</td>
<td style="text-align: left;">Self-Discipline</td>
<td style="text-align: left;">Auto-discipline</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C6</td>
<td style="text-align: left;">Cautiousness</td>
<td style="text-align: left;">Prudence</td>
</tr>
<tr class="even">
<td style="text-align: left;">A</td>
<td style="text-align: left;">Agreeableness</td>
<td style="text-align: left;">Agréabilité</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A1</td>
<td style="text-align: left;">Trust</td>
<td style="text-align: left;">Confiance</td>
</tr>
<tr class="even">
<td style="text-align: left;">A2</td>
<td style="text-align: left;">Morality</td>
<td style="text-align: left;">Moralité</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A3</td>
<td style="text-align: left;">Altruism</td>
<td style="text-align: left;">Altruisme</td>
</tr>
<tr class="even">
<td style="text-align: left;">A4</td>
<td style="text-align: left;">Cooperation</td>
<td style="text-align: left;">Coopération</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A5</td>
<td style="text-align: left;">Modesty</td>
<td style="text-align: left;">Modestie</td>
</tr>
<tr class="even">
<td style="text-align: left;">A6</td>
<td style="text-align: left;">Sympathy</td>
<td style="text-align: left;">Compassion</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O</td>
<td style="text-align: left;">Openness</td>
<td style="text-align: left;">Ouverture à l’expérience</td>
</tr>
<tr class="even">
<td style="text-align: left;">O1</td>
<td style="text-align: left;">Imagination</td>
<td style="text-align: left;">Imagination</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O2</td>
<td style="text-align: left;">Artistic Interest</td>
<td style="text-align: left;">Intérêt pour l’art</td>
</tr>
<tr class="even">
<td style="text-align: left;">O3</td>
<td style="text-align: left;">Emotionality</td>
<td style="text-align: left;">Emotivité</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O4</td>
<td style="text-align: left;">Adventurousness</td>
<td style="text-align: left;">Témérité</td>
</tr>
<tr class="even">
<td style="text-align: left;">O5</td>
<td style="text-align: left;">Intellect</td>
<td style="text-align: left;">Intellect</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O6</td>
<td style="text-align: left;">Liberalism</td>
<td style="text-align: left;">Libéralisme</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
</section>
<section id="méthode" class="level1">
<h1>Méthode</h1>
<section id="participants" class="level2">
<h2 class="anchored" data-anchor-id="participants">Participants</h2>
<p>Les participants sont des étudiants en deuxième année de Master de Traduction et d’Interprétation au sein de l’Université de Mons en Belgique. Âgés entre 20 et 34 ans, avec une moyenne d’âge de 23,8 ans (ET = 3,43). Vingt personnes ont participé, parmi lesquelles quinze femmes et cinq hommes. A ces vingt personnes s’ajoutent les deux auteurs qui sont intervenus dans la première étape de la procédure.</p>
</section>
<section id="matériel" class="level2">
<h2 class="anchored" data-anchor-id="matériel">Matériel</h2>
<p>Les items analysés sont ceux de l’IPIP NEO 300 items, fournis par le site de l’IPIP et notamment, la <a href="https://ipip.ori.org/FrenchCanadian300-Item-IPIP-NEO.htm">version française québécoise fournie sur ce même site</a> <span class="citation" data-cites="gravel_french_nodate">(<a href="#ref-gravel_french_nodate" role="doc-biblioref">Gravel, s.&nbsp;d.</a>)</span>. Le questionnaire a été réalisé sur Google Forms, une plateforme qui permet de faire passer des questionnaires en ligne gratuitement, permettant également d’assurer l’anonymat des participants.</p>
</section>
<section id="procédure" class="level2">
<h2 class="anchored" data-anchor-id="procédure">Procédure</h2>
<section id="etape-1-première-évaluation-par-les-deux-auteurs-de-la-traducion-québecquoise" class="level3">
<h3 class="anchored" data-anchor-id="etape-1-première-évaluation-par-les-deux-auteurs-de-la-traducion-québecquoise">Etape 1 : première évaluation par les deux auteurs de la traducion québecquoise</h3>
<p>D’abord, les deux auteurs ont parcouru la traduction française québécoise fournie sur le site de l’IPIP NEO de manière indépendante afin d’identifier les items qui pourraient poser des problèmes de compréhension, tant au niveau du vocabulaire qu’au niveau des tournures de phrases. Les items ayant été estimés ambigus, sont les items pour lesquels l’un <strong>et / ou</strong> l’autre pointaient un problème. Il est possible de noter que 91 % des items étaient consensuellement estimés comme non problématiques. Par contre, les 26 items suivants (9% des items) ont été identifiés comme étant potentiellement problématiques (<a href="#tbl-accord" class="quarto-xref">Table&nbsp;2</a>).</p>
<div class="cell">
<div id="tbl-accord" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-accord-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Items ayant été identifiés comme problématiques dans leurs traductions
</figcaption>
<div aria-describedby="tbl-accord-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Item</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Original</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Traduction française québécoise</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Auteur1</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Auteur2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">12</td>
<td style="text-align: left;">Take charge.</td>
<td style="text-align: left;">J'aime prendre en charge.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="even">
<td style="text-align: right;">28</td>
<td style="text-align: left;">Tend to vote for liberal political candidates.</td>
<td style="text-align: left;">J’ai tendance à promouvoir des valeurs sociales traditionnelles.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="odd">
<td style="text-align: right;">36</td>
<td style="text-align: left;">Get irritated easily.</td>
<td style="text-align: left;">Je suis irritable facilement.</td>
<td style="text-align: left;">OK</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="even">
<td style="text-align: right;">37</td>
<td style="text-align: left;">Talk to a lot of different people at parties.</td>
<td style="text-align: left;">Je parle à plusieurs personnes dans les partys.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="odd">
<td style="text-align: right;">42</td>
<td style="text-align: left;">Try to lead others.</td>
<td style="text-align: left;">J'essaie de diriger les autres.</td>
<td style="text-align: left;">OK</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="even">
<td style="text-align: right;">50</td>
<td style="text-align: left;">Work hard.</td>
<td style="text-align: left;">Je travaille fort.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="odd">
<td style="text-align: right;">57</td>
<td style="text-align: left;">Have a lot of fun.</td>
<td style="text-align: left;">J'ai beaucoup de plaisir.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">OK</td>
</tr>
<tr class="even">
<td style="text-align: right;">66</td>
<td style="text-align: left;">Get upset easily.</td>
<td style="text-align: left;">Je deviens choqué facilement.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="odd">
<td style="text-align: right;">109</td>
<td style="text-align: left;">Have a sharp tongue.</td>
<td style="text-align: left;">J'ai tendance à être sévère et critique.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">OK</td>
</tr>
<tr class="even">
<td style="text-align: right;">134</td>
<td style="text-align: left;">Have a good word for everyone.</td>
<td style="text-align: left;">J'ai de bons commentaires sur tout le monde.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="odd">
<td style="text-align: right;">148</td>
<td style="text-align: left;">Tend to vote for conservative political candidates.</td>
<td style="text-align: left;">J’ai tendance à promouvoir des valeurs sociales libérales.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="even">
<td style="text-align: right;">163</td>
<td style="text-align: left;">Seldom get emotional.</td>
<td style="text-align: left;">Je suis rarement émotif.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="odd">
<td style="text-align: right;">166</td>
<td style="text-align: left;">Stumble over my words</td>
<td style="text-align: left;">Je trébuche dans mes mots.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">OK</td>
</tr>
<tr class="even">
<td style="text-align: right;">170</td>
<td style="text-align: left;">Set high standards for myself and others.</td>
<td style="text-align: left;">Je me fixe des standards élevés pour moi-même et les autres.</td>
<td style="text-align: left;">OK</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="odd">
<td style="text-align: right;">174</td>
<td style="text-align: left;">Think highly of myself.</td>
<td style="text-align: left;">J'ai une très grande estime de moi-même.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="even">
<td style="text-align: right;">184</td>
<td style="text-align: left;">Distrust people</td>
<td style="text-align: left;">Je ne fais pas confiance aux autres.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="odd">
<td style="text-align: right;">187</td>
<td style="text-align: left;">Want to be left alone</td>
<td style="text-align: left;">J'ai le goût qu'on me laisse seul.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="even">
<td style="text-align: right;">191</td>
<td style="text-align: left;">Feel that my life lacks direction</td>
<td style="text-align: left;">Je sens que ma vie manque de sens.</td>
<td style="text-align: left;">OK</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="odd">
<td style="text-align: right;">199</td>
<td style="text-align: left;">Yell at people.</td>
<td style="text-align: left;">Je crie après les gens.</td>
<td style="text-align: left;">OK</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="even">
<td style="text-align: right;">223</td>
<td style="text-align: left;">Rarely notice my emotional reactions</td>
<td style="text-align: left;">Je suis rarement sensible à mes réactions émotives.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">OK</td>
</tr>
<tr class="odd">
<td style="text-align: right;">224</td>
<td style="text-align: left;">Make people feel uncomfortable.</td>
<td style="text-align: left;">Je rends les gens inconfortables.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="even">
<td style="text-align: right;">262</td>
<td style="text-align: left;">Would never go hang gliding or bungee jumping.</td>
<td style="text-align: left;">Je ne ferai jamais du deltaplane ou un saut en bungee.</td>
<td style="text-align: left;">OK</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="odd">
<td style="text-align: right;">267</td>
<td style="text-align: left;">Am not easily amused.</td>
<td style="text-align: left;">Je ne m'amuse pas facilement.</td>
<td style="text-align: left;">OK</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="even">
<td style="text-align: right;">270</td>
<td style="text-align: left;">Act without thinking.</td>
<td style="text-align: left;">J'agis sans penser.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="odd">
<td style="text-align: right;">294</td>
<td style="text-align: left;">Make myself the center of attention.</td>
<td style="text-align: left;">Je suis le centre de l'attention.</td>
<td style="text-align: left;">OK</td>
<td style="text-align: left;">X</td>
</tr>
<tr class="even">
<td style="text-align: right;">299</td>
<td style="text-align: left;">Can't stand weak people.</td>
<td style="text-align: left;">Je n'aime pas côtoyer les gens faibles.</td>
<td style="text-align: left;">X</td>
<td style="text-align: left;">X</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
</section>
<section id="etape-2-traductions-de-langlais-au-français-par-les-étudiants-en-traduction" class="level3">
<h3 class="anchored" data-anchor-id="etape-2-traductions-de-langlais-au-français-par-les-étudiants-en-traduction">Etape 2 : traductions de l’anglais au français par les étudiants en traduction</h3>
<p>Afin de remédier à ces problèmes de traduction, il a été décidé de présenter ces items à des étudiants en deuxième année de master en Traduction, l’objectif étant qu’ils fournissent la traduction la plus adéquate possible de chaque item, de l’anglais au français. Le questionnaire a été réalisé sur Google Forms et a donc été diffusé sur le groupe Facebook officiel des étudiants en Master 2 de Traduction et Interprétation de l’UMONS.</p>
<p>Lors de l’ouverture du questionnaire en ligne, les participants arrivaient sur une page présentant le projet. Sur la page était donc spécifiée la consigne indiquant que le questionnaire comprenait 26 phrases courtes en anglais pour lesquelles il est demandé de proposer une traduction en français. Il était également spécifié que les réponses étaient anonymes, que la participation était libre et volontaire et que les participants pouvaient décider d’arrêter de répondre au questionnaire s’ils le souhaitaient, sans qu’il n’y ait de conséquences. Il était aussi spécifié que cela ne prendrait que cinq minutes environ. En cliquant sur “suivant”, les participants étaient alors conduits sur une page avec les 26 items en anglais, auxquels une zone de réponse ouverte était associée afin qu’ils puissent fournir leur traduction. Après avoir répondu à toutes les questions, les participants étaient amenés sur une page où il leur était demandé d’indiquer leur âge ainsi que leur genre. Enfin, ils étaient conduits sur une page les remerciant de leur participation.</p>
</section>
<section id="etape-3-analyse-des-fréquences-de-chaque-proposition-de-traduction" class="level3">
<h3 class="anchored" data-anchor-id="etape-3-analyse-des-fréquences-de-chaque-proposition-de-traduction">Etape 3 : analyse des fréquences de chaque proposition de traduction</h3>
<p>Les données ont ensuite été récoltées, classées et codées dans un tableau Excel.</p>
<p>A partir des traductions obtenues, une analyse a pu être réalisée afin de déterminer quelle traduction, pour chaque item, était la plus fréquemment donnée par les participants. Ainsi, pour chaque item, une analyse des réponses a été effectuée. Pour cela, des thèmes communs qui couvrent les vingt réponses à chaque item ont été dégagés. Pour chaque thème identifié, un code a été attribué puis le nombre de réponses qui s’identifient au thème qui leur correspond ont été comptabilisées en utilisant la fonction de comptage avec condition “NB.Si()” sur Excel <span class="citation" data-cites="microsoft_corporation_microsoft_2018">(<a href="#ref-microsoft_corporation_microsoft_2018" role="doc-biblioref">Microsoft, 2018</a>)</span>. Il est ainsi possible, pour chaque item, de dégager les traductions les plus fréquemment données par les participants.</p>
</section>
</section>
</section>
<section id="résultats" class="level1">
<h1>Résultats</h1>
<section id="exemple-de-litem-50-work-hard" class="level2">
<h2 class="anchored" data-anchor-id="exemple-de-litem-50-work-hard">Exemple de l’item 50 : “Work hard”</h2>
<p>La traduction québécoise était “Je travaille fort”, ce qui semble un peu trop littéral pour être bien compris. Cet item a donc fait partie du questionnaire et parmi les 20 participants, 4 réponses différentes ont été données à savoir :</p>
<ul>
<li>Je travaille <strong>dur</strong>.</li>
<li>Je travaille <strong>beaucoup/énormément</strong>.</li>
<li>Je travaille <strong>d’arrache-pied</strong>.</li>
<li>Je m’<strong>investis</strong> dans mon travail.</li>
</ul>
<p>A partir de ces quatre propositions, il a été possible d’établir des thèmes et de les coder. Ainsi, toutes les traductions comprenant le mot “dur” ont été codées “D”, celles comprenant le mot “beaucoup” ou “énormément” ont été codées “B”, celles comprenant le mot “arrache-pied” ont été codées “A” et celles comprenant le mot “investis” ont été codées “I”. De cette manière, il a alors été possible de comptabiliser les différents thèmes afin de dégager la traduction donnée la plus fréquemment par les participants, celle qui se rapproche le plus de la meilleure traduction. Pour cet item, le <a href="#tbl-workhard" class="quarto-xref">Table&nbsp;3</a> a pu être dressé.</p>
<div class="cell">
<div id="tbl-workhard" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-workhard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Fréquences et proportions de traductions pour l’item « Work hard » par 20 étudiants en traduction de l’UMONS
</figcaption>
<div aria-describedby="tbl-workhard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Thèmes</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Code</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Fréquences</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Proportions (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Dur</td>
<td style="text-align: left;">D</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">75</td>
</tr>
<tr class="even">
<td style="text-align: left;">Beaucoup / énormément</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">D'arrache-pied</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Investis</td>
<td style="text-align: left;">I</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Ainsi, il est possible de dire que 75% des participants ont traduit “Work hard” par “Je travaille dur”. C’est donc cette traduction qui a été retenue pour la version française de l’IPIP NEO. Les mêmes analyses ont été réalisées sur chacun des items. Concernant les items 42, 163, 184, 191 et 267, ils ont en majorité été traduits de la même façon que pour la version québécoise et sont donc restés inchangés.</p>
</section>
<section id="items-réévalués" class="level2">
<h2 class="anchored" data-anchor-id="items-réévalués">Items réévalués</h2>
<p>En revanche, plusieurs items ont dû faire l’objet d’une seconde analyse, car ils restaient problématiques.</p>
<p>D’abord, La traduction de l’item 12 s’est avéré problématique. En effet, 50% des participants ont traduit “I take charge” par “Je m’en occupe”. Cependant, un test de personnalité cherche à mesurer des traits et non pas des actions en cours. Ainsi, “je m’en occupe” semble être une phrase se référant plus à une action qu’à un trait de personnalité. Selon nous, cette traduction semble trop littérale et pourrait conduire les participants à se demander par exemple “de quoi m’occupe-je ?” et à ne pas comprendre l’item. Néanmoins, 20% des participants ont donné la traduction “Je prends les choses en main”. Cette traduction semble plus proche de l’idée générale de l’item et semble laisser moins de place à l’ambiguïté quant à la façon de l’interpréter. C’est donc cette traduction qui a été choisie après discussion entre les deux auteurs.</p>
<p>Ensuite, les traductions des items 28 et 148 ont également été estimés ambiguës. En effet, ces items concernent l’orientation politique à savoir “conservateur” ou “libéral”. Le problème majeur de ces items est que ces deux partis sont des partis américains, qui n’ont pas du tout la même signification en Belgique ou en France, voire qui n’existent pas. Cependant, les traducteurs ont traduit littéralement les items en conservant les termes de “libéraux” et “conservateurs”. Après réflexion, nous avons décidé de conserver les traductions données par les participants. Cela permet de ne pas prendre le risque de changer le sens même des items, les termes “libéraux” et “conservateurs” pouvant être compris dans leur sens propre sans pour autant se référer à un parti politique, “Conservateur” étant synonyme de “préserver ce qui existe” et “Libéral” étant synonyme de “favorable aux libertés individuelles” <span class="citation" data-cites="robert_p_liberal_nodate">(<a href="#ref-robert_p_liberal_nodate" role="doc-biblioref">Robert, s.&nbsp;d.</a>)</span>. Les items retenus ici sont donc les suivants : “J’ai tendance à voter pour des candidats libéraux” et “J’ai tendance à voter pour des candidats conservateurs”.</p>
</section>
<section id="traduction-française-européenne" class="level2">
<h2 class="anchored" data-anchor-id="traduction-française-européenne">Traduction française européenne</h2>
<p>Dans le <a href="#tbl-traductions" class="quarto-xref">Table&nbsp;4</a>, se trouvent les nouvelles traductions retenues, avec la proportion de participants ayant fourni cette traduction (ce tableau n’inclut pas les items inchangés).</p>
<div class="cell">
<div id="tbl-traductions" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-traductions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Traductions des items retenues dans le questionnaire
</figcaption>
<div aria-describedby="tbl-traductions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Item</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Proportion (%)</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Traduction retenue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">12</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">Je prends les choses en main</td>
</tr>
<tr class="even">
<td style="text-align: right;">28</td>
<td style="text-align: right;">75</td>
<td style="text-align: left;">J'ai tendance à voter pour des candidats libéraux</td>
</tr>
<tr class="odd">
<td style="text-align: right;">36</td>
<td style="text-align: right;">40</td>
<td style="text-align: left;">Je suis facilement irrité</td>
</tr>
<tr class="even">
<td style="text-align: right;">37</td>
<td style="text-align: right;">70</td>
<td style="text-align: left;">Je parle à plusieurs personnes en soirée</td>
</tr>
<tr class="odd">
<td style="text-align: right;">50</td>
<td style="text-align: right;">75</td>
<td style="text-align: left;">Je travaille dur</td>
</tr>
<tr class="even">
<td style="text-align: right;">57</td>
<td style="text-align: right;">85</td>
<td style="text-align: left;">Je m'amuse beaucoup</td>
</tr>
<tr class="odd">
<td style="text-align: right;">66</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">Je suis facilement contrarié</td>
</tr>
<tr class="even">
<td style="text-align: right;">109</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">Je n'ai pas ma langue dans ma poche</td>
</tr>
<tr class="odd">
<td style="text-align: right;">134</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">J'ai toujours un mot gentil pour tout le monde</td>
</tr>
<tr class="even">
<td style="text-align: right;">148</td>
<td style="text-align: right;">55</td>
<td style="text-align: left;">J'ai tendance à voter pour des candidats conservateurs</td>
</tr>
<tr class="odd">
<td style="text-align: right;">166</td>
<td style="text-align: right;">40</td>
<td style="text-align: left;">Je cherche mes mots</td>
</tr>
<tr class="even">
<td style="text-align: right;">170</td>
<td style="text-align: right;">45</td>
<td style="text-align: left;">Je suis exigeant avec moi-même et les autres</td>
</tr>
<tr class="odd">
<td style="text-align: right;">174</td>
<td style="text-align: right;">65</td>
<td style="text-align: left;">J'ai une haute estime de moi-même</td>
</tr>
<tr class="even">
<td style="text-align: right;">187</td>
<td style="text-align: right;">70</td>
<td style="text-align: left;">Je veux qu'on me laisse seul</td>
</tr>
<tr class="odd">
<td style="text-align: right;">199</td>
<td style="text-align: right;">95</td>
<td style="text-align: left;">Je crie sur les gens</td>
</tr>
<tr class="even">
<td style="text-align: right;">223</td>
<td style="text-align: right;">60</td>
<td style="text-align: left;">Je remarque rarement mes réactions émotionnelles</td>
</tr>
<tr class="odd">
<td style="text-align: right;">224</td>
<td style="text-align: right;">85</td>
<td style="text-align: left;">Je mets les gens mal à l'aise</td>
</tr>
<tr class="even">
<td style="text-align: right;">262</td>
<td style="text-align: right;">70</td>
<td style="text-align: left;">Je ne ferai jamais du deltaplane ou de saut à l'élastique</td>
</tr>
<tr class="odd">
<td style="text-align: right;">270</td>
<td style="text-align: right;">85</td>
<td style="text-align: left;">J'agis sans réfléchir</td>
</tr>
<tr class="even">
<td style="text-align: right;">294</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">Je fais en sorte d'être le centre de l'attention</td>
</tr>
<tr class="odd">
<td style="text-align: right;">299</td>
<td style="text-align: right;">100</td>
<td style="text-align: left;">Je ne supporte pas les gens faibles</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>Il est donc à présent possible de fournir une traduction française Européenne à l’IPIP NEO, en réutilisant la traduction québécoise validée et en replaçant tous les items ci-dessus par les nouvelles traductions fournies par notre échantillon de vingt étudiants traducteurs. La version française européenne que nous proposons est dans le <a href="#tbl-ipipneo" class="quarto-xref">Table&nbsp;5</a>.</p>
</section>
</section>
<section id="ipip-neo-300---version-française" class="level1">
<h1>IPIP NEO 300 - Version française</h1>
<div class="cell">
<div id="tbl-ipipneo" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ipipneo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: IPIP NEO 300 - Version française
</figcaption>
<div aria-describedby="tbl-ipipneo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Item</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Question</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Je m'inquiète à propos de choses.</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">Je me fais des amis facilement.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">J'ai une imagination débordante.</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">Je fais confiance aux autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">Je complète les tâches avec succès.</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">Je me mets en colère facilement.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">J'adore les grandes fêtes.</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: left;">Je crois en l'importance de l'art.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: left;">Je ne tricherais jamais à propos de mes impôts.</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: left;">J'aime l'ordre.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: left;">Je me sens souvent triste.</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: left;">Je prends les choses en main</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: left;">Je vis mes émotions intensément.</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: left;">Je fais sentir aux gens qu'ils sont les bienvenus.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: left;">J'essaie de suivre les règles.</td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: left;">Je suis facilement intimidé.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">17</td>
<td style="text-align: left;">Je suis toujours occupé.</td>
</tr>
<tr class="even">
<td style="text-align: right;">18</td>
<td style="text-align: left;">Je préfère la variété à la routine.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">19</td>
<td style="text-align: left;">Je suis facile à satisfaire.</td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td style="text-align: left;">Je vais droit au but.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">21</td>
<td style="text-align: left;">Je mange souvent à l'excès.</td>
</tr>
<tr class="even">
<td style="text-align: right;">22</td>
<td style="text-align: left;">J'adore les sensations fortes.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">23</td>
<td style="text-align: left;">J'aime résoudre des problèmes complexes.</td>
</tr>
<tr class="even">
<td style="text-align: right;">24</td>
<td style="text-align: left;">Je n'aime pas être le centre de l'attention.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">25</td>
<td style="text-align: left;">Je fais les corvées immédiatement.</td>
</tr>
<tr class="even">
<td style="text-align: right;">26</td>
<td style="text-align: left;">Je panique facilement.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">27</td>
<td style="text-align: left;">Je respire la joie.</td>
</tr>
<tr class="even">
<td style="text-align: right;">28</td>
<td style="text-align: left;">J'ai tendance à voter pour des candidats libéraux</td>
</tr>
<tr class="odd">
<td style="text-align: right;">29</td>
<td style="text-align: left;">Je sympathise avec les sans-abri.</td>
</tr>
<tr class="even">
<td style="text-align: right;">30</td>
<td style="text-align: left;">J'évite les erreurs.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">31</td>
<td style="text-align: left;">Je crains le pire.</td>
</tr>
<tr class="even">
<td style="text-align: right;">32</td>
<td style="text-align: left;">Je développe rapidement des liens avec les autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">33</td>
<td style="text-align: left;">J'aime me perdre dans mes idées.</td>
</tr>
<tr class="even">
<td style="text-align: right;">34</td>
<td style="text-align: left;">Je crois que les autres ont de bonnes intentions.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">35</td>
<td style="text-align: left;">J'excelle dans ce que je fais.</td>
</tr>
<tr class="even">
<td style="text-align: right;">36</td>
<td style="text-align: left;">Je suis facilement irrité</td>
</tr>
<tr class="odd">
<td style="text-align: right;">37</td>
<td style="text-align: left;">Je parle à plusieurs personnes en soirée</td>
</tr>
<tr class="even">
<td style="text-align: right;">38</td>
<td style="text-align: left;">J'aime la musique.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">39</td>
<td style="text-align: left;">Je m'en tiens aux règles.</td>
</tr>
<tr class="even">
<td style="text-align: right;">40</td>
<td style="text-align: left;">J'aime faire du rangement.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">41</td>
<td style="text-align: left;">Je ne m'aime pas.</td>
</tr>
<tr class="even">
<td style="text-align: right;">42</td>
<td style="text-align: left;">J'essaie de diriger les autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">43</td>
<td style="text-align: left;">Je ressens les émotions des autres.</td>
</tr>
<tr class="even">
<td style="text-align: right;">44</td>
<td style="text-align: left;">J'anticipe les besoins des autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">45</td>
<td style="text-align: left;">Je tiens mes promesses.</td>
</tr>
<tr class="even">
<td style="text-align: right;">46</td>
<td style="text-align: left;">J'ai peur de faire la mauvaise chose.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">47</td>
<td style="text-align: left;">Je suis toujours en mouvement.</td>
</tr>
<tr class="even">
<td style="text-align: right;">48</td>
<td style="text-align: left;">J'aime visiter de nouveaux endroits.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">49</td>
<td style="text-align: left;">Je ne supporte pas les confrontations.</td>
</tr>
<tr class="even">
<td style="text-align: right;">50</td>
<td style="text-align: left;">Je travaille dur</td>
</tr>
<tr class="odd">
<td style="text-align: right;">51</td>
<td style="text-align: left;">Je ne sais pas pourquoi je fais certaines choses.</td>
</tr>
<tr class="even">
<td style="text-align: right;">52</td>
<td style="text-align: left;">Je recherche l'aventure.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">53</td>
<td style="text-align: left;">J'adore lire des documents stimulants.</td>
</tr>
<tr class="even">
<td style="text-align: right;">54</td>
<td style="text-align: left;">Je n'aime pas parler de moi-même.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">55</td>
<td style="text-align: left;">Je suis toujours préparé.</td>
</tr>
<tr class="even">
<td style="text-align: right;">56</td>
<td style="text-align: left;">Je me sens dépassé par les événements.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">57</td>
<td style="text-align: left;">Je m'amuse beaucoup</td>
</tr>
<tr class="even">
<td style="text-align: right;">58</td>
<td style="text-align: left;">Je crois qu'il n'y a pas de bon ou de mauvais absolu.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">59</td>
<td style="text-align: left;">J'ai de la sympathie pour les gens plus démunis que moi.</td>
</tr>
<tr class="even">
<td style="text-align: right;">60</td>
<td style="text-align: left;">Je choisis mes mots avec soin.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">61</td>
<td style="text-align: left;">J'ai peur de plusieurs choses.</td>
</tr>
<tr class="even">
<td style="text-align: right;">62</td>
<td style="text-align: left;">Je me sens confortable avec les gens.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">63</td>
<td style="text-align: left;">J'adore rêvasser.</td>
</tr>
<tr class="even">
<td style="text-align: right;">64</td>
<td style="text-align: left;">J'ai confiance en ce que les gens disent.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">65</td>
<td style="text-align: left;">Je gère les tâches facilement.</td>
</tr>
<tr class="even">
<td style="text-align: right;">66</td>
<td style="text-align: left;">Je suis facilement contrarié</td>
</tr>
<tr class="odd">
<td style="text-align: right;">67</td>
<td style="text-align: left;">J'aime faire partie d'un groupe.</td>
</tr>
<tr class="even">
<td style="text-align: right;">68</td>
<td style="text-align: left;">Je vois une beauté dans les choses que d'autres pourraient ne pas remarquer.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">69</td>
<td style="text-align: left;">J'utilise la flatterie pour avancer.</td>
</tr>
<tr class="even">
<td style="text-align: right;">70</td>
<td style="text-align: left;">Je veux que tout soit parfait.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">71</td>
<td style="text-align: left;">Il m'arrive souvent de broyer du noir.</td>
</tr>
<tr class="even">
<td style="text-align: right;">72</td>
<td style="text-align: left;">Je peux influencer les autres à faire des choses.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">73</td>
<td style="text-align: left;">Je suis passionné à propos de causes.</td>
</tr>
<tr class="even">
<td style="text-align: right;">74</td>
<td style="text-align: left;">J'adore aider les autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">75</td>
<td style="text-align: left;">Je paye mes factures à temps.</td>
</tr>
<tr class="even">
<td style="text-align: right;">76</td>
<td style="text-align: left;">J'éprouve de la difficulté à aborder les autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">77</td>
<td style="text-align: left;">Je fais beaucoup de choses dans mes temps libres.</td>
</tr>
<tr class="even">
<td style="text-align: right;">78</td>
<td style="text-align: left;">Je suis intéressé par plusieurs choses.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">79</td>
<td style="text-align: left;">Je déteste paraître exigeant.</td>
</tr>
<tr class="even">
<td style="text-align: right;">80</td>
<td style="text-align: left;">Je mets mes plans en action.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">81</td>
<td style="text-align: left;">Je fais des choses que je regrette par la suite.</td>
</tr>
<tr class="even">
<td style="text-align: right;">82</td>
<td style="text-align: left;">J'adore l'action.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">83</td>
<td style="text-align: left;">J'ai un vocabulaire riche.</td>
</tr>
<tr class="even">
<td style="text-align: right;">84</td>
<td style="text-align: left;">Je me considère comme une personne dans la moyenne.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">85</td>
<td style="text-align: left;">Je commence les tâches tout de suite.</td>
</tr>
<tr class="even">
<td style="text-align: right;">86</td>
<td style="text-align: left;">Je me sens incapable de gérer les choses.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">87</td>
<td style="text-align: left;">J'exprime une joie enfantine.</td>
</tr>
<tr class="even">
<td style="text-align: right;">88</td>
<td style="text-align: left;">Je crois que les criminels devraient recevoir de l'aide plutôt que des punitions.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">89</td>
<td style="text-align: left;">J'accorde plus de valeur à la coopération qu'à la compétition.</td>
</tr>
<tr class="even">
<td style="text-align: right;">90</td>
<td style="text-align: left;">Je m'en tiens au plan établi.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">91</td>
<td style="text-align: left;">Je deviens stressé facilement.</td>
</tr>
<tr class="even">
<td style="text-align: right;">92</td>
<td style="text-align: left;">J'agis aisément avec les autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">93</td>
<td style="text-align: left;">J'aime me perdre dans mes pensées.</td>
</tr>
<tr class="even">
<td style="text-align: right;">94</td>
<td style="text-align: left;">Je crois que les gens sont fondamentalement moraux.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">95</td>
<td style="text-align: left;">J'agis avec solidité et assurance.</td>
</tr>
<tr class="even">
<td style="text-align: right;">96</td>
<td style="text-align: left;">Je suis souvent de mauvaise humeur.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">97</td>
<td style="text-align: left;">J'implique les autres dans ce que je fais.</td>
</tr>
<tr class="even">
<td style="text-align: right;">98</td>
<td style="text-align: left;">J'adore les fleurs.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">99</td>
<td style="text-align: left;">J'utilise les autres pour mes propres fins.</td>
</tr>
<tr class="even">
<td style="text-align: right;">100</td>
<td style="text-align: left;">J'adore l'ordre et la constance.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">101</td>
<td style="text-align: left;">J'ai une faible opinion de moi-même.</td>
</tr>
<tr class="even">
<td style="text-align: right;">102</td>
<td style="text-align: left;">Je cherche à influencer les autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">103</td>
<td style="text-align: left;">J'aime m'auto-analyser et analyser ma vie.</td>
</tr>
<tr class="even">
<td style="text-align: right;">104</td>
<td style="text-align: left;">Je me préoccupe des autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">105</td>
<td style="text-align: left;">Je dis la vérité.</td>
</tr>
<tr class="even">
<td style="text-align: right;">106</td>
<td style="text-align: left;">J'ai peur d'attirer l'attention vers moi.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">107</td>
<td style="text-align: left;">Je peux gérer plusieurs choses en même temps.</td>
</tr>
<tr class="even">
<td style="text-align: right;">108</td>
<td style="text-align: left;">J'aime commencer de nouvelles choses.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">109</td>
<td style="text-align: left;">Je n'ai pas ma langue dans ma poche</td>
</tr>
<tr class="even">
<td style="text-align: right;">110</td>
<td style="text-align: left;">Je me lance dans les tâches avec tout mon cœur.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">111</td>
<td style="text-align: left;">Je fais des excès.</td>
</tr>
<tr class="even">
<td style="text-align: right;">112</td>
<td style="text-align: left;">J'aime faire partie d'une foule bruyante.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">113</td>
<td style="text-align: left;">Je peux gérer beaucoup d'informations.</td>
</tr>
<tr class="even">
<td style="text-align: right;">114</td>
<td style="text-align: left;">Je me vante rarement de mes accomplissements.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">115</td>
<td style="text-align: left;">Je me mets au travail immédiatement.</td>
</tr>
<tr class="even">
<td style="text-align: right;">116</td>
<td style="text-align: left;">J'ai de la difficulté à prendre une décision.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">117</td>
<td style="text-align: left;">Je prends la vie en riant.</td>
</tr>
<tr class="even">
<td style="text-align: right;">118</td>
<td style="text-align: left;">Je crois en une seule vraie religion.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">119</td>
<td style="text-align: left;">Je souffre devant la tristesse des autres.</td>
</tr>
<tr class="even">
<td style="text-align: right;">120</td>
<td style="text-align: left;">Je me lance dans les choses sans réfléchir.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">121</td>
<td style="text-align: left;">Je me laisse emporter par mes problèmes.</td>
</tr>
<tr class="even">
<td style="text-align: right;">122</td>
<td style="text-align: left;">J'encourage les gens.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">123</td>
<td style="text-align: left;">Je donne libre cours à mes fantaisies.</td>
</tr>
<tr class="even">
<td style="text-align: right;">124</td>
<td style="text-align: left;">Je crois en la bonté humaine.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">125</td>
<td style="text-align: left;">Je trouve de bonnes solutions.</td>
</tr>
<tr class="even">
<td style="text-align: right;">126</td>
<td style="text-align: left;">Je perds patience.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">127</td>
<td style="text-align: left;">J'adore les fêtes surprise.</td>
</tr>
<tr class="even">
<td style="text-align: right;">128</td>
<td style="text-align: left;">J'apprécie la beauté de la nature.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">129</td>
<td style="text-align: left;">Je sais comment contourner les règles.</td>
</tr>
<tr class="even">
<td style="text-align: right;">130</td>
<td style="text-align: left;">Je fais les choses selon un plan.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">131</td>
<td style="text-align: left;">J'ai des sautes d'humeur fréquentes.</td>
</tr>
<tr class="even">
<td style="text-align: right;">132</td>
<td style="text-align: left;">Je prends le contrôle des choses.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">133</td>
<td style="text-align: left;">J'essaie de me comprendre.</td>
</tr>
<tr class="even">
<td style="text-align: right;">134</td>
<td style="text-align: left;">J'ai toujours un mot gentil pour tout le monde</td>
</tr>
<tr class="odd">
<td style="text-align: right;">135</td>
<td style="text-align: left;">J'écoute ma conscience.</td>
</tr>
<tr class="even">
<td style="text-align: right;">136</td>
<td style="text-align: left;">Je me sens seulement à l'aise avec mes amis.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">137</td>
<td style="text-align: left;">Je réagis rapidement.</td>
</tr>
<tr class="even">
<td style="text-align: right;">138</td>
<td style="text-align: left;">Je préfère m'en tenir aux choses connues.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">139</td>
<td style="text-align: left;">Je contredis les autres.</td>
</tr>
<tr class="even">
<td style="text-align: right;">140</td>
<td style="text-align: left;">Je fais plus que ce que l'on attend de moi.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">141</td>
<td style="text-align: left;">J'adore manger.</td>
</tr>
<tr class="even">
<td style="text-align: right;">142</td>
<td style="text-align: left;">J'agis de manière effrénée.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">143</td>
<td style="text-align: left;">J'aime réfléchir sur différentes choses.</td>
</tr>
<tr class="even">
<td style="text-align: right;">144</td>
<td style="text-align: left;">Je crois être meilleur que les autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">145</td>
<td style="text-align: left;">Je réalise mes objectifs.</td>
</tr>
<tr class="even">
<td style="text-align: right;">146</td>
<td style="text-align: left;">Je me laisse envahir par les émotions.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">147</td>
<td style="text-align: left;">J'adore la vie.</td>
</tr>
<tr class="even">
<td style="text-align: right;">148</td>
<td style="text-align: left;">J'ai tendance à voter pour des candidats conservateurs</td>
</tr>
<tr class="odd">
<td style="text-align: right;">149</td>
<td style="text-align: left;">Je ne suis pas intéressé par les problèmes des autres.</td>
</tr>
<tr class="even">
<td style="text-align: right;">150</td>
<td style="text-align: left;">Je prends des décisions impulsives.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">151</td>
<td style="text-align: left;">Je ne suis pas facilement dérangé par les choses.</td>
</tr>
<tr class="even">
<td style="text-align: right;">152</td>
<td style="text-align: left;">Je me laisse difficilement connaître par les autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">153</td>
<td style="text-align: left;">Je passe du temps à réfléchir sur les choses.</td>
</tr>
<tr class="even">
<td style="text-align: right;">154</td>
<td style="text-align: left;">Je pense que tout ira bien.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">155</td>
<td style="text-align: left;">Je sais comment faire avancer les choses.</td>
</tr>
<tr class="even">
<td style="text-align: right;">156</td>
<td style="text-align: left;">Je suis rarement irrité.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">157</td>
<td style="text-align: left;">Je préfère être seul.</td>
</tr>
<tr class="even">
<td style="text-align: right;">158</td>
<td style="text-align: left;">Je n'aime pas l'art.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">159</td>
<td style="text-align: left;">Je triche pour avancer.</td>
</tr>
<tr class="even">
<td style="text-align: right;">160</td>
<td style="text-align: left;">J'oublie souvent de remettre les choses à leur place.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">161</td>
<td style="text-align: left;">Je me sens désespéré.</td>
</tr>
<tr class="even">
<td style="text-align: right;">162</td>
<td style="text-align: left;">J'attends que les autres prennent les devants.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">163</td>
<td style="text-align: left;">Je suis rarement émotif.</td>
</tr>
<tr class="even">
<td style="text-align: right;">164</td>
<td style="text-align: left;">Je regarde les autres de haut.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">165</td>
<td style="text-align: left;">J'enfreins les règles.</td>
</tr>
<tr class="even">
<td style="text-align: right;">166</td>
<td style="text-align: left;">Je cherche mes mots</td>
</tr>
<tr class="odd">
<td style="text-align: right;">167</td>
<td style="text-align: left;">J'aime prendre ça mollo.</td>
</tr>
<tr class="even">
<td style="text-align: right;">168</td>
<td style="text-align: left;">Je n'aime pas les changements.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">169</td>
<td style="text-align: left;">J'adore une bonne bagarre.</td>
</tr>
<tr class="even">
<td style="text-align: right;">170</td>
<td style="text-align: left;">Je suis exigeant avec moi-même et les autres</td>
</tr>
<tr class="odd">
<td style="text-align: right;">171</td>
<td style="text-align: left;">Je fais rarement des excès.</td>
</tr>
<tr class="even">
<td style="text-align: right;">172</td>
<td style="text-align: left;">J'agis de façon téméraire.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">173</td>
<td style="text-align: left;">Je ne suis pas intéressé par les idées abstraites.</td>
</tr>
<tr class="even">
<td style="text-align: right;">174</td>
<td style="text-align: left;">J’ai une haute estime de moi-même</td>
</tr>
<tr class="odd">
<td style="text-align: right;">175</td>
<td style="text-align: left;">Je trouve difficile de me mettre au travail.</td>
</tr>
<tr class="even">
<td style="text-align: right;">176</td>
<td style="text-align: left;">Je demeure calme sous pression.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">177</td>
<td style="text-align: left;">Je regarde le bon côté de la vie.</td>
</tr>
<tr class="even">
<td style="text-align: right;">178</td>
<td style="text-align: left;">Je crois que trop d'argent de l'impôt va aux artistes pour les soutenir.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">179</td>
<td style="text-align: left;">J'ai tendance à ne pas aimer les gens au cœur tendre.</td>
</tr>
<tr class="even">
<td style="text-align: right;">180</td>
<td style="text-align: left;">J'agis sur un coup de tête.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">181</td>
<td style="text-align: left;">Je suis détendu la plupart du temps.</td>
</tr>
<tr class="even">
<td style="text-align: right;">182</td>
<td style="text-align: left;">Je me sens souvent inconfortable en présence d'autres personnes.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">183</td>
<td style="text-align: left;">Je rêvasse rarement.</td>
</tr>
<tr class="even">
<td style="text-align: right;">184</td>
<td style="text-align: left;">Je ne fais pas confiance aux autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">185</td>
<td style="text-align: left;">Je juge mal les situations.</td>
</tr>
<tr class="even">
<td style="text-align: right;">186</td>
<td style="text-align: left;">Je me mets rarement en colère.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">187</td>
<td style="text-align: left;">Je veux qu'on me laisse seul</td>
</tr>
<tr class="even">
<td style="text-align: right;">188</td>
<td style="text-align: left;">Je n'aime pas la poésie.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">189</td>
<td style="text-align: left;">J'exerce de la pression sur les gens.</td>
</tr>
<tr class="even">
<td style="text-align: right;">190</td>
<td style="text-align: left;">Je laisse ma chambre en désordre.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">191</td>
<td style="text-align: left;">Je sens que ma vie manque de sens.</td>
</tr>
<tr class="even">
<td style="text-align: right;">192</td>
<td style="text-align: left;">Je reste en arrière-plan.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">193</td>
<td style="text-align: left;">Je ne suis pas facilement affecté par mes émotions.</td>
</tr>
<tr class="even">
<td style="text-align: right;">194</td>
<td style="text-align: left;">Je suis indifférent aux sentiments des autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">195</td>
<td style="text-align: left;">Je ne tiens pas mes promesses.</td>
</tr>
<tr class="even">
<td style="text-align: right;">196</td>
<td style="text-align: left;">Je ne suis pas gêné facilement.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">197</td>
<td style="text-align: left;">J'aime prendre mon temps.</td>
</tr>
<tr class="even">
<td style="text-align: right;">198</td>
<td style="text-align: left;">Je n'aime pas l'idée de changer.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">199</td>
<td style="text-align: left;">Je crie sur les gens</td>
</tr>
<tr class="even">
<td style="text-align: right;">200</td>
<td style="text-align: left;">J'exige la qualité.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">201</td>
<td style="text-align: left;">Je résiste facilement à la tentation.</td>
</tr>
<tr class="even">
<td style="text-align: right;">202</td>
<td style="text-align: left;">Je suis prêt à tout essayer, au moins une fois.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">203</td>
<td style="text-align: left;">J'évite les discussions philosophiques.</td>
</tr>
<tr class="even">
<td style="text-align: right;">204</td>
<td style="text-align: left;">J'ai une très bonne opinion de moi-même.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">205</td>
<td style="text-align: left;">Je perds mon temps.</td>
</tr>
<tr class="even">
<td style="text-align: right;">206</td>
<td style="text-align: left;">Je peux gérer les problèmes complexes.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">207</td>
<td style="text-align: left;">Je ris à haute voix.</td>
</tr>
<tr class="even">
<td style="text-align: right;">208</td>
<td style="text-align: left;">Je crois que les lois devraient être strictement appliquées.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">209</td>
<td style="text-align: left;">Je crois en l'expression "œil pour œil".</td>
</tr>
<tr class="even">
<td style="text-align: right;">210</td>
<td style="text-align: left;">Je me précipite dans l'action.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">211</td>
<td style="text-align: left;">Je ne suis pas facilement perturbé par les événements.</td>
</tr>
<tr class="even">
<td style="text-align: right;">212</td>
<td style="text-align: left;">J'évite le contact avec les autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">213</td>
<td style="text-align: left;">Je n'ai pas une bonne imagination.</td>
</tr>
<tr class="even">
<td style="text-align: right;">214</td>
<td style="text-align: left;">Je soupçonne des motifs cachés chez les autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">215</td>
<td style="text-align: left;">Je ne comprends pas les choses.</td>
</tr>
<tr class="even">
<td style="text-align: right;">216</td>
<td style="text-align: left;">Je ne suis pas facilement agacé.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">217</td>
<td style="text-align: left;">Je n'aime pas les événements où il y a beaucoup de monde.</td>
</tr>
<tr class="even">
<td style="text-align: right;">218</td>
<td style="text-align: left;">Je n'apprécie pas aller à des musées d'art.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">219</td>
<td style="text-align: left;">Je fais semblant de me préoccuper des autres.</td>
</tr>
<tr class="even">
<td style="text-align: right;">220</td>
<td style="text-align: left;">Je laisse traîner mes choses.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">221</td>
<td style="text-align: left;">Je me sens rarement triste.</td>
</tr>
<tr class="even">
<td style="text-align: right;">222</td>
<td style="text-align: left;">J'ai peu à dire.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">223</td>
<td style="text-align: left;">Je remarque rarement mes réactions émotionnelles</td>
</tr>
<tr class="even">
<td style="text-align: right;">224</td>
<td style="text-align: left;">Je mets les gens mal à l'aise</td>
</tr>
<tr class="odd">
<td style="text-align: right;">225</td>
<td style="text-align: left;">J'amène les autres à faire mes tâches.</td>
</tr>
<tr class="even">
<td style="text-align: right;">226</td>
<td style="text-align: left;">Je suis confortable dans des situations inhabituelles.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">227</td>
<td style="text-align: left;">J'aime avoir un style de vie tranquille.</td>
</tr>
<tr class="even">
<td style="text-align: right;">228</td>
<td style="text-align: left;">Je préfère m'en tenir à mes habitudes.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">229</td>
<td style="text-align: left;">J'insulte les gens.</td>
</tr>
<tr class="even">
<td style="text-align: right;">230</td>
<td style="text-align: left;">Je ne suis pas très motivé à réussir.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">231</td>
<td style="text-align: left;">Je suis capable de contrôler mes envies.</td>
</tr>
<tr class="even">
<td style="text-align: right;">232</td>
<td style="text-align: left;">Je recherche le danger.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">233</td>
<td style="text-align: left;">J'ai de la difficulté à comprendre les idées abstraites.</td>
</tr>
<tr class="even">
<td style="text-align: right;">234</td>
<td style="text-align: left;">Je connais les réponses à plusieurs questions.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">235</td>
<td style="text-align: left;">J'ai besoin d'un coup de pouce pour démarrer.</td>
</tr>
<tr class="even">
<td style="text-align: right;">236</td>
<td style="text-align: left;">Je sais m'adapter.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">237</td>
<td style="text-align: left;">Je divertis mes amis.</td>
</tr>
<tr class="even">
<td style="text-align: right;">238</td>
<td style="text-align: left;">Je crois que nous prenons trop soin des criminels.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">239</td>
<td style="text-align: left;">Je tente de ne pas penser aux gens dans le besoin.</td>
</tr>
<tr class="even">
<td style="text-align: right;">240</td>
<td style="text-align: left;">Je fais des choses insensées.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">241</td>
<td style="text-align: left;">Je ne me préoccupe pas de choses qui ont déjà eu lieu.</td>
</tr>
<tr class="even">
<td style="text-align: right;">242</td>
<td style="text-align: left;">Je ne suis pas vraiment intéressé par les autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">243</td>
<td style="text-align: left;">Je me perds rarement dans mes pensées.</td>
</tr>
<tr class="even">
<td style="text-align: right;">244</td>
<td style="text-align: left;">Je me méfie des autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">245</td>
<td style="text-align: left;">J'ai peu à apporter.</td>
</tr>
<tr class="even">
<td style="text-align: right;">246</td>
<td style="text-align: left;">Je garde mon calme.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">247</td>
<td style="text-align: left;">J'évite les foules.</td>
</tr>
<tr class="even">
<td style="text-align: right;">248</td>
<td style="text-align: left;">Je n'aime pas les concerts.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">249</td>
<td style="text-align: left;">Je profite des autres.</td>
</tr>
<tr class="even">
<td style="text-align: right;">250</td>
<td style="text-align: left;">Je ne suis pas incommodé par les personnes désordonnées.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">251</td>
<td style="text-align: left;">Je suis à l'aise avec moi-même.</td>
</tr>
<tr class="even">
<td style="text-align: right;">252</td>
<td style="text-align: left;">Je n'aime pas attirer l'attention sur moi.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">253</td>
<td style="text-align: left;">Je vis très peu de hauts et de bas émotionnels.</td>
</tr>
<tr class="even">
<td style="text-align: right;">254</td>
<td style="text-align: left;">Je tourne le dos aux autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">255</td>
<td style="text-align: left;">Je fais le contraire de ce qui est demandé.</td>
</tr>
<tr class="even">
<td style="text-align: right;">256</td>
<td style="text-align: left;">Je ne suis pas dérangé par les situations sociales difficiles.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">257</td>
<td style="text-align: left;">Je laisse les choses avancer à leur propre rythme.</td>
</tr>
<tr class="even">
<td style="text-align: right;">258</td>
<td style="text-align: left;">Je n'aime pas les nouvelles tendances culinaires.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">259</td>
<td style="text-align: left;">Je m'en prends aux autres.</td>
</tr>
<tr class="even">
<td style="text-align: right;">260</td>
<td style="text-align: left;">Je fais juste assez de travail pour m'en sortir.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">261</td>
<td style="text-align: left;">Je ne dépense jamais plus que je peux me permettre.</td>
</tr>
<tr class="even">
<td style="text-align: right;">262</td>
<td style="text-align: left;">Je ne ferai jamais du deltaplane ou de saut à l'élastique</td>
</tr>
<tr class="odd">
<td style="text-align: right;">263</td>
<td style="text-align: left;">Je ne suis pas intéressé par les discussions théoriques.</td>
</tr>
<tr class="even">
<td style="text-align: right;">264</td>
<td style="text-align: left;">Je me vante de mes vertus.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">265</td>
<td style="text-align: left;">J'ai de la difficulté à commencer les tâches.</td>
</tr>
<tr class="even">
<td style="text-align: right;">266</td>
<td style="text-align: left;">Je surmonte aisément les coups durs.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">267</td>
<td style="text-align: left;">Je ne m'amuse pas facilement.</td>
</tr>
<tr class="even">
<td style="text-align: right;">268</td>
<td style="text-align: left;">Je crois que nous devrions être sévères à propos des crimes.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">269</td>
<td style="text-align: left;">Je crois que les gens devraient se débrouiller seuls.</td>
</tr>
<tr class="even">
<td style="text-align: right;">270</td>
<td style="text-align: left;">J'agis sans réfléchir</td>
</tr>
<tr class="odd">
<td style="text-align: right;">271</td>
<td style="text-align: left;">Je m'adapte facilement aux nouvelles situations.</td>
</tr>
<tr class="even">
<td style="text-align: right;">272</td>
<td style="text-align: left;">Je garde les autres à distance.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">273</td>
<td style="text-align: left;">J'ai de la difficulté à imaginer les choses.</td>
</tr>
<tr class="even">
<td style="text-align: right;">274</td>
<td style="text-align: left;">Je crois que les gens sont essentiellement mauvais.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">275</td>
<td style="text-align: left;">Je ne perçois pas les conséquences d'un acte.</td>
</tr>
<tr class="even">
<td style="text-align: right;">276</td>
<td style="text-align: left;">Je me plains rarement.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">277</td>
<td style="text-align: left;">Je recherche le calme.</td>
</tr>
<tr class="even">
<td style="text-align: right;">278</td>
<td style="text-align: left;">Je n'ai pas de plaisir à regarder des spectacles de danse.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">279</td>
<td style="text-align: left;">J'entrave les plans des autres.</td>
</tr>
<tr class="even">
<td style="text-align: right;">280</td>
<td style="text-align: left;">Je ne suis pas incommodé par le désordre.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">281</td>
<td style="text-align: left;">Je suis très satisfait de moi.</td>
</tr>
<tr class="even">
<td style="text-align: right;">282</td>
<td style="text-align: left;">Je retiens mes opinions.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">283</td>
<td style="text-align: left;">Je ne comprends pas les gens émotifs.</td>
</tr>
<tr class="even">
<td style="text-align: right;">284</td>
<td style="text-align: left;">Je ne prends pas de temps pour les autres.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">285</td>
<td style="text-align: left;">Je dénature les faits.</td>
</tr>
<tr class="even">
<td style="text-align: right;">286</td>
<td style="text-align: left;">Je suis capable de défendre mes intérêts.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">287</td>
<td style="text-align: left;">Je réagis lentement.</td>
</tr>
<tr class="even">
<td style="text-align: right;">288</td>
<td style="text-align: left;">Je suis attaché aux méthodes conventionnelles.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">289</td>
<td style="text-align: left;">Je suis rancunier.</td>
</tr>
<tr class="even">
<td style="text-align: right;">290</td>
<td style="text-align: left;">Je mets peu de temps et d'efforts dans mon travail.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">291</td>
<td style="text-align: left;">Je ne fais jamais de folies.</td>
</tr>
<tr class="even">
<td style="text-align: right;">292</td>
<td style="text-align: left;">Je n'aime pas la musique forte.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">293</td>
<td style="text-align: left;">J'évite les lectures difficiles.</td>
</tr>
<tr class="even">
<td style="text-align: right;">294</td>
<td style="text-align: left;">Je fais en sorte d'être le centre de l'attention</td>
</tr>
<tr class="odd">
<td style="text-align: right;">295</td>
<td style="text-align: left;">Je reporte les décisions.</td>
</tr>
<tr class="even">
<td style="text-align: right;">296</td>
<td style="text-align: left;">Je suis calme, même dans les situations tendues.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">297</td>
<td style="text-align: left;">Je fais rarement des plaisanteries.</td>
</tr>
<tr class="even">
<td style="text-align: right;">298</td>
<td style="text-align: left;">J'aime être debout durant l'hymne national.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">299</td>
<td style="text-align: left;">Je ne supporte pas les gens faibles</td>
</tr>
<tr class="even">
<td style="text-align: right;">300</td>
<td style="text-align: left;">Je fais souvent des plans de dernière minute.</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">Les références</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-costa_jr_manuel_1998" class="csl-entry" role="listitem">
Costa, P. T., McCrae, R. R., &amp; Rolland, J.-P. (1998). <em>Manuel de l’inventaire <span>NEO</span> <span>PI</span>-<span>R</span>.</em> Paris: ECPA.
</div>
<div id="ref-goldberg_broad-bandwidth_1999" class="csl-entry" role="listitem">
Goldberg, L. R. (1999). A broad-bandwidth, public domain, personality inventory measuring the lower-level facets of several five-factor models. <em>Personality Psychology in Europe</em>, <em>7</em>, 7‑28. Consulté à l'adresse <a href="http://admin.umt.edu.pk/Media/Site/STD/FileManager/OsamaArticle/26august2015/A%20broad-bandwidth%20inventory.pdf">http://admin.umt.edu.pk/Media/Site/STD/FileManager/OsamaArticle/26august2015/A%20broad-bandwidth%20inventory.pdf</a>
</div>
<div id="ref-goldberg_international_2006" class="csl-entry" role="listitem">
Goldberg, L. R., Johnson, J. A., Eber, H. W., Hogan, R., Ashton, M. C., Cloninger, C. R., &amp; Gough, H. G. (2006). The international personality item pool and the future of public-domain personality measures. <em>Journal of Research in Personality</em>, <em>40</em>(1), 84‑96. <a href="https://doi.org/10.1016/j.jrp.2005.08.007">https://doi.org/10.1016/j.jrp.2005.08.007</a>
</div>
<div id="ref-gravel_french_nodate" class="csl-entry" role="listitem">
Gravel, M. (s.&nbsp;d.). <em>French (<span>Canadian</span>) <span>Translation</span> of the <span>IPIP</span> <span>Version</span> of the <span>NEO</span> <span>PI</span>-<span>R</span></em>. Consulté à l'adresse <a href="https://ipip.ori.org/FrenchCanadian300-Item-IPIP-NEO.htm">https://ipip.ori.org/FrenchCanadian300-Item-IPIP-NEO.htm</a>
</div>
<div id="ref-hagger-johnson_conscientiousness_2007" class="csl-entry" role="listitem">
Hagger-Johnson, G. E., &amp; Whiteman, M. C. (2007). Conscientiousness facets and health behaviors: <span>A</span> latent variable modeling approach. <em>Personality and Individual Differences</em>, <em>43</em>(5), 1235‑1245. <a href="https://doi.org/10.1016/j.paid.2007.03.014">https://doi.org/10.1016/j.paid.2007.03.014</a>
</div>
<div id="ref-kajonius_assessing_2019" class="csl-entry" role="listitem">
Kajonius, P. J., &amp; Johnson, J. A. (2019). Assessing the <span>Structure</span> of the <span>Five</span> <span>Factor</span> <span>Model</span> of <span>Personality</span> (<span>IPIP</span>-<span>NEO</span>-120) in the <span>Public</span> <span>Domain</span>. <em>Europe’s Journal of Psychology</em>, <em>15</em>(2), 260‑275. <a href="https://doi.org/10.5964/ejop.v15i2.1671">https://doi.org/10.5964/ejop.v15i2.1671</a>
</div>
<div id="ref-karlin_300_nodate" class="csl-entry" role="listitem">
Karlin, O. (s.&nbsp;d.). <em>300 <span>IPIP</span> items in the scales measuring constructs similar to those in the <span>NEO</span>-<span>PI</span>-<span>R</span>.</em> Consulté à l'adresse <a href="https://ipip.ori.org/JapaneseIPIP-NEOFacets.htm">https://ipip.ori.org/JapaneseIPIP-NEOFacets.htm</a>
</div>
<div id="ref-lewis_relationship_2010" class="csl-entry" role="listitem">
Lewis, A. R., Zinbarg, R. E., Mineka, S., Craske, M. G., Epstein, A., &amp; Griffith, J. W. (2010). The relationship between anxiety sensitivity and latent symptoms of emotional problems: <span>A</span> structural equation modeling approach. <em>Behaviour Research and Therapy</em>, <em>48</em>(8), 761‑769. <a href="https://doi.org/10.1016/j.brat.2010.05.001">https://doi.org/10.1016/j.brat.2010.05.001</a>
</div>
<div id="ref-lim_assessing_2006" class="csl-entry" role="listitem">
Lim, B.-C., &amp; Ployhart, R. E. (2006). Assessing the <span>Convergent</span> and <span>Discriminant</span> <span>Validity</span> of <span>Goldberg</span>’s <span>International</span> <span>Personality</span> <span>Item</span> <span>Pool</span>: <span>A</span> <span>Multitrait</span>-<span>Multimethod</span> <span>Examination</span>. <em>Organizational Research Methods</em>, <em>9</em>(1), 29‑54. <a href="https://doi.org/10.1177/1094428105283193">https://doi.org/10.1177/1094428105283193</a>
</div>
<div id="ref-longley_taxometric_2017" class="csl-entry" role="listitem">
Longley, S. L., Miller, S. A., Broman-Fulks, J., Calamari, J. E., Holm-Denoma, J. M., &amp; Meyers, K. (2017). Taxometric analyses of higher-order personality domains. <em>Personality and Individual Differences</em>, <em>108</em>, 207‑219. <a href="https://doi.org/10.1016/j.paid.2016.12.018">https://doi.org/10.1016/j.paid.2016.12.018</a>
</div>
<div id="ref-maples_test_2014" class="csl-entry" role="listitem">
Maples, J. L., Guan, L., Carter, N. T., &amp; Miller, J. D. (2014). A test of the <span>International</span> <span>Personality</span> <span>Item</span> <span>Pool</span> representation of the <span>Revised</span> <span>NEO</span> <span>Personality</span> <span>Inventory</span> and development of a 120-item <span>IPIP</span>-based measure of the five-factor model. <em>Psychological Assessment</em>, <em>26</em>(4), 1070‑1084. <a href="https://doi.org/10.1037/pas0000004">https://doi.org/10.1037/pas0000004</a>
</div>
<div id="ref-microsoft_corporation_microsoft_2018" class="csl-entry" role="listitem">
Microsoft. (2018). <em>Microsoft <span>Excel</span></em>. Consulté à l'adresse <a href="https://office.microsoft.com/excel">https://office.microsoft.com/excel</a>
</div>
<div id="ref-musek_j_slovene_nodate" class="csl-entry" role="listitem">
Musek, J. (s.&nbsp;d.). <em>Slovene <span>Translation</span> of the <span>IPIP</span> <span>NEO</span> <span>PI</span> <span>Facets</span></em>. Consulté à l'adresse <a href="https://ipip.ori.org/SloveneIPIP-NEOFacets.htm">https://ipip.ori.org/SloveneIPIP-NEOFacets.htm</a>
</div>
<div id="ref-rehman2020structural" class="csl-entry" role="listitem">
Rehman, M., Muellenbach, M., &amp; Johnson, J. A. (2020). Structural Validity and Reliability of The Urdu Translated Version of IPIP-NEO-300 Web-Based Inventory. <em>Available at SSRN 3637681</em>. Consulté à l'adresse <a href="https://www.academia.edu/download/63770760/Structural_Validity_of_Urdu_IPIP-NEO-30020200628-73673-52nm9i.pdf">https://www.academia.edu/download/63770760/Structural_Validity_of_Urdu_IPIP-NEO-30020200628-73673-52nm9i.pdf</a>
</div>
<div id="ref-robert_p_liberal_nodate" class="csl-entry" role="listitem">
Robert, P. (s.&nbsp;d.). Libéral. Consulté à l'adresse <a href="https://dictionnaire.lerobert.com/">https://dictionnaire.lerobert.com/</a>
</div>
<div id="ref-siddiqui_personality_2011" class="csl-entry" role="listitem">
Siddiqui, K. (2011). Personality <span>Influences</span> on <span>Mobile</span> <span>Phone</span> <span>Usage</span>. <em>Interdisciplinary Journal of Contempory Research in Business</em>, <em>3</em>(3), 554‑565. Consulté à l'adresse <a href="https://www.researchgate.net/publication/256494774_Personality_Influences_on_Mobile_Phone_Usage">https://www.researchgate.net/publication/256494774_Personality_Influences_on_Mobile_Phone_Usage</a>
</div>
<div id="ref-vallerand_vers_1989" class="csl-entry" role="listitem">
Vallerand, R. J. (1989). Vers une méthodologie de validation trans-culturelle de questionnaires psychologiques: <span>Implications</span> pour la recherche en langue française. <em>Canadian Psychology / Psychologie canadienne</em>, <em>30</em>(4), 662‑680. <a href="https://doi.org/10.1037/h0079856">https://doi.org/10.1037/h0079856</a>
</div>
<div id="ref-verreault_francais_nodate" class="csl-entry" role="listitem">
Verreault, C. (s.&nbsp;d.). <em>Français international, français québécois ou jouai : quelle langue parlent donc les <span>Québécois</span> ?</em>
</div>
</div></section><section class="quarto-appendix-contents" id="quarto-citation"><h2 class="anchored quarto-appendix-heading">Citation</h2><div><div class="quarto-appendix-secondary-label">BibTeX</div><pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@online{thiry2023,
  author = {Thiry, Benjamin and Piolti, Maëva},
  title = {IPIP NEO 300, adapation française européenne},
  date = {2023-02-12},
  url = {https://benjaminthiry.netlify.app/posts/2023-02-12-ipipneo300fr/},
  langid = {fr}
}
</code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre><div class="quarto-appendix-secondary-label">Veuillez citer ce travail comme suit&nbsp;:</div><div id="ref-thiry2023" class="csl-entry quarto-appendix-citeas" role="listitem">
Thiry, B., &amp; Piolti, M. (2023, February 12). IPIP NEO 300, adapation
française européenne. Retrieved from <a href="https://benjaminthiry.netlify.app/posts/2023-02-12-ipipneo300fr/">https://benjaminthiry.netlify.app/posts/2023-02-12-ipipneo300fr/</a>
</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copié");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copié");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/benjaminthiry\.netlify\.app");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="ouriagan/blogcomments" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->




</body></html>